# Part 1: Pandas - from Zero to Hero

## DataFrame Basics III

### Sorting DataFrames

In [1]:
import pandas as pd

In [2]:
titanic = pd.read_csv("titanic.csv")

In [3]:
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [4]:
titanic.age.sort_values()

803    0.42
755    0.67
644    0.75
469    0.75
78     0.83
       ...
859     NaN
863     NaN
868     NaN
878     NaN
888     NaN
Name: age, Length: 891, dtype: float64

In [14]:
titanic.sort_values(by = "age")

     survived  pclass     sex    age  sibsp  parch      fare embarked deck
803         1       3    male   0.42      0      1    8.5167        C  NaN
755         1       2    male   0.67      1      1   14.5000        S  NaN
469         1       3  female   0.75      2      1   19.2583        C  NaN
644         1       3  female   0.75      2      1   19.2583        C  NaN
78          1       2    male   0.83      0      2   29.0000        S  NaN
831         1       2    male   0.83      1      1   18.7500        S  NaN
305         1       1    male   0.92      1      2  151.5500        S    C
788         1       3    male   1.00      1      2   20.5750        S  NaN
172         1       3  female   1.00      1      1   11.1333        S  NaN
381         1       3  female   1.00      0      2   15.7417        C  NaN
386         0       3    male   1.00      5      2   46.9000        S  NaN
827         1       2    male   1.00      0      2   37.0042        C  NaN
183         1       2    male   1.00      2      1   39.0000        S    F
164         0       3    male   1.00      4      1   39.6875        S  NaN
340         1       2    male   2.00      1      1   26.0000        S    F
824         0       3    male   2.00      4      1   39.6875        S  NaN
16          0       3    male   2.00      4      1   29.1250        Q  NaN
7           0       3    male   2.00      3      1   21.0750        S  NaN
530         1       2  female   2.00      1      1   26.0000        S  NaN
297         0       1  female   2.00      1      2  151.5500        S    C
119         0       3  female   2.00      4      2   31.2750        S  NaN
642         0       3  female   2.00      3      2   27.9000        S  NaN
479         1       3  female   2.00      0      1   12.2875        S  NaN
205         0       3  female   2.00      0      1   10.4625        S    G
407         1       2    male   3.00      1      1   18.7500        S  NaN
348         1       3    male   3.00      1      1   15.9000        S  NaN
261         1       3    male   3.00      4      2   31.3875        S  NaN
374         0       3  female   3.00      3      1   21.0750        S  NaN
193         1       2    male   3.00      1      1   26.0000        S    F
43          1       2  female   3.00      1      2   41.5792        C  NaN
63          0       3    male   4.00      3      2   27.9000        S  NaN
171         0       3    male   4.00      4      1   29.1250        Q  NaN
445         1       1    male   4.00      0      2   81.8583        S    A
691         1       3  female   4.00      0      1   13.4167        C  NaN
750         1       2  female   4.00      1      1   23.0000        S  NaN
850         0       3    male   4.00      4      2   31.2750        S  NaN
869         1       3    male   4.00      1      1   11.1333        S  NaN
184         1       3  female   4.00      0      2   22.0250        S  NaN
10          1       3  female   4.00      1      1   16.7000        S    G
618         1       2  female   4.00      2      1   39.0000        S    F
58          1       2  female   5.00      1      2   27.7500        S  NaN
777         1       3  female   5.00      0      0   12.4750        S  NaN
233         1       3  female   5.00      4      2   31.3875        S  NaN
448         1       3  female   5.00      2      1   19.2583        C  NaN
720         1       2  female   6.00      0      1   33.0000        S  NaN
813         0       3  female   6.00      4      2   31.2750        S  NaN
751         1       3    male   6.00      0      1   12.4750        S    E
535         1       2  female   7.00      0      2   26.2500        S  NaN
278         0       3    male   7.00      4      1   29.1250        Q  NaN
50          0       3    male   7.00      4      1   39.6875        S  NaN
787         0       3    male   8.00      4      1   29.1250        Q  NaN
24          0       3  female   8.00      3      1   21.0750        S  NaN
237         1       2  female   8.00      0      2   26.2500        S  NaN
549         1       2    male   8.00      1      1   36.7500        S  NaN
634         0       3  female   9.00      3      2   27.9000        S  NaN
541         0       3  female   9.00      4      2   31.2750        S  NaN
852         0       3  female   9.00      1      1   15.2458        C  NaN
147         0       3  female   9.00      2      2   34.3750        S  NaN
480         0       3    male   9.00      5      2   46.9000        S  NaN
165         1       3    male   9.00      0      2   20.5250        S  NaN
489         1       3    male   9.00      1      1   15.9000        S  NaN
182         0       3    male   9.00      4      2   31.3875        S  NaN
419         0       3  female  10.00      0      2   24.1500        S  NaN
819         0       3    male  10.00      3      2   27.9000        S  NaN
731         0       3    male  11.00      0      0   18.7875        C  NaN
59          0       3    male  11.00      5      2   46.9000        S  NaN
802         1       1    male  11.00      1      2  120.0000        S    B
542         0       3  female  11.00      4      2   31.2750        S  NaN
125         1       3    male  12.00      1      0   11.2417        C  NaN
446         1       2  female  13.00      0      1   19.5000        S  NaN
780         1       3  female  13.00      0      0    7.2292        C  NaN
683         0       3    male  14.00      5      2   46.9000        S  NaN
686         0       3    male  14.00      4      1   39.6875        S  NaN
435         1       1  female  14.00      1      2  120.0000        S    B
14          0       3  female  14.00      0      0    7.8542        S  NaN
39          1       3  female  14.00      1      0   11.2417        C  NaN
9           1       2  female  14.00      1      0   30.0708        C  NaN
111         0       3  female  14.50      1      0   14.4542        C  NaN
352         0       3    male  15.00      1      1    7.2292        C  NaN
22          1       3  female  15.00      0      0    8.0292        Q  NaN
689         1       1  female  15.00      0      1  211.3375        S    B
830         1       3  female  15.00      1      0   14.4542        C  NaN
875         1       3  female  15.00      0      0    7.2250        C  NaN
71          0       3  female  16.00      5      2   46.9000        S  NaN
282         0       3    male  16.00      0      0    9.5000        S  NaN
333         0       3    male  16.00      2      0   18.0000        S  NaN
791         0       2    male  16.00      0      0   26.0000        S  NaN
208         1       3  female  16.00      0      0    7.7500        Q  NaN
266         0       3    male  16.00      4      1   39.6875        S  NaN
156         1       3  female  16.00      0      0    7.7333        Q  NaN
574         0       3    male  16.00      0      0    8.0500        S  NaN
86          0       3    male  16.00      1      3   34.3750        S  NaN
138         0       3    male  16.00      0      0    9.2167        S  NaN
220         1       3    male  16.00      0      0    8.0500        S  NaN
841         0       2    male  16.00      0      0   10.5000        S  NaN
504         1       1  female  16.00      0      0   86.5000        S    B
329         1       1  female  16.00      0      1   57.9792        C    B
853         1       1  female  16.00      0      1   39.4000        S    D
764         0       3    male  16.00      0      0    7.7750        S  NaN
746         0       3    male  16.00      1      1   20.2500        S  NaN
500         0       3    male  17.00      0      0    8.6625        S  NaN
721         0       3    male  17.00      1      0    7.0542        S  NaN
433         0       3    male  17.00      0      0    7.1250        S  NaN
532         0       3    male  17.00      1      1    7.2292        C  NaN
844         0       3    male  17.00      0      0    8.6625        S  NaN
68          1       3  female  17.00      4      2    7.9250        S  NaN
84          1       2  female  17.00      0      0   10.5000        S  NaN
389         1       2  female  17.00      0      0   12.0000        C  NaN
114         0       3  female  17.00      0      0   14.4583        C  NaN
163         0       3    male  17.00      0      0    8.6625        S  NaN
307         1       1  female  17.00      1      0  108.9000        C    C
781         1       1  female  17.00      1      0   57.0000        S    B
550         1       1    male  17.00      0      2  110.8833        C    C
144         0       2    male  18.00      0      0   11.5000        S  NaN
505         0       1    male  18.00      1      0  108.9000        C    C
49          0       3  female  18.00      1      0   17.8000        S  NaN
385         0       2    male  18.00      0      0   73.5000        S  NaN
757         0       2    male  18.00      0      0   11.5000        S  NaN
228         0       2    male  18.00      0      0   13.0000        S  NaN
38          0       3  female  18.00      2      0   18.0000        S  NaN
175         0       3    male  18.00      1      1    7.8542        S  NaN
688         0       3    male  18.00      0      0    7.7958        S  NaN
204         1       3    male  18.00      0      0    8.0500        S  NaN
677         1       3  female  18.00      0      0    9.8417        S  NaN
855         1       3  female  18.00      0      1    9.3500        S  NaN
807         0       3  female  18.00      0      0    7.7750        S  NaN
654         0       3  female  18.00      0      0    6.7500        Q  NaN
786         1       3  female  18.00      0      0    7.4958        S  NaN
702         0       3  female  18.00      0      1   14.4542        C  NaN
417         1       2  female  18.00      0      2   13.0000        S  NaN
651         1       2  female  18.00      0      1   23.0000        S  NaN
700         1       1  female  18.00      1      0  227.5250        C    C
585         1       1  female  18.00      0      2   79.6500        S    E
311         1       1  female  18.00      2      2  262.3750        C    B
834         0       3    male  18.00      0      0    8.3000        S  NaN
675         0       3    male  18.00      0      0    7.7750        S  NaN
424         0       3    male  18.00      1      1   20.2125        S  NaN
775         0       3    male  18.00      0      0    7.7500        S  NaN
371         0       3    male  18.00      1      0    6.4958        S  NaN
427         1       2  female  19.00      0      0   26.0000        S  NaN
226         1       2    male  19.00      0      0   10.5000        S  NaN
191         0       2    male  19.00      0      0   13.0000        S  NaN
145         0       2    male  19.00      1      1   36.7500        S  NaN
877         0       3    male  19.00      0      0    7.8958        S  NaN
887         1       1  female  19.00      0      0   30.0000        S    B
372         0       3    male  19.00      0      0    8.0500        S  NaN
291         1       1  female  19.00      1      0   91.0792        C    B
136         1       1  female  19.00      0      2   26.2833        S    D
546         1       2  female  19.00      1      0   26.0000        S  NaN
283         1       3    male  19.00      0      0    8.0500        S  NaN
238         0       2    male  19.00      0      0   10.5000        S  NaN
143         0       3    male  19.00      0      0    6.7500        Q  NaN
566         0       3    male  19.00      0      0    7.8958        S  NaN
748         0       1    male  19.00      1      0   53.1000        S    D
27          0       1    male  19.00      3      2  263.0000        S    C
192         1       3  female  19.00      1      0    7.8542        S  NaN
44          1       3  female  19.00      0      0    7.8792        Q  NaN
302         0       3    male  19.00      0      0    0.0000        S  NaN
379         0       3    male  19.00      0      0    7.7750        S  NaN
646         0       3    male  19.00      0      0    7.8958        S  NaN
687         0       3    male  19.00      0      0   10.1708        S  NaN
67          0       3    male  19.00      0      0    8.1583        S  NaN
575         0       3    male  19.00      0      0   14.5000        S  NaN
715         0       3    male  19.00      0      0    7.6500        S    F
404         0       3  female  20.00      0      0    8.6625        S  NaN
113         0       3  female  20.00      1      0    9.8250        S  NaN
441         0       3    male  20.00      0      0    9.5000        S  NaN
378         0       3    male  20.00      0      0    4.0125        C  NaN
12          0       3    male  20.00      0      0    8.0500        S  NaN
876         0       3    male  20.00      0      0    9.8458        S  NaN
664         1       3    male  20.00      1      0    7.9250        S  NaN
762         1       3    male  20.00      0      0    7.2292        C  NaN
622         1       3    male  20.00      1      1   15.7417        C  NaN
131         0       3    male  20.00      0      0    7.0500        S  NaN
725         0       3    male  20.00      0      0    8.6625        S  NaN
91          0       3    male  20.00      0      0    7.8542        S  NaN
640         0       3    male  20.00      0      0    7.8542        S  NaN
682         0       3    male  20.00      0      0    9.2250        S  NaN
840         0       3    male  20.00      0      0    7.9250        S  NaN
227         0       3    male  20.50      0      0    7.2500        S  NaN
56          1       2  female  21.00      0      0   10.5000        S  NaN
436         0       3  female  21.00      2      2   34.3750        S  NaN
402         0       3  female  21.00      1      0    9.8250        S  NaN
501         0       3  female  21.00      0      0    7.7500        Q  NaN
72          0       2    male  21.00      0      0   73.5000        S  NaN
120         0       2    male  21.00      2      0   73.5000        S  NaN
491         0       3    male  21.00      0      0    7.2500        S  NaN
106         1       3  female  21.00      0      0    7.6500        S  NaN
861         0       2    male  21.00      1      0   11.5000        S  NaN
836         0       3    male  21.00      0      0    8.6625        S  NaN
115         0       3    male  21.00      0      0    7.9250        S  NaN
51          0       3    male  21.00      0      0    7.8000        S  NaN
624         0       3    male  21.00      0      0   16.1000        S  NaN
173         0       3    male  21.00      0      0    7.9250        S  NaN
421         0       3    male  21.00      0      0    7.7333        Q  NaN
623         0       3    male  21.00      0      0    7.8542        S  NaN
742         1       1  female  21.00      2      2  262.3750        C    B
391         1       3    male  21.00      0      0    7.7958        S  NaN
494         0       3    male  21.00      0      0    8.0500        S  NaN
652         0       3    male  21.00      0      0    8.4333        S  NaN
37          0       3    male  21.00      0      0    8.0500        S  NaN
408         0       3    male  21.00      0      0    7.7750        S  NaN
102         0       1    male  21.00      0      1   77.2875        S    D
627         1       1  female  21.00      0      0   77.9583        S    D
554         1       3  female  22.00      0      0    7.7750        S  NaN
539         1       1  female  22.00      0      2   49.5000        C    B
553         1       3    male  22.00      0      0    7.2250        C  NaN
588         0       3    male  22.00      0      0    8.0500        S  NaN
243         0       3    male  22.00      0      0    7.1250        S  NaN
478         0       3    male  22.00      0      0    7.5208        S  NaN
151         1       1  female  22.00      1      0   66.6000        S    C
356         1       1  female  22.00      0      1   55.0000        S    E
708         1       1  female  22.00      0      0  151.5500        S  NaN
60          0       3    male  22.00      0      0    7.2292        C  NaN
882         0       3  female  22.00      0      0   10.5167        S  NaN
289         1       3  female  22.00      0      0    7.7500        Q  NaN
287         0       3    male  22.00      0      0    7.8958        S  NaN
320         0       3    male  22.00      0      0    7.2500        S  NaN
608         1       2  female  22.00      1      2   41.5792        C  NaN
80          0       3    male  22.00      0      0    9.0000        S  NaN
373         0       1    male  22.00      0      0  135.6333        C  NaN
112         0       3    male  22.00      0      0    8.0500        S  NaN
212         0       3    male  22.00      0      0    7.2500        S  NaN
141         1       3  female  22.00      0      0    7.7500        S  NaN
225         0       3    male  22.00      0      0    9.3500        S  NaN
521         0       3    male  22.00      0      0    7.8958        S  NaN
323         1       2  female  22.00      1      1   29.0000        S  NaN
0           0       3    male  22.00      1      0    7.2500        S  NaN
395         0       3    male  22.00      0      0    7.7958        S  NaN
376         1       3  female  22.00      0      0    7.2500        S  NaN
474         0       3  female  22.00      0      0    9.8375        S  NaN
816         0       3  female  23.00      0      0    7.9250        S  NaN
398         0       2    male  23.00      0      0   10.5000        S  NaN
350         0       3    male  23.00      0      0    9.2250        S  NaN
393         1       1  female  23.00      1      0  113.2750        C    D
833         0       3    male  23.00      0      0    7.8542        S  NaN
135         0       2    male  23.00      0      0   15.0458        C  NaN
733         0       2    male  23.00      0      0   13.0000        S  NaN
88          1       1  female  23.00      3      2  263.0000        S    C
473         1       2  female  23.00      0      0   13.7917        C    D
658         0       2    male  23.00      0      0   13.0000        S  NaN
753         0       3    male  23.00      0      0    7.8958        S  NaN
97          1       1    male  23.00      0      1   63.3583        C    D
529         0       2    male  23.00      2      1   11.5000        S  NaN
734         0       2    male  23.00      0      0   13.0000        S  NaN
649         1       3  female  23.00      0      0    7.5500        S  NaN
296         0       3    male  23.50      0      0    7.2292        C  NaN
615         1       2  female  24.00      1      2   65.0000        S  NaN
565         0       3    male  24.00      2      0   24.1500        S  NaN
89          0       3    male  24.00      0      0    8.0500        S  NaN
641         1       1  female  24.00      0      0   69.3000        C    B
310         1       1  female  24.00      0      0   83.1583        C    C
341         1       1  female  24.00      3      2  263.0000        S    C
369         1       1  female  24.00      0      0   69.3000        C    B
710         1       1  female  24.00      0      0   49.5042        C    C
234         0       2    male  24.00      0      0   10.5000        S  NaN
655         0       2    male  24.00      2      0   73.5000        S  NaN
864         0       2    male  24.00      0      0   13.0000        S  NaN
499         0       3    male  24.00      0      0    7.7958        S  NaN
199         0       2  female  24.00      0      0   13.0000        S  NaN
294         0       3    male  24.00      0      0    7.8958        S  NaN
743         0       3    male  24.00      1      0   16.1000        S  NaN
316         1       2  female  24.00      1      0   26.0000        S  NaN
247         1       2  female  24.00      0      2   14.5000        S  NaN
437         1       2  female  24.00      2      3   18.7500        S  NaN

In [15]:
titanic

     survived  pclass     sex    age  sibsp  parch      fare embarked deck
275         1       1  female  63.00      1      0   77.9583        S    D
829         1       1  female  62.00      0      0   80.0000      NaN    B
366         1       1  female  60.00      1      0   75.2500        C    D
268         1       1  female  58.00      0      1  153.4625        S    C
11          1       1  female  58.00      0      0   26.5500        S    C
195         1       1  female  58.00      0      0  146.5208        C    B
879         1       1  female  56.00      0      1   83.1583        C    C
496         1       1  female  54.00      1      0   78.2667        C    D
513         1       1  female  54.00      1      0   59.4000        C  NaN
571         1       1  female  53.00      2      0   51.4792        S    C
820         1       1  female  52.00      1      1   93.5000        S    B
591         1       1  female  52.00      1      0   78.2667        C    D
765         1       1  female  51.00      1      0   77.9583        S    D
299         1       1  female  50.00      0      1  247.5208        C    B
177         0       1  female  50.00      0      0   28.7125        C    C
52          1       1  female  49.00      1      0   76.7292        C    D
796         1       1  female  49.00      0      0   25.9292        S    D
556         1       1  female  48.00      1      0   39.6000        C    A
862         1       1  female  48.00      0      0   25.9292        S    D
871         1       1  female  47.00      1      1   52.5542        S    D
856         1       1  female  45.00      1      1  164.8667        S  NaN
523         1       1  female  44.00      0      1   57.9792        C    B
194         1       1  female  44.00      0      0   27.7208        C    B
779         1       1  female  43.00      0      1  211.3375        S    B
380         1       1  female  42.00      0      0  227.5250        C  NaN
337         1       1  female  41.00      0      0  134.5000        C    E
609         1       1  female  40.00      0      0  153.4625        S    C
319         1       1  female  40.00      1      1  134.5000        C    E
581         1       1  female  39.00      1      1  110.8833        C    C
577         1       1  female  39.00      1      0   55.9000        S    E
558         1       1  female  39.00      1      1   79.6500        S    E
835         1       1  female  39.00      1      1   83.1583        C    E
716         1       1  female  38.00      0      0  227.5250        C    C
61          1       1  female  38.00      0      0   80.0000      NaN    B
1           1       1  female  38.00      1      0   71.2833        C    C
763         1       1  female  36.00      1      2  120.0000        S    B
540         1       1  female  36.00      0      2   71.0000        S    B
325         1       1  female  36.00      0      0  135.6333        C    C
486         1       1  female  35.00      1      0   90.0000        S    C
383         1       1  female  35.00      1      0   52.0000        S  NaN
269         1       1  female  35.00      0      0  135.6333        S    C
230         1       1  female  35.00      1      0   83.4750        S    C
3           1       1  female  35.00      1      0   53.1000        S    C
258         1       1  female  35.00      0      0  512.3292        C  NaN
809         1       1  female  33.00      1      0   53.1000        S    E
412         1       1  female  33.00      1      0   90.0000        Q    C
759         1       1  female  33.00      0      0   86.5000        S    B
218         1       1  female  32.00      0      0   76.2917        C    D
215         1       1  female  31.00      1      0  113.2750        C    D
318         1       1  female  31.00      0      2  164.8667        S    C
842         1       1  female  30.00      0      0   31.0000        C  NaN
520         1       1  female  30.00      0      0   93.5000        S    B
257         1       1  female  30.00      0      0   86.5000        S    B
309         1       1  female  30.00      0      0   56.9292        C    E
537         1       1  female  30.00      0      0  106.4250        C  NaN
730         1       1  female  29.00      0      0  211.3375        S    B
290         1       1  female  26.00      0      0   78.8500        S  NaN
498         0       1  female  25.00      1      2  151.5500        S    C
710         1       1  female  24.00      0      0   49.5042        C    C
369         1       1  female  24.00      0      0   69.3000        C    B
341         1       1  female  24.00      3      2  263.0000        S    C
310         1       1  female  24.00      0      0   83.1583        C    C
641         1       1  female  24.00      0      0   69.3000        C    B
393         1       1  female  23.00      1      0  113.2750        C    D
88          1       1  female  23.00      3      2  263.0000        S    C
708         1       1  female  22.00      0      0  151.5500        S  NaN
356         1       1  female  22.00      0      1   55.0000        S    E
151         1       1  female  22.00      1      0   66.6000        S    C
539         1       1  female  22.00      0      2   49.5000        C    B
627         1       1  female  21.00      0      0   77.9583        S    D
742         1       1  female  21.00      2      2  262.3750        C    B
136         1       1  female  19.00      0      2   26.2833        S    D
291         1       1  female  19.00      1      0   91.0792        C    B
887         1       1  female  19.00      0      0   30.0000        S    B
700         1       1  female  18.00      1      0  227.5250        C    C
585         1       1  female  18.00      0      2   79.6500        S    E
311         1       1  female  18.00      2      2  262.3750        C    B
781         1       1  female  17.00      1      0   57.0000        S    B
307         1       1  female  17.00      1      0  108.9000        C    C
853         1       1  female  16.00      0      1   39.4000        S    D
329         1       1  female  16.00      0      1   57.9792        C    B
504         1       1  female  16.00      0      0   86.5000        S    B
689         1       1  female  15.00      0      1  211.3375        S    B
435         1       1  female  14.00      1      2  120.0000        S    B
297         0       1  female   2.00      1      2  151.5500        S    C
31          1       1  female    NaN      1      0  146.5208        C    B
166         1       1  female    NaN      0      1   55.0000        S    E
256         1       1  female    NaN      0      0   79.2000        C  NaN
306         1       1  female    NaN      0      0  110.8833        C  NaN
334         1       1  female    NaN      1      0  133.6500        S  NaN
375         1       1  female    NaN      1      0   82.1708        C  NaN
457         1       1  female    NaN      1      0   51.8625        S    D
669         1       1  female    NaN      1      0   52.0000        S    C
849         1       1  female    NaN      1      0   89.1042        C    C
630         1       1    male  80.00      0      0   30.0000        S    A
493         0       1    male  71.00      0      0   49.5042        C  NaN
96          0       1    male  71.00      0      0   34.6542        C    A
745         0       1    male  70.00      1      1   71.0000        S    B
54          0       1    male  65.00      0      1   61.9792        C    B
456         0       1    male  65.00      0      0   26.5500        S    E
438         0       1    male  64.00      1      4  263.0000        S    C
545         0       1    male  64.00      0      0   26.0000        S  NaN
252         0       1    male  62.00      0      0   26.5500        S    C
555         0       1    male  62.00      0      0   26.5500        S  NaN
625         0       1    male  61.00      0      0   32.3208        S    D
170         0       1    male  61.00      0      0   33.5000        S    B
694         0       1    male  60.00      0      0   26.5500        S  NaN
587         1       1    male  60.00      1      1   79.2000        C    B
487         0       1    male  58.00      0      0   29.7000        C    B
659         0       1    male  58.00      0      2  113.2750        C    D
174         0       1    male  56.00      0      0   30.6958        C    A
647         1       1    male  56.00      0      0   35.5000        C    A
467         0       1    male  56.00      0      0   26.5500        S  NaN
492         0       1    male  55.00      0      0   30.5000        S    C
124         0       1    male  54.00      0      1   77.2875        S    D
6           0       1    male  54.00      0      0   51.8625        S    E
449         1       1    male  52.00      0      0   30.5000        S    C
262         0       1    male  52.00      1      1   79.6500        S    E
155         0       1    male  51.00      0      1   61.3792        C  NaN
857         1       1    male  51.00      0      0   26.5500        S    E
660         1       1    male  50.00      2      0  133.6500        S  NaN
434         0       1    male  50.00      1      0   55.9000        S    E
544         0       1    male  50.00      1      0  106.4250        C    C
698         0       1    male  49.00      1      1  110.8833        C    C
453         1       1    male  49.00      1      0   89.1042        C    C
599         1       1    male  49.00      1      0   56.9292        C    A
645         1       1    male  48.00      1      0   76.7292        C    D
460         1       1    male  48.00      0      0   26.5500        S    E
712         1       1    male  48.00      1      0   52.0000        S    C
662         0       1    male  47.00      0      0   25.5875        S    E
462         0       1    male  47.00      0      0   38.5000        S    E
110         0       1    male  47.00      0      0   52.0000        S    C
515         0       1    male  47.00      0      0   34.0208        S    D
789         0       1    male  46.00      0      0   79.2000        C    B
92          0       1    male  46.00      1      0   61.1750        S    E
331         0       1    male  45.50      0      0   28.5000        S    C
536         0       1    male  45.00      0      0   26.5500        S    B
187         1       1    male  45.00      0      0   26.5500        S  NaN
339         0       1    male  45.00      0      0   35.5000        S  NaN
62          0       1    male  45.00      1      0   83.4750        S    C
245         0       1    male  44.00      2      0   90.0000        Q    C
35          0       1    male  42.00      1      0   52.0000        S  NaN
621         1       1    male  42.00      1      0   52.5542        S    D
707         1       1    male  42.00      0      0   26.2875        S    E
30          0       1    male  40.00      0      0   27.7208        C  NaN
209         1       1    male  40.00      0      0   31.0000        C    A
263         0       1    male  40.00      0      0    0.0000        S    B
806         0       1    male  39.00      0      0    0.0000        S    A
332         0       1    male  38.00      0      1  153.4625        S    C
224         1       1    male  38.00      1      0   90.0000        S    C
822         0       1    male  38.00      0      0    0.0000        S  NaN
137         0       1    male  37.00      1      0   53.1000        S    C
273         0       1    male  37.00      0      1   29.7000        C    C
248         1       1    male  37.00      1      1   52.5542        S    D
679         1       1    male  36.00      0      1  512.3292        C    B
390         1       1    male  36.00      1      2  120.0000        S    B
512         1       1    male  36.00      0      0   26.2875        S    E
572         1       1    male  36.00      0      0   26.3875        S    E
583         0       1    male  36.00      0      0   40.1250        C    A
741         0       1    male  36.00      1      0   78.8500        S    C
737         1       1    male  35.00      0      0  512.3292        C    B
701         1       1    male  35.00      0      0   26.2875        S    E
604         1       1    male  35.00      0      0   26.5500        C  NaN
447         1       1    male  34.00      0      0   26.5500        S  NaN
872         0       1    male  33.00      0      0    5.0000        S    B
632         1       1    male  32.00      0      0   30.5000        C    B
690         1       1    male  31.00      1      0   57.0000        S    B
671         0       1    male  31.00      1      0   52.0000        S    B
867         0       1    male  31.00      0      0   50.4958        S    A
452         0       1    male  30.00      0      0   27.7500        C    C
782         0       1    male  29.00      0      0   30.0000        S    D
336         0       1    male  29.00      1      0   66.6000        S    C
23          1       1    male  28.00      0      0   35.5000        S    A
34          0       1    male  28.00      1      0   82.1708        C  NaN
83          0       1    male  28.00      0      0   47.1000        S  NaN
430         1       1    male  28.00      0      0   26.5500        S    C
681         1       1    male  27.00      0      0   76.7292        C    D
607         1       1    male  27.00      0      0   30.5000        S  NaN
724         1       1    male  27.00      1      0   53.1000        S    E
377         0       1    male  27.00      0      2  211.5000        C    C
889         1       1    male  26.00      0      0   30.0000        C    C
484         1       1    male  25.00      1      0   91.0792        C    B
370         1       1    male  25.00      1      0   55.4417        C    E
118         0       1    male  24.00      0      1  247.5208        C    B
139         0       1    male  24.00      0      0   79.2000        C    B
97          1       1    male  23.00      0      1   63.3583        C    D
373         0       1    male  22.00      0      0  135.6333        C  NaN
102         0       1    male  21.00      0      1   77.2875        S    D
748         0       1    male  19.00      1      0   53.1000        S    D
27          0       1    male  19.00      3      2  263.0000        S    C
505         0       1    male  18.00      1      0  108.9000        C    C
550         1       1    male  17.00      0      2  110.8833        C    C
802         1       1    male  11.00      1      2  120.0000        S    B
445         1       1    male   4.00      0      2   81.8583        S    A
305         1       1    male   0.92      1      2  151.5500        S    C
55          1       1    male    NaN      0      0   35.5000        S    C
64          0       1    male    NaN      0      0   27.7208        C  NaN
168         0       1    male    NaN      0      0   25.9250        S  NaN
185         0       1    male    NaN      0      0   50.0000        S    A
270         0       1    male    NaN      0      0   31.0000        S  NaN
284         0       1    male    NaN      0      0   26.0000        S    A
295         0       1    male    NaN      0      0   27.7208        C  NaN
298         1       1    male    NaN      0      0   30.5000        S    C
351         0       1    male    NaN      0      0   35.0000        S    C
475         0       1    male    NaN      0      0   52.0000        S    A
507         1       1    male    NaN      0      0   26.5500        S  NaN
527         0       1    male    NaN      0      0  221.7792        S    C
557         0       1    male    NaN      0      0  227.5250        C  NaN
602         0       1    male    NaN      0      0   42.4000        S  NaN
633         0       1    male    NaN      0      0    0.0000        S  NaN
711         0       1    male    NaN      0      0   26.5500        S    C
740         1       1    male    NaN      0      0   30.0000        S    D
766         0       1    male    NaN      0      0   39.6000        C  NaN
793         0       1    male    NaN      0      0   30.6958        C  NaN
815         0       1    male    NaN      0      0    0.0000        S    B
839         1       1    male    NaN      0      0   29.7000        C    C
772         0       2  female  57.00      0      0   10.5000        S    E
15          1       2  female  55.00      0      0   16.0000        S  NaN
774         1       2  female  54.00      1      3   23.0000        S  NaN
259         1       2  female  50.00      0      1   26.0000        S  NaN
458         1       2  female  50.00      0      0   10.5000        S  NaN
526         1       2  female  50.00      0      0   10.5000        S  NaN
754         1       2  female  48.00      1      2   65.0000        S  NaN
706         1       2  female  45.00      0      0   13.5000        S  NaN
440         1       2  female  45.00      1      1   26.2500        S  NaN
854         0       2  female  44.00      1      0   26.0000        S  NaN
432         1       2  female  42.00      1      0   26.0000        S  NaN
865         1       2  female  42.00      0      0   13.0000        S  NaN
272         1       2  female  41.00      0      1   19.5000        S  NaN
161         1       2  female  40.00      0      0   15.7500        S  NaN
346         1       2  female  40.00      0      0   13.0000        S  NaN
670         1       2  female  40.00      1      1   39.0000        S  NaN
357         0       2  female  38.00      0      0   13.0000        S  NaN
387         1       2  female  36.00      0      0   13.0000        S  NaN
327         1       2  female  36.00      0      0   13.0000        S    D
518         1       2  female  36.00      1      0   26.0000        S  NaN
211         1       2  female  35.00      0      0   21.0000        S  NaN
516         1       2  female  34.00      0      0   10.5000        S    F
576         1       2  female  34.00      0      0   13.0000        S  NaN
416         1       2  female  34.00      1      1   32.5000        S  NaN
98          1       2  female  34.00      0      1   23.0000        S  NaN
472         1       2  female  33.00      1      2   27.7500        S  NaN
506         1       2  female  33.00      0      2   26.0000        S  NaN
123         1       2  female  32.50      0      0   13.0000        S    E
190         1       2  female  32.00      0      0   13.0000        S  NaN
801         1       2  female  31.00      1      1   26.2500        S  NaN
726         1       2  female  30.00      3      0   21.0000        S  NaN
747         1       2  female  30.00      0      0   13.0000        S  NaN
322         1       2  female  30.00      0      0   12.3500        Q  NaN
53          1       2  female  29.00      1      0   26.0000        S  NaN
66          1       2  female  29.00      0      0   10.5000        S    F
133         1       2  female  29.00      1      0   26.0000        S  NaN
874         1       2  female  28.00      1      0   24.0000        C  NaN
426         1       2  female  28.00      1      0   26.0000        S  NaN
399         1       2  female  28.00      0      0   12.6500        S  NaN
635         1       2  female  28.00      0      0   13.0000        S  NaN
443         1       2  female  28.00      0      0   13.0000        S  NaN
866         1       2  female  27.00      1      0   13.8583        C  NaN
41          0       2  female  27.00      1      0   21.0000        S  NaN
717         1       2  female  27.00      0      0   10.5000        S    E
312         0       2  female  26.00      1      1   26.0000        S  NaN
880         1       2  female  25.00      0      1   26.0000        S  NaN
580         1       2  female  25.00      1      1   30.0000        S  NaN
600         1       2  female  24.00      2      1   27.0000        S  NaN
437         1       2  female  24.00      2      3   18.7500        S  NaN

In [18]:
titanic.sort_values(by = "age", ascending = False, inplace = True)

In [19]:
titanic

     survived  pclass     sex    age  sibsp  parch      fare embarked deck
630         1       1    male  80.00      0      0   30.0000        S    A
851         0       3    male  74.00      0      0    7.7750        S  NaN
96          0       1    male  71.00      0      0   34.6542        C    A
493         0       1    male  71.00      0      0   49.5042        C  NaN
116         0       3    male  70.50      0      0    7.7500        Q  NaN
672         0       2    male  70.00      0      0   10.5000        S  NaN
745         0       1    male  70.00      1      1   71.0000        S    B
33          0       2    male  66.00      0      0   10.5000        S  NaN
280         0       3    male  65.00      0      0    7.7500        Q  NaN
456         0       1    male  65.00      0      0   26.5500        S    E
54          0       1    male  65.00      0      1   61.9792        C    B
438         0       1    male  64.00      1      4  263.0000        S    C
545         0       1    male  64.00      0      0   26.0000        S  NaN
483         1       3  female  63.00      0      0    9.5875        S  NaN
275         1       1  female  63.00      1      0   77.9583        S    D
555         0       1    male  62.00      0      0   26.5500        S  NaN
829         1       1  female  62.00      0      0   80.0000      NaN    B
570         1       2    male  62.00      0      0   10.5000        S  NaN
252         0       1    male  62.00      0      0   26.5500        S    C
625         0       1    male  61.00      0      0   32.3208        S    D
170         0       1    male  61.00      0      0   33.5000        S    B
326         0       3    male  61.00      0      0    6.2375        S  NaN
587         1       1    male  60.00      1      1   79.2000        C    B
366         1       1  female  60.00      1      0   75.2500        C    D
684         0       2    male  60.00      1      1   39.0000        S  NaN
694         0       1    male  60.00      0      0   26.5500        S  NaN
232         0       2    male  59.00      0      0   13.5000        S  NaN
94          0       3    male  59.00      0      0    7.2500        S  NaN
195         1       1  female  58.00      0      0  146.5208        C    B
487         0       1    male  58.00      0      0   29.7000        C    B
659         0       1    male  58.00      0      2  113.2750        C    D
268         1       1  female  58.00      0      1  153.4625        S    C
11          1       1  female  58.00      0      0   26.5500        S    C
626         0       2    male  57.00      0      0   12.3500        Q  NaN
772         0       2  female  57.00      0      0   10.5000        S    E
174         0       1    male  56.00      0      0   30.6958        C    A
879         1       1  female  56.00      0      1   83.1583        C    C
467         0       1    male  56.00      0      0   26.5500        S  NaN
647         1       1    male  56.00      0      0   35.5000        C    A
152         0       3    male  55.50      0      0    8.0500        S  NaN
15          1       2  female  55.00      0      0   16.0000        S  NaN
492         0       1    male  55.00      0      0   30.5000        S    C
513         1       1  female  54.00      1      0   59.4000        C  NaN
124         0       1    male  54.00      0      1   77.2875        S    D
496         1       1  female  54.00      1      0   78.2667        C    D
774         1       2  female  54.00      1      3   23.0000        S  NaN
6           0       1    male  54.00      0      0   51.8625        S    E
582         0       2    male  54.00      0      0   26.0000        S  NaN
249         0       2    male  54.00      1      0   26.0000        S  NaN
317         0       2    male  54.00      0      0   14.0000        S  NaN
571         1       1  female  53.00      2      0   51.4792        S    C
262         0       1    male  52.00      1      1   79.6500        S    E
449         1       1    male  52.00      0      0   30.5000        S    C
820         1       1  female  52.00      1      1   93.5000        S    B
591         1       1  female  52.00      1      0   78.2667        C    D
695         0       2    male  52.00      0      0   13.5000        S  NaN
714         0       2    male  52.00      0      0   13.0000        S  NaN
150         0       2    male  51.00      0      0   12.5250        S  NaN
631         0       3    male  51.00      0      0    7.0542        S  NaN
406         0       3    male  51.00      0      0    7.7500        S  NaN
155         0       1    male  51.00      0      1   61.3792        C  NaN
765         1       1  female  51.00      1      0   77.9583        S    D
222         0       3    male  51.00      0      0    8.0500        S  NaN
857         1       1    male  51.00      0      0   26.5500        S    E
482         0       3    male  50.00      0      0    8.0500        S  NaN
723         0       2    male  50.00      0      0   13.0000        S  NaN
526         1       2  female  50.00      0      0   10.5000        S  NaN
458         1       2  female  50.00      0      0   10.5000        S  NaN
259         1       2  female  50.00      0      1   26.0000        S  NaN
544         0       1    male  50.00      1      0  106.4250        C    C
434         0       1    male  50.00      1      0   55.9000        S    E
177         0       1  female  50.00      0      0   28.7125        C    C
299         1       1  female  50.00      0      1  247.5208        C    B
660         1       1    male  50.00      2      0  133.6500        S  NaN
599         1       1    male  49.00      1      0   56.9292        C    A
796         1       1  female  49.00      0      0   25.9292        S    D
52          1       1  female  49.00      1      0   76.7292        C    D
453         1       1    male  49.00      1      0   89.1042        C    C
698         0       1    male  49.00      1      1  110.8833        C    C
597         0       3    male  49.00      0      0    0.0000        S  NaN
771         0       3    male  48.00      0      0    7.8542        S  NaN
645         1       1    male  48.00      1      0   76.7292        C    D
556         1       1  female  48.00      1      0   39.6000        C    A
862         1       1  female  48.00      0      0   25.9292        S    D
463         0       2    male  48.00      0      0   13.0000        S  NaN
754         1       2  female  48.00      1      2   65.0000        S  NaN
736         0       3  female  48.00      1      3   34.3750        S  NaN
460         1       1    male  48.00      0      0   26.5500        S    E
712         1       1    male  48.00      1      0   52.0000        S    C
132         0       3  female  47.00      1      0   14.5000        S  NaN
592         0       3    male  47.00      0      0    7.2500        S  NaN
515         0       1    male  47.00      0      0   34.0208        S    D
110         0       1    male  47.00      0      0   52.0000        S    C
871         1       1  female  47.00      1      1   52.5542        S    D
462         0       1    male  47.00      0      0   38.5000        S    E
586         0       2    male  47.00      0      0   15.0000        S  NaN
662         0       1    male  47.00      0      0   25.5875        S    E
873         0       3    male  47.00      0      0    9.0000        S  NaN
397         0       2    male  46.00      0      0   26.0000        S  NaN
789         0       1    male  46.00      0      0   79.2000        C    B
92          0       1    male  46.00      1      0   61.1750        S    E
331         0       1    male  45.50      0      0   28.5000        S    C
203         0       3    male  45.50      0      0    7.2250        C  NaN
339         0       1    male  45.00      0      0   35.5000        S  NaN
62          0       1    male  45.00      1      0   83.4750        S    C
440         1       2  female  45.00      1      1   26.2500        S  NaN
706         1       2  female  45.00      0      0   13.5000        S  NaN
129         0       3    male  45.00      0      0    6.9750        S  NaN
338         1       3    male  45.00      0      0    8.0500        S  NaN
187         1       1    male  45.00      0      0   26.5500        S  NaN
276         0       3  female  45.00      0      0    7.7500        S  NaN
167         0       3  female  45.00      1      4   27.9000        S  NaN
362         0       3  female  45.00      0      1   14.4542        C  NaN
856         1       1  female  45.00      1      1  164.8667        S  NaN
536         0       1    male  45.00      0      0   26.5500        S    B
160         0       3    male  44.00      0      1   16.1000        S  NaN
854         0       2  female  44.00      1      0   26.0000        S  NaN
236         0       2    male  44.00      1      0   26.0000        S  NaN
523         1       1  female  44.00      0      1   57.9792        C    B
414         1       3    male  44.00      0      0    7.9250        S  NaN
603         0       3    male  44.00      0      0    8.0500        S  NaN
194         1       1  female  44.00      0      0   27.7208        C    B
245         0       1    male  44.00      2      0   90.0000        Q    C
696         0       3    male  44.00      0      0    8.0500        S  NaN
779         1       1  female  43.00      0      1  211.3375        S    B
314         0       2    male  43.00      1      1   26.2500        S  NaN
818         0       3    male  43.00      0      0    6.4500        S  NaN
678         0       3  female  43.00      1      6   46.9000        S  NaN
668         0       3    male  43.00      0      0    8.0500        S  NaN
699         0       3    male  42.00      0      0    7.6500        S    F
349         0       3    male  42.00      0      0    8.6625        S  NaN
845         0       3    male  42.00      0      0    7.5500        S  NaN
621         1       1    male  42.00      1      0   52.5542        S    D
35          0       1    male  42.00      1      0   52.0000        S  NaN
707         1       1    male  42.00      0      0   26.2875        S    E
197         0       3    male  42.00      0      1    8.4042        S  NaN
865         1       2  female  42.00      0      0   13.0000        S  NaN
432         1       2  female  42.00      1      0   26.0000        S  NaN
288         1       2    male  42.00      0      0   13.0000        S  NaN
149         0       2    male  42.00      0      0   13.0000        S  NaN
217         0       2    male  42.00      1      0   27.0000        S  NaN
380         1       1  female  42.00      0      0  227.5250        C  NaN
272         1       2  female  41.00      0      1   19.5000        S  NaN
638         0       3  female  41.00      0      5   39.6875        S  NaN
761         0       3    male  41.00      0      0    7.1250        S  NaN
860         0       3    male  41.00      2      0   14.1083        S  NaN
337         1       1  female  41.00      0      0  134.5000        C    E
254         0       3  female  41.00      0      2   20.2125        S  NaN
525         0       3    male  40.50      0      0    7.7500        Q  NaN
153         0       3    male  40.50      0      2   14.5000        S  NaN
661         0       3    male  40.00      0      0    7.2250        C  NaN
263         0       1    male  40.00      0      0    0.0000        S    B
609         1       1  female  40.00      0      0  153.4625        S    C
319         1       1  female  40.00      1      1  134.5000        C    E
561         0       3    male  40.00      0      0    7.8958        S  NaN
346         1       2  female  40.00      0      0   13.0000        S  NaN
188         0       3    male  40.00      1      1   15.5000        Q  NaN
360         0       3    male  40.00      1      4   27.9000        S  NaN
209         1       1    male  40.00      0      0   31.0000        C    A
30          0       1    male  40.00      0      0   27.7208        C  NaN
670         1       2  female  40.00      1      1   39.0000        S  NaN
40          0       3  female  40.00      1      0    9.4750        S  NaN
161         1       2  female  40.00      0      0   15.7500        S  NaN
528         0       3    male  39.00      0      0    7.9250        S  NaN
400         1       3    male  39.00      0      0    7.9250        S  NaN
13          0       3    male  39.00      1      5   31.2750        S  NaN
811         0       3    male  39.00      0      0   24.1500        S  NaN
806         0       1    male  39.00      0      0    0.0000        S    A
610         0       3  female  39.00      1      5   31.2750        S  NaN
885         0       3  female  39.00      0      5   29.1250        Q  NaN
558         1       1  female  39.00      1      1   79.6500        S    E
581         1       1  female  39.00      1      1  110.8833        C    C
577         1       1  female  39.00      1      0   55.9000        S    E
835         1       1  female  39.00      1      1   83.1583        C    E
808         0       2    male  39.00      0      0   13.0000        S  NaN
795         0       2    male  39.00      0      0   13.0000        S  NaN
705         0       2    male  39.00      0      0   26.0000        S  NaN
108         0       3    male  38.00      0      0    7.8958        S  NaN
357         0       2  female  38.00      0      0   13.0000        S  NaN
471         0       3    male  38.00      0      0    8.6625        S  NaN
716         1       1  female  38.00      0      0  227.5250        C    C
465         0       3    male  38.00      0      0    7.0500        S  NaN
822         0       1    male  38.00      0      0    0.0000        S  NaN
25          1       3  female  38.00      1      5   31.3875        S  NaN
224         1       1    male  38.00      1      0   90.0000        S    C
332         0       1    male  38.00      0      1  153.4625        S    C
1           1       1  female  38.00      1      0   71.2833        C    C
61          1       1  female  38.00      0      0   80.0000      NaN    B
503         0       3  female  37.00      0      0    9.5875        S  NaN
104         0       3    male  37.00      2      0    7.9250        S  NaN
248         1       1    male  37.00      1      1   52.5542        S    D
137         0       1    male  37.00      1      0   53.1000        S    C
594         0       2    male  37.00      1      0   26.0000        S  NaN
273         0       1    male  37.00      0      1   29.7000        C    C
148         0       2    male  36.50      0      2   26.0000        S    F
679         1       1    male  36.00      0      1  512.3292        C    B
265         0       2    male  36.00      0      0   10.5000        S  NaN
292         0       2    male  36.00      0      0   12.8750        C    D
763         1       1  female  36.00      1      2  120.0000        S    B
559         1       3  female  36.00      1      0   17.4000        S  NaN
325         1       1  female  36.00      0      0  135.6333        C    C
741         0       1    male  36.00      1      0   78.8500        S    C
583         0       1    male  36.00      0      0   40.1250        C    A
572         1       1    male  36.00      0      0   26.3875        S    E
512         1       1    male  36.00      0      0   26.2875        S    E
390         1       1    male  36.00      1      2  120.0000        S    B
179         0       3    male  36.00      0      0    0.0000        S  NaN
189         0       3    male  36.00      0      0    7.8958        S  NaN
450         0       2    male  36.00      1      2   27.7500        S  NaN
327         1       2  female  36.00      0      0   13.0000        S    D
518         1       2  female  36.00      1      0   26.0000        S  NaN
540         1       1  female  36.00      0      2   71.0000        S    B
387         1       2  female  36.00      0      0   13.0000        S  NaN
344         0       2    male  36.00      0      0   13.0000        S  NaN
663         0       3    male  36.00      0      0    7.4958        S  NaN
595         0       3    male  36.00      1      1   24.1500        S  NaN
605         0       3    male  36.00      1      0   15.5500        S  NaN
258         1       1  female  35.00      0      0  512.3292        C  NaN
3           1       1  female  35.00      1      0   53.1000        S    C
230         1       1  female  35.00      1      0   83.4750        S    C
269         1       1  female  35.00      0      0  135.6333        S    C
383         1       1  female  35.00      1      0   52.0000        S  NaN
737         1       1    male  35.00      0      0  512.3292        C    B
701         1       1    male  35.00      0      0   26.2875        S    E
486         1       1  female  35.00      1      0   90.0000        S    C
211         1       2  female  35.00      0      0   21.0000        S  NaN
812         0       2    male  35.00      0      0   10.5000        S  NaN
279         1       3  female  35.00      1      1   20.2500        S  NaN
4           0       3    male  35.00      0      0    8.0500        S  NaN
847         0       3    male  35.00      0      0    7.8958        C  NaN
363         0       3    male  35.00      0      0    7.0500        S  NaN
604         1       1    male  35.00      0      0   26.5500        C  NaN
590         0       3    male  35.00      0      0    7.1250        S  NaN
20          0       2    male  35.00      0      0   26.0000        S  NaN
614         0       3    male  35.00      0      0    8.0500        S  NaN
843         0       3    male  34.50      0      0    6.4375        C  NaN
405         0       2    male  34.00      1      0   21.0000        S  NaN
447         1       1    male  34.00      0      0   26.5500        S  NaN
616         0       3    male  34.00      1      1   14.4000        S  NaN
722         0       2    male  34.00      0      0   13.0000        S  NaN
758         0       3    male  34.00      0      0    8.0500        S  NaN
476         0       2    male  34.00      1      0   21.0000        S  NaN
99          0       2    male  34.00      1      0   26.0000        S  NaN
202         0       3    male  34.00      0      0    6.4958        S  NaN
516         1       2  female  34.00      0      0   10.5000        S    F
461         0       3    male  34.00      0      0    8.0500        S  NaN
98          1       2  female  34.00      0      1   23.0000        S  NaN
21          1       2    male  34.00      0      0   13.0000        S    D
416         1       2  female  34.00      1      1   32.5000        S  NaN
800         0       2    male  34.00      0      0   13.0000        S  NaN
576         1       2  female  34.00      0      0   13.0000        S  NaN
506         1       2  female  33.00      0      2   26.0000        S  NaN
285         0       3    male  33.00      0      0    8.6625        C  NaN
103         0       3    male  33.00      0      0    8.6542        S  NaN
752         0       3    male  33.00      0      0    9.5000        S  NaN
719         0       3    male  33.00      0      0    7.7750        S  NaN
881         0       3    male  33.00      0      0    7.8958        S  NaN
872         0       1    male  33.00      0      0    5.0000        S    B
130         0       3    male  33.00      0      0    7.8958        C  NaN
239         0       2    male  33.00      0      0   12.2750        S  NaN
759         1       1  female  33.00      0      0   86.5000        S    B
412         1       1  female  33.00      1      0   90.0000        Q    C
809         1       1  female  33.00      1      0   53.1000        S    E
548         0       3    male  33.00      1      1   20.5250        S  NaN
472         1       2  female  33.00      1      2   27.7500        S  NaN

In [20]:
titanic.sort_values(by = ["pclass", "sex", "age"], ascending = [True, True, False], inplace= True)

In [21]:
pd.options.display.max_rows = 900

In [23]:
print(titanic)

     survived  pclass     sex    age  sibsp  parch      fare embarked deck
275         1       1  female  63.00      1      0   77.9583        S    D
829         1       1  female  62.00      0      0   80.0000      NaN    B
366         1       1  female  60.00      1      0   75.2500        C    D
195         1       1  female  58.00      0      0  146.5208        C    B
268         1       1  female  58.00      0      1  153.4625        S    C
11          1       1  female  58.00      0      0   26.5500        S    C
879         1       1  female  56.00      0      1   83.1583        C    C
513         1       1  female  54.00      1      0   59.4000        C  NaN
496         1       1  female  54.00      1      0   78.2667        C    D
571         1       1  female  53.00      2      0   51.4792        S    C
820         1       1  female  52.00      1      1   93.5000        S    B
591         1       1  female  52.00      1      0   78.2667        C    D
765         1       1  female  51.00      1      0   77.9583        S    D
177         0       1  female  50.00      0      0   28.7125        C    C
299         1       1  female  50.00      0      1  247.5208        C    B
796         1       1  female  49.00      0      0   25.9292        S    D
52          1       1  female  49.00      1      0   76.7292        C    D
556         1       1  female  48.00      1      0   39.6000        C    A
862         1       1  female  48.00      0      0   25.9292        S    D
871         1       1  female  47.00      1      1   52.5542        S    D
856         1       1  female  45.00      1      1  164.8667        S  NaN
523         1       1  female  44.00      0      1   57.9792        C    B
194         1       1  female  44.00      0      0   27.7208        C    B
779         1       1  female  43.00      0      1  211.3375        S    B
380         1       1  female  42.00      0      0  227.5250        C  NaN
337         1       1  female  41.00      0      0  134.5000        C    E
609         1       1  female  40.00      0      0  153.4625        S    C
319         1       1  female  40.00      1      1  134.5000        C    E
558         1       1  female  39.00      1      1   79.6500        S    E
581         1       1  female  39.00      1      1  110.8833        C    C
577         1       1  female  39.00      1      0   55.9000        S    E
835         1       1  female  39.00      1      1   83.1583        C    E
716         1       1  female  38.00      0      0  227.5250        C    C
1           1       1  female  38.00      1      0   71.2833        C    C
61          1       1  female  38.00      0      0   80.0000      NaN    B
763         1       1  female  36.00      1      2  120.0000        S    B
325         1       1  female  36.00      0      0  135.6333        C    C
540         1       1  female  36.00      0      2   71.0000        S    B
258         1       1  female  35.00      0      0  512.3292        C  NaN
3           1       1  female  35.00      1      0   53.1000        S    C
230         1       1  female  35.00      1      0   83.4750        S    C
269         1       1  female  35.00      0      0  135.6333        S    C
383         1       1  female  35.00      1      0   52.0000        S  NaN
486         1       1  female  35.00      1      0   90.0000        S    C
759         1       1  female  33.00      0      0   86.5000        S    B
412         1       1  female  33.00      1      0   90.0000        Q    C
809         1       1  female  33.00      1      0   53.1000        S    E
218         1       1  female  32.00      0      0   76.2917        C    D
318         1       1  female  31.00      0      2  164.8667        S    C
215         1       1  female  31.00      1      0  113.2750        C    D
257         1       1  female  30.00      0      0   86.5000        S    B
842         1       1  female  30.00      0      0   31.0000        C  NaN
520         1       1  female  30.00      0      0   93.5000        S    B
309         1       1  female  30.00      0      0   56.9292        C    E
537         1       1  female  30.00      0      0  106.4250        C  NaN
730         1       1  female  29.00      0      0  211.3375        S    B
290         1       1  female  26.00      0      0   78.8500        S  NaN
498         0       1  female  25.00      1      2  151.5500        S    C
641         1       1  female  24.00      0      0   69.3000        C    B
710         1       1  female  24.00      0      0   49.5042        C    C
341         1       1  female  24.00      3      2  263.0000        S    C
310         1       1  female  24.00      0      0   83.1583        C    C
369         1       1  female  24.00      0      0   69.3000        C    B
393         1       1  female  23.00      1      0  113.2750        C    D
88          1       1  female  23.00      3      2  263.0000        S    C
151         1       1  female  22.00      1      0   66.6000        S    C
539         1       1  female  22.00      0      2   49.5000        C    B
708         1       1  female  22.00      0      0  151.5500        S  NaN
356         1       1  female  22.00      0      1   55.0000        S    E
627         1       1  female  21.00      0      0   77.9583        S    D
742         1       1  female  21.00      2      2  262.3750        C    B
136         1       1  female  19.00      0      2   26.2833        S    D
887         1       1  female  19.00      0      0   30.0000        S    B
291         1       1  female  19.00      1      0   91.0792        C    B
700         1       1  female  18.00      1      0  227.5250        C    C
585         1       1  female  18.00      0      2   79.6500        S    E
311         1       1  female  18.00      2      2  262.3750        C    B
307         1       1  female  17.00      1      0  108.9000        C    C
781         1       1  female  17.00      1      0   57.0000        S    B
504         1       1  female  16.00      0      0   86.5000        S    B
329         1       1  female  16.00      0      1   57.9792        C    B
853         1       1  female  16.00      0      1   39.4000        S    D
689         1       1  female  15.00      0      1  211.3375        S    B
435         1       1  female  14.00      1      2  120.0000        S    B
297         0       1  female   2.00      1      2  151.5500        S    C
31          1       1  female    NaN      1      0  146.5208        C    B
166         1       1  female    NaN      0      1   55.0000        S    E
256         1       1  female    NaN      0      0   79.2000        C  NaN
306         1       1  female    NaN      0      0  110.8833        C  NaN
334         1       1  female    NaN      1      0  133.6500        S  NaN
375         1       1  female    NaN      1      0   82.1708        C  NaN
457         1       1  female    NaN      1      0   51.8625        S    D
669         1       1  female    NaN      1      0   52.0000        S    C
849         1       1  female    NaN      1      0   89.1042        C    C
630         1       1    male  80.00      0      0   30.0000        S    A
96          0       1    male  71.00      0      0   34.6542        C    A
493         0       1    male  71.00      0      0   49.5042        C  NaN
745         0       1    male  70.00      1      1   71.0000        S    B
456         0       1    male  65.00      0      0   26.5500        S    E
54          0       1    male  65.00      0      1   61.9792        C    B
438         0       1    male  64.00      1      4  263.0000        S    C
545         0       1    male  64.00      0      0   26.0000        S  NaN
555         0       1    male  62.00      0      0   26.5500        S  NaN
252         0       1    male  62.00      0      0   26.5500        S    C
625         0       1    male  61.00      0      0   32.3208        S    D
170         0       1    male  61.00      0      0   33.5000        S    B
587         1       1    male  60.00      1      1   79.2000        C    B
694         0       1    male  60.00      0      0   26.5500        S  NaN
487         0       1    male  58.00      0      0   29.7000        C    B
659         0       1    male  58.00      0      2  113.2750        C    D
174         0       1    male  56.00      0      0   30.6958        C    A
467         0       1    male  56.00      0      0   26.5500        S  NaN
647         1       1    male  56.00      0      0   35.5000        C    A
492         0       1    male  55.00      0      0   30.5000        S    C
124         0       1    male  54.00      0      1   77.2875        S    D
6           0       1    male  54.00      0      0   51.8625        S    E
262         0       1    male  52.00      1      1   79.6500        S    E
449         1       1    male  52.00      0      0   30.5000        S    C
155         0       1    male  51.00      0      1   61.3792        C  NaN
857         1       1    male  51.00      0      0   26.5500        S    E
544         0       1    male  50.00      1      0  106.4250        C    C
434         0       1    male  50.00      1      0   55.9000        S    E
660         1       1    male  50.00      2      0  133.6500        S  NaN
599         1       1    male  49.00      1      0   56.9292        C    A
453         1       1    male  49.00      1      0   89.1042        C    C
698         0       1    male  49.00      1      1  110.8833        C    C
645         1       1    male  48.00      1      0   76.7292        C    D
460         1       1    male  48.00      0      0   26.5500        S    E
712         1       1    male  48.00      1      0   52.0000        S    C
515         0       1    male  47.00      0      0   34.0208        S    D
110         0       1    male  47.00      0      0   52.0000        S    C
462         0       1    male  47.00      0      0   38.5000        S    E
662         0       1    male  47.00      0      0   25.5875        S    E
789         0       1    male  46.00      0      0   79.2000        C    B
92          0       1    male  46.00      1      0   61.1750        S    E
331         0       1    male  45.50      0      0   28.5000        S    C
339         0       1    male  45.00      0      0   35.5000        S  NaN
62          0       1    male  45.00      1      0   83.4750        S    C
187         1       1    male  45.00      0      0   26.5500        S  NaN
536         0       1    male  45.00      0      0   26.5500        S    B
245         0       1    male  44.00      2      0   90.0000        Q    C
621         1       1    male  42.00      1      0   52.5542        S    D
35          0       1    male  42.00      1      0   52.0000        S  NaN
707         1       1    male  42.00      0      0   26.2875        S    E
263         0       1    male  40.00      0      0    0.0000        S    B
209         1       1    male  40.00      0      0   31.0000        C    A
30          0       1    male  40.00      0      0   27.7208        C  NaN
806         0       1    male  39.00      0      0    0.0000        S    A
822         0       1    male  38.00      0      0    0.0000        S  NaN
224         1       1    male  38.00      1      0   90.0000        S    C
332         0       1    male  38.00      0      1  153.4625        S    C
248         1       1    male  37.00      1      1   52.5542        S    D
137         0       1    male  37.00      1      0   53.1000        S    C
273         0       1    male  37.00      0      1   29.7000        C    C
679         1       1    male  36.00      0      1  512.3292        C    B
741         0       1    male  36.00      1      0   78.8500        S    C
583         0       1    male  36.00      0      0   40.1250        C    A
572         1       1    male  36.00      0      0   26.3875        S    E
512         1       1    male  36.00      0      0   26.2875        S    E
390         1       1    male  36.00      1      2  120.0000        S    B
737         1       1    male  35.00      0      0  512.3292        C    B
701         1       1    male  35.00      0      0   26.2875        S    E
604         1       1    male  35.00      0      0   26.5500        C  NaN
447         1       1    male  34.00      0      0   26.5500        S  NaN
872         0       1    male  33.00      0      0    5.0000        S    B
632         1       1    male  32.00      0      0   30.5000        C    B
690         1       1    male  31.00      1      0   57.0000        S    B
671         0       1    male  31.00      1      0   52.0000        S    B
867         0       1    male  31.00      0      0   50.4958        S    A
452         0       1    male  30.00      0      0   27.7500        C    C
336         0       1    male  29.00      1      0   66.6000        S    C
782         0       1    male  29.00      0      0   30.0000        S    D
83          0       1    male  28.00      0      0   47.1000        S  NaN
430         1       1    male  28.00      0      0   26.5500        S    C
34          0       1    male  28.00      1      0   82.1708        C  NaN
23          1       1    male  28.00      0      0   35.5000        S    A
681         1       1    male  27.00      0      0   76.7292        C    D
607         1       1    male  27.00      0      0   30.5000        S  NaN
377         0       1    male  27.00      0      2  211.5000        C    C
724         1       1    male  27.00      1      0   53.1000        S    E
889         1       1    male  26.00      0      0   30.0000        C    C
370         1       1    male  25.00      1      0   55.4417        C    E
484         1       1    male  25.00      1      0   91.0792        C    B
118         0       1    male  24.00      0      1  247.5208        C    B
139         0       1    male  24.00      0      0   79.2000        C    B
97          1       1    male  23.00      0      1   63.3583        C    D
373         0       1    male  22.00      0      0  135.6333        C  NaN
102         0       1    male  21.00      0      1   77.2875        S    D
27          0       1    male  19.00      3      2  263.0000        S    C
748         0       1    male  19.00      1      0   53.1000        S    D
505         0       1    male  18.00      1      0  108.9000        C    C
550         1       1    male  17.00      0      2  110.8833        C    C
802         1       1    male  11.00      1      2  120.0000        S    B
445         1       1    male   4.00      0      2   81.8583        S    A
305         1       1    male   0.92      1      2  151.5500        S    C
55          1       1    male    NaN      0      0   35.5000        S    C
64          0       1    male    NaN      0      0   27.7208        C  NaN
168         0       1    male    NaN      0      0   25.9250        S  NaN
185         0       1    male    NaN      0      0   50.0000        S    A
270         0       1    male    NaN      0      0   31.0000        S  NaN
284         0       1    male    NaN      0      0   26.0000        S    A
295         0       1    male    NaN      0      0   27.7208        C  NaN
298         1       1    male    NaN      0      0   30.5000        S    C
351         0       1    male    NaN      0      0   35.0000        S    C
475         0       1    male    NaN      0      0   52.0000        S    A
507         1       1    male    NaN      0      0   26.5500        S  NaN
527         0       1    male    NaN      0      0  221.7792        S    C
557         0       1    male    NaN      0      0  227.5250        C  NaN
602         0       1    male    NaN      0      0   42.4000        S  NaN
633         0       1    male    NaN      0      0    0.0000        S  NaN
711         0       1    male    NaN      0      0   26.5500        S    C
740         1       1    male    NaN      0      0   30.0000        S    D
766         0       1    male    NaN      0      0   39.6000        C  NaN
793         0       1    male    NaN      0      0   30.6958        C  NaN
815         0       1    male    NaN      0      0    0.0000        S    B
839         1       1    male    NaN      0      0   29.7000        C    C
772         0       2  female  57.00      0      0   10.5000        S    E
15          1       2  female  55.00      0      0   16.0000        S  NaN
774         1       2  female  54.00      1      3   23.0000        S  NaN
526         1       2  female  50.00      0      0   10.5000        S  NaN
458         1       2  female  50.00      0      0   10.5000        S  NaN
259         1       2  female  50.00      0      1   26.0000        S  NaN
754         1       2  female  48.00      1      2   65.0000        S  NaN
440         1       2  female  45.00      1      1   26.2500        S  NaN
706         1       2  female  45.00      0      0   13.5000        S  NaN
854         0       2  female  44.00      1      0   26.0000        S  NaN
865         1       2  female  42.00      0      0   13.0000        S  NaN
432         1       2  female  42.00      1      0   26.0000        S  NaN
272         1       2  female  41.00      0      1   19.5000        S  NaN
346         1       2  female  40.00      0      0   13.0000        S  NaN
670         1       2  female  40.00      1      1   39.0000        S  NaN
161         1       2  female  40.00      0      0   15.7500        S  NaN
357         0       2  female  38.00      0      0   13.0000        S  NaN
327         1       2  female  36.00      0      0   13.0000        S    D
518         1       2  female  36.00      1      0   26.0000        S  NaN
387         1       2  female  36.00      0      0   13.0000        S  NaN
211         1       2  female  35.00      0      0   21.0000        S  NaN
516         1       2  female  34.00      0      0   10.5000        S    F
98          1       2  female  34.00      0      1   23.0000        S  NaN
416         1       2  female  34.00      1      1   32.5000        S  NaN
576         1       2  female  34.00      0      0   13.0000        S  NaN
506         1       2  female  33.00      0      2   26.0000        S  NaN
472         1       2  female  33.00      1      2   27.7500        S  NaN
123         1       2  female  32.50      0      0   13.0000        S    E
190         1       2  female  32.00      0      0   13.0000        S  NaN
801         1       2  female  31.00      1      1   26.2500        S  NaN
322         1       2  female  30.00      0      0   12.3500        Q  NaN
747         1       2  female  30.00      0      0   13.0000        S  NaN
726         1       2  female  30.00      3      0   21.0000        S  NaN
133         1       2  female  29.00      1      0   26.0000        S  NaN
53          1       2  female  29.00      1      0   26.0000        S  NaN
66          1       2  female  29.00      0      0   10.5000        S    F
399         1       2  female  28.00      0      0   12.6500        S  NaN
443         1       2  female  28.00      0      0   13.0000        S  NaN
874         1       2  female  28.00      1      0   24.0000        C  NaN
635         1       2  female  28.00      0      0   13.0000        S  NaN
426         1       2  female  28.00      1      0   26.0000        S  NaN
717         1       2  female  27.00      0      0   10.5000        S    E
41          0       2  female  27.00      1      0   21.0000        S  NaN
866         1       2  female  27.00      1      0   13.8583        C  NaN
312         0       2  female  26.00      1      1   26.0000        S  NaN
880         1       2  female  25.00      0      1   26.0000        S  NaN
580         1       2  female  25.00      1      1   30.0000        S  NaN
615         1       2  female  24.00      1      2   65.0000        S  NaN
316         1       2  female  24.00      1      0   26.0000        S  NaN

In [24]:
titanic.sort_index(ascending = True, inplace = True)

In [25]:
titanic

     survived  pclass     sex    age  sibsp  parch      fare embarked deck
0           0       3    male  22.00      1      0    7.2500        S  NaN
1           1       1  female  38.00      1      0   71.2833        C    C
2           1       3  female  26.00      0      0    7.9250        S  NaN
3           1       1  female  35.00      1      0   53.1000        S    C
4           0       3    male  35.00      0      0    8.0500        S  NaN
5           0       3    male    NaN      0      0    8.4583        Q  NaN
6           0       1    male  54.00      0      0   51.8625        S    E
7           0       3    male   2.00      3      1   21.0750        S  NaN
8           1       3  female  27.00      0      2   11.1333        S  NaN
9           1       2  female  14.00      1      0   30.0708        C  NaN
10          1       3  female   4.00      1      1   16.7000        S    G
11          1       1  female  58.00      0      0   26.5500        S    C
12          0       3    male  20.00      0      0    8.0500        S  NaN
13          0       3    male  39.00      1      5   31.2750        S  NaN
14          0       3  female  14.00      0      0    7.8542        S  NaN
15          1       2  female  55.00      0      0   16.0000        S  NaN
16          0       3    male   2.00      4      1   29.1250        Q  NaN
17          1       2    male    NaN      0      0   13.0000        S  NaN
18          0       3  female  31.00      1      0   18.0000        S  NaN
19          1       3  female    NaN      0      0    7.2250        C  NaN
20          0       2    male  35.00      0      0   26.0000        S  NaN
21          1       2    male  34.00      0      0   13.0000        S    D
22          1       3  female  15.00      0      0    8.0292        Q  NaN
23          1       1    male  28.00      0      0   35.5000        S    A
24          0       3  female   8.00      3      1   21.0750        S  NaN
25          1       3  female  38.00      1      5   31.3875        S  NaN
26          0       3    male    NaN      0      0    7.2250        C  NaN
27          0       1    male  19.00      3      2  263.0000        S    C
28          1       3  female    NaN      0      0    7.8792        Q  NaN
29          0       3    male    NaN      0      0    7.8958        S  NaN
30          0       1    male  40.00      0      0   27.7208        C  NaN
31          1       1  female    NaN      1      0  146.5208        C    B
32          1       3  female    NaN      0      0    7.7500        Q  NaN
33          0       2    male  66.00      0      0   10.5000        S  NaN
34          0       1    male  28.00      1      0   82.1708        C  NaN
35          0       1    male  42.00      1      0   52.0000        S  NaN
36          1       3    male    NaN      0      0    7.2292        C  NaN
37          0       3    male  21.00      0      0    8.0500        S  NaN
38          0       3  female  18.00      2      0   18.0000        S  NaN
39          1       3  female  14.00      1      0   11.2417        C  NaN
40          0       3  female  40.00      1      0    9.4750        S  NaN
41          0       2  female  27.00      1      0   21.0000        S  NaN
42          0       3    male    NaN      0      0    7.8958        C  NaN
43          1       2  female   3.00      1      2   41.5792        C  NaN
44          1       3  female  19.00      0      0    7.8792        Q  NaN
45          0       3    male    NaN      0      0    8.0500        S  NaN
46          0       3    male    NaN      1      0   15.5000        Q  NaN
47          1       3  female    NaN      0      0    7.7500        Q  NaN
48          0       3    male    NaN      2      0   21.6792        C  NaN
49          0       3  female  18.00      1      0   17.8000        S  NaN
50          0       3    male   7.00      4      1   39.6875        S  NaN
51          0       3    male  21.00      0      0    7.8000        S  NaN
52          1       1  female  49.00      1      0   76.7292        C    D
53          1       2  female  29.00      1      0   26.0000        S  NaN
54          0       1    male  65.00      0      1   61.9792        C    B
55          1       1    male    NaN      0      0   35.5000        S    C
56          1       2  female  21.00      0      0   10.5000        S  NaN
57          0       3    male  28.50      0      0    7.2292        C  NaN
58          1       2  female   5.00      1      2   27.7500        S  NaN
59          0       3    male  11.00      5      2   46.9000        S  NaN
60          0       3    male  22.00      0      0    7.2292        C  NaN
61          1       1  female  38.00      0      0   80.0000      NaN    B
62          0       1    male  45.00      1      0   83.4750        S    C
63          0       3    male   4.00      3      2   27.9000        S  NaN
64          0       1    male    NaN      0      0   27.7208        C  NaN
65          1       3    male    NaN      1      1   15.2458        C  NaN
66          1       2  female  29.00      0      0   10.5000        S    F
67          0       3    male  19.00      0      0    8.1583        S  NaN
68          1       3  female  17.00      4      2    7.9250        S  NaN
69          0       3    male  26.00      2      0    8.6625        S  NaN
70          0       2    male  32.00      0      0   10.5000        S  NaN
71          0       3  female  16.00      5      2   46.9000        S  NaN
72          0       2    male  21.00      0      0   73.5000        S  NaN
73          0       3    male  26.00      1      0   14.4542        C  NaN
74          1       3    male  32.00      0      0   56.4958        S  NaN
75          0       3    male  25.00      0      0    7.6500        S    F
76          0       3    male    NaN      0      0    7.8958        S  NaN
77          0       3    male    NaN      0      0    8.0500        S  NaN
78          1       2    male   0.83      0      2   29.0000        S  NaN
79          1       3  female  30.00      0      0   12.4750        S  NaN
80          0       3    male  22.00      0      0    9.0000        S  NaN
81          1       3    male  29.00      0      0    9.5000        S  NaN
82          1       3  female    NaN      0      0    7.7875        Q  NaN
83          0       1    male  28.00      0      0   47.1000        S  NaN
84          1       2  female  17.00      0      0   10.5000        S  NaN
85          1       3  female  33.00      3      0   15.8500        S  NaN
86          0       3    male  16.00      1      3   34.3750        S  NaN
87          0       3    male    NaN      0      0    8.0500        S  NaN
88          1       1  female  23.00      3      2  263.0000        S    C
89          0       3    male  24.00      0      0    8.0500        S  NaN
90          0       3    male  29.00      0      0    8.0500        S  NaN
91          0       3    male  20.00      0      0    7.8542        S  NaN
92          0       1    male  46.00      1      0   61.1750        S    E
93          0       3    male  26.00      1      2   20.5750        S  NaN
94          0       3    male  59.00      0      0    7.2500        S  NaN
95          0       3    male    NaN      0      0    8.0500        S  NaN
96          0       1    male  71.00      0      0   34.6542        C    A
97          1       1    male  23.00      0      1   63.3583        C    D
98          1       2  female  34.00      0      1   23.0000        S  NaN
99          0       2    male  34.00      1      0   26.0000        S  NaN
100         0       3  female  28.00      0      0    7.8958        S  NaN
101         0       3    male    NaN      0      0    7.8958        S  NaN
102         0       1    male  21.00      0      1   77.2875        S    D
103         0       3    male  33.00      0      0    8.6542        S  NaN
104         0       3    male  37.00      2      0    7.9250        S  NaN
105         0       3    male  28.00      0      0    7.8958        S  NaN
106         1       3  female  21.00      0      0    7.6500        S  NaN
107         1       3    male    NaN      0      0    7.7750        S  NaN
108         0       3    male  38.00      0      0    7.8958        S  NaN
109         1       3  female    NaN      1      0   24.1500        Q  NaN
110         0       1    male  47.00      0      0   52.0000        S    C
111         0       3  female  14.50      1      0   14.4542        C  NaN
112         0       3    male  22.00      0      0    8.0500        S  NaN
113         0       3  female  20.00      1      0    9.8250        S  NaN
114         0       3  female  17.00      0      0   14.4583        C  NaN
115         0       3    male  21.00      0      0    7.9250        S  NaN
116         0       3    male  70.50      0      0    7.7500        Q  NaN
117         0       2    male  29.00      1      0   21.0000        S  NaN
118         0       1    male  24.00      0      1  247.5208        C    B
119         0       3  female   2.00      4      2   31.2750        S  NaN
120         0       2    male  21.00      2      0   73.5000        S  NaN
121         0       3    male    NaN      0      0    8.0500        S  NaN
122         0       2    male  32.50      1      0   30.0708        C  NaN
123         1       2  female  32.50      0      0   13.0000        S    E
124         0       1    male  54.00      0      1   77.2875        S    D
125         1       3    male  12.00      1      0   11.2417        C  NaN
126         0       3    male    NaN      0      0    7.7500        Q  NaN
127         1       3    male  24.00      0      0    7.1417        S  NaN
128         1       3  female    NaN      1      1   22.3583        C    F
129         0       3    male  45.00      0      0    6.9750        S  NaN
130         0       3    male  33.00      0      0    7.8958        C  NaN
131         0       3    male  20.00      0      0    7.0500        S  NaN
132         0       3  female  47.00      1      0   14.5000        S  NaN
133         1       2  female  29.00      1      0   26.0000        S  NaN
134         0       2    male  25.00      0      0   13.0000        S  NaN
135         0       2    male  23.00      0      0   15.0458        C  NaN
136         1       1  female  19.00      0      2   26.2833        S    D
137         0       1    male  37.00      1      0   53.1000        S    C
138         0       3    male  16.00      0      0    9.2167        S  NaN
139         0       1    male  24.00      0      0   79.2000        C    B
140         0       3  female    NaN      0      2   15.2458        C  NaN
141         1       3  female  22.00      0      0    7.7500        S  NaN
142         1       3  female  24.00      1      0   15.8500        S  NaN
143         0       3    male  19.00      0      0    6.7500        Q  NaN
144         0       2    male  18.00      0      0   11.5000        S  NaN
145         0       2    male  19.00      1      1   36.7500        S  NaN
146         1       3    male  27.00      0      0    7.7958        S  NaN
147         0       3  female   9.00      2      2   34.3750        S  NaN
148         0       2    male  36.50      0      2   26.0000        S    F
149         0       2    male  42.00      0      0   13.0000        S  NaN
150         0       2    male  51.00      0      0   12.5250        S  NaN
151         1       1  female  22.00      1      0   66.6000        S    C
152         0       3    male  55.50      0      0    8.0500        S  NaN
153         0       3    male  40.50      0      2   14.5000        S  NaN
154         0       3    male    NaN      0      0    7.3125        S  NaN
155         0       1    male  51.00      0      1   61.3792        C  NaN
156         1       3  female  16.00      0      0    7.7333        Q  NaN
157         0       3    male  30.00      0      0    8.0500        S  NaN
158         0       3    male    NaN      0      0    8.6625        S  NaN
159         0       3    male    NaN      8      2   69.5500        S  NaN
160         0       3    male  44.00      0      1   16.1000        S  NaN
161         1       2  female  40.00      0      0   15.7500        S  NaN
162         0       3    male  26.00      0      0    7.7750        S  NaN
163         0       3    male  17.00      0      0    8.6625        S  NaN
164         0       3    male   1.00      4      1   39.6875        S  NaN
165         1       3    male   9.00      0      2   20.5250        S  NaN
166         1       1  female    NaN      0      1   55.0000        S    E
167         0       3  female  45.00      1      4   27.9000        S  NaN
168         0       1    male    NaN      0      0   25.9250        S  NaN
169         0       3    male  28.00      0      0   56.4958        S  NaN
170         0       1    male  61.00      0      0   33.5000        S    B
171         0       3    male   4.00      4      1   29.1250        Q  NaN
172         1       3  female   1.00      1      1   11.1333        S  NaN
173         0       3    male  21.00      0      0    7.9250        S  NaN
174         0       1    male  56.00      0      0   30.6958        C    A
175         0       3    male  18.00      1      1    7.8542        S  NaN
176         0       3    male    NaN      3      1   25.4667        S  NaN
177         0       1  female  50.00      0      0   28.7125        C    C
178         0       2    male  30.00      0      0   13.0000        S  NaN
179         0       3    male  36.00      0      0    0.0000        S  NaN
180         0       3  female    NaN      8      2   69.5500        S  NaN
181         0       2    male    NaN      0      0   15.0500        C  NaN
182         0       3    male   9.00      4      2   31.3875        S  NaN
183         1       2    male   1.00      2      1   39.0000        S    F
184         1       3  female   4.00      0      2   22.0250        S  NaN
185         0       1    male    NaN      0      0   50.0000        S    A
186         1       3  female    NaN      1      0   15.5000        Q  NaN
187         1       1    male  45.00      0      0   26.5500        S  NaN
188         0       3    male  40.00      1      1   15.5000        Q  NaN
189         0       3    male  36.00      0      0    7.8958        S  NaN
190         1       2  female  32.00      0      0   13.0000        S  NaN
191         0       2    male  19.00      0      0   13.0000        S  NaN
192         1       3  female  19.00      1      0    7.8542        S  NaN
193         1       2    male   3.00      1      1   26.0000        S    F
194         1       1  female  44.00      0      0   27.7208        C    B
195         1       1  female  58.00      0      0  146.5208        C    B
196         0       3    male    NaN      0      0    7.7500        Q  NaN
197         0       3    male  42.00      0      1    8.4042        S  NaN
198         1       3  female    NaN      0      0    7.7500        Q  NaN
199         0       2  female  24.00      0      0   13.0000        S  NaN
200         0       3    male  28.00      0      0    9.5000        S  NaN
201         0       3    male    NaN      8      2   69.5500        S  NaN
202         0       3    male  34.00      0      0    6.4958        S  NaN
203         0       3    male  45.50      0      0    7.2250        C  NaN
204         1       3    male  18.00      0      0    8.0500        S  NaN
205         0       3  female   2.00      0      1   10.4625        S    G
206         0       3    male  32.00      1      0   15.8500        S  NaN
207         1       3    male  26.00      0      0   18.7875        C  NaN
208         1       3  female  16.00      0      0    7.7500        Q  NaN
209         1       1    male  40.00      0      0   31.0000        C    A
210         0       3    male  24.00      0      0    7.0500        S  NaN
211         1       2  female  35.00      0      0   21.0000        S  NaN
212         0       3    male  22.00      0      0    7.2500        S  NaN
213         0       2    male  30.00      0      0   13.0000        S  NaN
214         0       3    male    NaN      1      0    7.7500        Q  NaN
215         1       1  female  31.00      1      0  113.2750        C    D
216         1       3  female  27.00      0      0    7.9250        S  NaN
217         0       2    male  42.00      1      0   27.0000        S  NaN
218         1       1  female  32.00      0      0   76.2917        C    D
219         0       2    male  30.00      0      0   10.5000        S  NaN
220         1       3    male  16.00      0      0    8.0500        S  NaN
221         0       2    male  27.00      0      0   13.0000        S  NaN
222         0       3    male  51.00      0      0    8.0500        S  NaN
223         0       3    male    NaN      0      0    7.8958        S  NaN
224         1       1    male  38.00      1      0   90.0000        S    C
225         0       3    male  22.00      0      0    9.3500        S  NaN
226         1       2    male  19.00      0      0   10.5000        S  NaN
227         0       3    male  20.50      0      0    7.2500        S  NaN
228         0       2    male  18.00      0      0   13.0000        S  NaN
229         0       3  female    NaN      3      1   25.4667        S  NaN
230         1       1  female  35.00      1      0   83.4750        S    C
231         0       3    male  29.00      0      0    7.7750        S  NaN
232         0       2    male  59.00      0      0   13.5000        S  NaN
233         1       3  female   5.00      4      2   31.3875        S  NaN
234         0       2    male  24.00      0      0   10.5000        S  NaN
235         0       3  female    NaN      0      0    7.5500        S  NaN
236         0       2    male  44.00      1      0   26.0000        S  NaN
237         1       2  female   8.00      0      2   26.2500        S  NaN
238         0       2    male  19.00      0      0   10.5000        S  NaN
239         0       2    male  33.00      0      0   12.2750        S  NaN
240         0       3  female    NaN      1      0   14.4542        C  NaN
241         1       3  female    NaN      1      0   15.5000        Q  NaN
242         0       2    male  29.00      0      0   10.5000        S  NaN
243         0       3    male  22.00      0      0    7.1250        S  NaN
244         0       3    male  30.00      0      0    7.2250        C  NaN
245         0       1    male  44.00      2      0   90.0000        Q    C
246         0       3  female  25.00      0      0    7.7750        S  NaN
247         1       2  female  24.00      0      2   14.5000        S  NaN
248         1       1    male  37.00      1      1   52.5542        S    D
249         0       2    male  54.00      1      0   26.0000        S  NaN
250         0       3    male    NaN      0      0    7.2500        S  NaN
251         0       3  female  29.00      1      1   10.4625        S    G
252         0       1    male  62.00      0      0   26.5500        S    C
253         0       3    male  30.00      1      0   16.1000        S  NaN
254         0       3  female  41.00      0      2   20.2125        S  NaN
255         1       3  female  29.00      0      2   15.2458        C  NaN
256         1       1  female    NaN      0      0   79.2000        C  NaN
257         1       1  female  30.00      0      0   86.5000        S    B
258         1       1  female  35.00      0      0  512.3292        C  NaN
259         1       2  female  50.00      0      1   26.0000        S  NaN
260         0       3    male    NaN      0      0    7.7500        Q  NaN
261         1       3    male   3.00      4      2   31.3875        S  NaN
262         0       1    male  52.00      1      1   79.6500        S    E
263         0       1    male  40.00      0      0    0.0000        S    B
264         0       3  female    NaN      0      0    7.7500        Q  NaN

In [26]:
titanic.sort_values(by = "age").reset_index(drop = True)

     survived  pclass     sex    age  sibsp  parch      fare embarked deck
0           1       3    male   0.42      0      1    8.5167        C  NaN
1           1       2    male   0.67      1      1   14.5000        S  NaN
2           1       3  female   0.75      2      1   19.2583        C  NaN
3           1       3  female   0.75      2      1   19.2583        C  NaN
4           1       2    male   0.83      0      2   29.0000        S  NaN
5           1       2    male   0.83      1      1   18.7500        S  NaN
6           1       1    male   0.92      1      2  151.5500        S    C
7           1       2    male   1.00      0      2   37.0042        C  NaN
8           1       3  female   1.00      0      2   15.7417        C  NaN
9           0       3    male   1.00      4      1   39.6875        S  NaN
10          1       2    male   1.00      2      1   39.0000        S    F
11          0       3    male   1.00      5      2   46.9000        S  NaN
12          1       3  female   1.00      1      1   11.1333        S  NaN
13          1       3    male   1.00      1      2   20.5750        S  NaN
14          0       3  female   2.00      3      2   27.9000        S  NaN
15          0       3    male   2.00      3      1   21.0750        S  NaN
16          1       2  female   2.00      1      1   26.0000        S  NaN
17          0       1  female   2.00      1      2  151.5500        S    C
18          0       3    male   2.00      4      1   39.6875        S  NaN
19          0       3  female   2.00      0      1   10.4625        S    G
20          0       3  female   2.00      4      2   31.2750        S  NaN
21          1       2    male   2.00      1      1   26.0000        S    F
22          1       3  female   2.00      0      1   12.2875        S  NaN
23          0       3    male   2.00      4      1   29.1250        Q  NaN
24          1       3    male   3.00      1      1   15.9000        S  NaN
25          1       2    male   3.00      1      1   18.7500        S  NaN
26          0       3  female   3.00      3      1   21.0750        S  NaN
27          1       3    male   3.00      4      2   31.3875        S  NaN
28          1       2  female   3.00      1      2   41.5792        C  NaN
29          1       2    male   3.00      1      1   26.0000        S    F
30          0       3    male   4.00      4      2   31.2750        S  NaN
31          0       3    male   4.00      4      1   29.1250        Q  NaN
32          0       3    male   4.00      3      2   27.9000        S  NaN
33          1       2  female   4.00      1      1   23.0000        S  NaN
34          1       3  female   4.00      0      1   13.4167        C  NaN
35          1       3    male   4.00      1      1   11.1333        S  NaN
36          1       2  female   4.00      2      1   39.0000        S    F
37          1       3  female   4.00      1      1   16.7000        S    G
38          1       1    male   4.00      0      2   81.8583        S    A
39          1       3  female   4.00      0      2   22.0250        S  NaN
40          1       3  female   5.00      4      2   31.3875        S  NaN
41          1       3  female   5.00      0      0   12.4750        S  NaN
42          1       3  female   5.00      2      1   19.2583        C  NaN
43          1       2  female   5.00      1      2   27.7500        S  NaN
44          1       2  female   6.00      0      1   33.0000        S  NaN
45          0       3  female   6.00      4      2   31.2750        S  NaN
46          1       3    male   6.00      0      1   12.4750        S    E
47          0       3    male   7.00      4      1   29.1250        Q  NaN
48          1       2  female   7.00      0      2   26.2500        S  NaN
49          0       3    male   7.00      4      1   39.6875        S  NaN
50          0       3  female   8.00      3      1   21.0750        S  NaN
51          1       2    male   8.00      1      1   36.7500        S  NaN
52          1       2  female   8.00      0      2   26.2500        S  NaN
53          0       3    male   8.00      4      1   29.1250        Q  NaN
54          0       3  female   9.00      2      2   34.3750        S  NaN
55          0       3  female   9.00      4      2   31.2750        S  NaN
56          0       3  female   9.00      1      1   15.2458        C  NaN
57          0       3    male   9.00      4      2   31.3875        S  NaN
58          0       3    male   9.00      5      2   46.9000        S  NaN
59          0       3  female   9.00      3      2   27.9000        S  NaN
60          1       3    male   9.00      1      1   15.9000        S  NaN
61          1       3    male   9.00      0      2   20.5250        S  NaN
62          0       3  female  10.00      0      2   24.1500        S  NaN
63          0       3    male  10.00      3      2   27.9000        S  NaN
64          0       3  female  11.00      4      2   31.2750        S  NaN
65          0       3    male  11.00      0      0   18.7875        C  NaN
66          0       3    male  11.00      5      2   46.9000        S  NaN
67          1       1    male  11.00      1      2  120.0000        S    B
68          1       3    male  12.00      1      0   11.2417        C  NaN
69          1       2  female  13.00      0      1   19.5000        S  NaN
70          1       3  female  13.00      0      0    7.2292        C  NaN
71          1       1  female  14.00      1      2  120.0000        S    B
72          0       3    male  14.00      4      1   39.6875        S  NaN
73          1       2  female  14.00      1      0   30.0708        C  NaN
74          1       3  female  14.00      1      0   11.2417        C  NaN
75          0       3    male  14.00      5      2   46.9000        S  NaN
76          0       3  female  14.00      0      0    7.8542        S  NaN
77          0       3  female  14.50      1      0   14.4542        C  NaN
78          0       3    male  15.00      1      1    7.2292        C  NaN
79          1       3  female  15.00      0      0    7.2250        C  NaN
80          1       1  female  15.00      0      1  211.3375        S    B
81          1       3  female  15.00      0      0    8.0292        Q  NaN
82          1       3  female  15.00      1      0   14.4542        C  NaN
83          1       3    male  16.00      0      0    8.0500        S  NaN
84          0       2    male  16.00      0      0   26.0000        S  NaN
85          0       3    male  16.00      2      0   18.0000        S  NaN
86          0       3    male  16.00      0      0    9.2167        S  NaN
87          0       3    male  16.00      4      1   39.6875        S  NaN
88          0       3    male  16.00      0      0    9.5000        S  NaN
89          0       3    male  16.00      1      3   34.3750        S  NaN
90          0       3    male  16.00      0      0    8.0500        S  NaN
91          0       3  female  16.00      5      2   46.9000        S  NaN
92          1       1  female  16.00      0      1   57.9792        C    B
93          0       2    male  16.00      0      0   10.5000        S  NaN
94          1       1  female  16.00      0      1   39.4000        S    D
95          0       3    male  16.00      0      0    7.7750        S  NaN
96          1       1  female  16.00      0      0   86.5000        S    B
97          0       3    male  16.00      1      1   20.2500        S  NaN
98          1       3  female  16.00      0      0    7.7333        Q  NaN
99          1       3  female  16.00      0      0    7.7500        Q  NaN
100         0       3    male  17.00      0      0    8.6625        S  NaN
101         0       3    male  17.00      1      0    7.0542        S  NaN
102         0       3    male  17.00      0      0    7.1250        S  NaN
103         1       1    male  17.00      0      2  110.8833        C    C
104         1       2  female  17.00      0      0   12.0000        C  NaN
105         0       3    male  17.00      0      0    8.6625        S  NaN
106         0       3    male  17.00      1      1    7.2292        C  NaN
107         0       3    male  17.00      0      0    8.6625        S  NaN
108         1       3  female  17.00      4      2    7.9250        S  NaN
109         1       1  female  17.00      1      0   57.0000        S    B
110         1       1  female  17.00      1      0  108.9000        C    C
111         1       2  female  17.00      0      0   10.5000        S  NaN
112         0       3  female  17.00      0      0   14.4583        C  NaN
113         0       3  female  18.00      0      0    6.7500        Q  NaN
114         0       3    male  18.00      1      1   20.2125        S  NaN
115         1       2  female  18.00      0      2   13.0000        S  NaN
116         0       3    male  18.00      0      0    7.7958        S  NaN
117         0       2    male  18.00      0      0   73.5000        S  NaN
118         0       3    male  18.00      1      0    6.4958        S  NaN
119         0       2    male  18.00      0      0   13.0000        S  NaN
120         0       1    male  18.00      1      0  108.9000        C    C
121         1       3    male  18.00      0      0    8.0500        S  NaN
122         1       3  female  18.00      0      0    9.8417        S  NaN
123         0       3    male  18.00      1      1    7.8542        S  NaN
124         0       3    male  18.00      0      0    7.7750        S  NaN
125         1       1  female  18.00      2      2  262.3750        C    B
126         1       1  female  18.00      0      2   79.6500        S    E
127         1       2  female  18.00      0      1   23.0000        S  NaN
128         0       3  female  18.00      0      1   14.4542        C  NaN
129         1       1  female  18.00      1      0  227.5250        C    C
130         0       2    male  18.00      0      0   11.5000        S  NaN
131         1       3  female  18.00      0      0    7.4958        S  NaN
132         1       3  female  18.00      0      1    9.3500        S  NaN
133         0       3  female  18.00      2      0   18.0000        S  NaN
134         0       3  female  18.00      0      0    7.7750        S  NaN
135         0       3    male  18.00      0      0    8.3000        S  NaN
136         0       2    male  18.00      0      0   11.5000        S  NaN
137         0       3    male  18.00      0      0    7.7500        S  NaN
138         0       3  female  18.00      1      0   17.8000        S  NaN
139         1       2    male  19.00      0      0   10.5000        S  NaN
140         1       1  female  19.00      0      2   26.2833        S    D
141         0       1    male  19.00      3      2  263.0000        S    C
142         0       3    male  19.00      0      0    7.6500        S    F
143         1       1  female  19.00      1      0   91.0792        C    B
144         0       3    male  19.00      0      0    0.0000        S  NaN
145         1       2  female  19.00      0      0   26.0000        S  NaN
146         0       3    male  19.00      0      0    8.1583        S  NaN
147         1       2  female  19.00      1      0   26.0000        S  NaN
148         0       3    male  19.00      0      0    7.8958        S  NaN
149         0       3    male  19.00      0      0   14.5000        S  NaN
150         0       3    male  19.00      0      0    7.8958        S  NaN
151         1       3  female  19.00      0      0    7.8792        Q  NaN
152         0       2    male  19.00      0      0   10.5000        S  NaN
153         0       3    male  19.00      0      0   10.1708        S  NaN
154         0       2    male  19.00      0      0   13.0000        S  NaN
155         0       3    male  19.00      0      0    7.8958        S  NaN
156         1       1  female  19.00      0      0   30.0000        S    B
157         1       3    male  19.00      0      0    8.0500        S  NaN
158         0       1    male  19.00      1      0   53.1000        S    D
159         0       3    male  19.00      0      0    6.7500        Q  NaN
160         0       3    male  19.00      0      0    8.0500        S  NaN
161         0       2    male  19.00      1      1   36.7500        S  NaN
162         0       3    male  19.00      0      0    7.7750        S  NaN
163         1       3  female  19.00      1      0    7.8542        S  NaN
164         0       3    male  20.00      0      0    4.0125        C  NaN
165         1       3    male  20.00      0      0    7.2292        C  NaN
166         1       3    male  20.00      1      1   15.7417        C  NaN
167         0       3    male  20.00      0      0    7.9250        S  NaN
168         0       3    male  20.00      0      0    9.8458        S  NaN
169         0       3    male  20.00      0      0    7.0500        S  NaN
170         1       3    male  20.00      1      0    7.9250        S  NaN
171         0       3    male  20.00      0      0    9.5000        S  NaN
172         0       3  female  20.00      0      0    8.6625        S  NaN
173         0       3    male  20.00      0      0    8.0500        S  NaN
174         0       3    male  20.00      0      0    7.8542        S  NaN
175         0       3    male  20.00      0      0    9.2250        S  NaN
176         0       3    male  20.00      0      0    8.6625        S  NaN
177         0       3    male  20.00      0      0    7.8542        S  NaN
178         0       3  female  20.00      1      0    9.8250        S  NaN
179         0       3    male  20.50      0      0    7.2500        S  NaN
180         0       3  female  21.00      1      0    9.8250        S  NaN
181         0       3    male  21.00      0      0    7.7750        S  NaN
182         0       1    male  21.00      0      1   77.2875        S    D
183         1       1  female  21.00      0      0   77.9583        S    D
184         1       3  female  21.00      0      0    7.6500        S  NaN
185         0       3    male  21.00      0      0    8.4333        S  NaN
186         0       2    male  21.00      0      0   73.5000        S  NaN
187         0       3    male  21.00      0      0    7.9250        S  NaN
188         0       2    male  21.00      1      0   11.5000        S  NaN
189         0       3    male  21.00      0      0    7.9250        S  NaN
190         1       1  female  21.00      2      2  262.3750        C    B
191         0       3    male  21.00      0      0    8.0500        S  NaN
192         0       3  female  21.00      0      0    7.7500        Q  NaN
193         0       3    male  21.00      0      0    8.0500        S  NaN
194         0       3  female  21.00      2      2   34.3750        S  NaN
195         0       3    male  21.00      0      0    7.2500        S  NaN
196         0       3    male  21.00      0      0    7.8000        S  NaN
197         0       3    male  21.00      0      0    7.7333        Q  NaN
198         1       2  female  21.00      0      0   10.5000        S  NaN
199         0       3    male  21.00      0      0    7.8542        S  NaN
200         0       3    male  21.00      0      0    8.6625        S  NaN
201         0       3    male  21.00      0      0   16.1000        S  NaN
202         1       3    male  21.00      0      0    7.7958        S  NaN
203         0       2    male  21.00      2      0   73.5000        S  NaN
204         0       3    male  22.00      0      0    8.0500        S  NaN
205         1       3  female  22.00      0      0    7.2500        S  NaN
206         1       3  female  22.00      0      0    7.7750        S  NaN
207         0       1    male  22.00      0      0  135.6333        C  NaN
208         0       3  female  22.00      0      0    9.8375        S  NaN
209         0       3    male  22.00      0      0    7.2500        S  NaN
210         1       3    male  22.00      0      0    7.2250        C  NaN
211         0       3    male  22.00      0      0    7.7958        S  NaN
212         0       3    male  22.00      0      0    7.8958        S  NaN
213         1       2  female  22.00      1      2   41.5792        C  NaN
214         1       3  female  22.00      0      0    7.7500        Q  NaN
215         0       3    male  22.00      0      0    7.5208        S  NaN
216         1       2  female  22.00      1      1   29.0000        S  NaN
217         0       3    male  22.00      0      0    7.8958        S  NaN
218         0       3    male  22.00      0      0    7.2292        C  NaN
219         1       1  female  22.00      0      2   49.5000        C    B
220         0       3    male  22.00      0      0    9.0000        S  NaN
221         1       1  female  22.00      0      1   55.0000        S    E
222         0       3    male  22.00      1      0    7.2500        S  NaN
223         0       3    male  22.00      0      0    7.2500        S  NaN
224         1       1  female  22.00      1      0   66.6000        S    C
225         1       1  female  22.00      0      0  151.5500        S  NaN
226         1       3  female  22.00      0      0    7.7500        S  NaN
227         0       3    male  22.00      0      0    9.3500        S  NaN
228         0       3    male  22.00      0      0    8.0500        S  NaN
229         0       3  female  22.00      0      0   10.5167        S  NaN
230         0       3    male  22.00      0      0    7.1250        S  NaN
231         0       3    male  23.00      0      0    9.2250        S  NaN
232         0       2    male  23.00      2      1   11.5000        S  NaN
233         0       2    male  23.00      0      0   13.0000        S  NaN
234         1       1  female  23.00      1      0  113.2750        C    D
235         0       2    male  23.00      0      0   13.0000        S  NaN
236         0       3    male  23.00      0      0    7.8542        S  NaN
237         0       2    male  23.00      0      0   13.0000        S  NaN
238         1       1  female  23.00      3      2  263.0000        S    C
239         0       2    male  23.00      0      0   15.0458        C  NaN
240         0       3  female  23.00      0      0    7.9250        S  NaN
241         0       2    male  23.00      0      0   10.5000        S  NaN
242         1       2  female  23.00      0      0   13.7917        C    D
243         0       3    male  23.00      0      0    7.8958        S  NaN
244         1       3  female  23.00      0      0    7.5500        S  NaN
245         1       1    male  23.00      0      1   63.3583        C    D
246         0       3    male  23.50      0      0    7.2292        C  NaN
247         1       2  female  24.00      2      3   18.7500        S  NaN
248         0       3    male  24.00      0      0    7.0500        S  NaN
249         0       1    male  24.00      0      0   79.2000        C    B
250         1       1  female  24.00      3      2  263.0000        S    C
251         0       2    male  24.00      0      0   13.0000        S  NaN
252         0       3    male  24.00      0      0    8.0500        S  NaN
253         1       1  female  24.00      0      0   69.3000        C    B
254         1       3    male  24.00      0      0    7.1417        S  NaN
255         1       3  female  24.00      1      0   15.8500        S  NaN
256         1       2  female  24.00      0      0   13.0000        S    F
257         0       1    male  24.00      0      1  247.5208        C    B
258         1       2  female  24.00      1      2   65.0000        S  NaN
259         0       3    male  24.00      0      0    7.4958        S  NaN
260         0       3    male  24.00      0      0    7.8958        S  NaN
261         0       2    male  24.00      0      0   10.5000        S  NaN
262         1       2  female  24.00      2      1   27.0000        S  NaN
263         0       3  female  24.00      0      0    8.8500        S  NaN
264         1       2  female  24.00      0      2   14.5000        S  NaN

In [27]:
titanic.sort_values(by = "age", ignore_index = True)

     survived  pclass     sex    age  sibsp  parch      fare embarked deck
0           1       3    male   0.42      0      1    8.5167        C  NaN
1           1       2    male   0.67      1      1   14.5000        S  NaN
2           1       3  female   0.75      2      1   19.2583        C  NaN
3           1       3  female   0.75      2      1   19.2583        C  NaN
4           1       2    male   0.83      0      2   29.0000        S  NaN
5           1       2    male   0.83      1      1   18.7500        S  NaN
6           1       1    male   0.92      1      2  151.5500        S    C
7           1       2    male   1.00      0      2   37.0042        C  NaN
8           1       3  female   1.00      0      2   15.7417        C  NaN
9           0       3    male   1.00      4      1   39.6875        S  NaN
10          1       2    male   1.00      2      1   39.0000        S    F
11          0       3    male   1.00      5      2   46.9000        S  NaN
12          1       3  female   1.00      1      1   11.1333        S  NaN
13          1       3    male   1.00      1      2   20.5750        S  NaN
14          0       3  female   2.00      3      2   27.9000        S  NaN
15          0       3    male   2.00      3      1   21.0750        S  NaN
16          1       2  female   2.00      1      1   26.0000        S  NaN
17          0       1  female   2.00      1      2  151.5500        S    C
18          0       3    male   2.00      4      1   39.6875        S  NaN
19          0       3  female   2.00      0      1   10.4625        S    G
20          0       3  female   2.00      4      2   31.2750        S  NaN
21          1       2    male   2.00      1      1   26.0000        S    F
22          1       3  female   2.00      0      1   12.2875        S  NaN
23          0       3    male   2.00      4      1   29.1250        Q  NaN
24          1       3    male   3.00      1      1   15.9000        S  NaN
25          1       2    male   3.00      1      1   18.7500        S  NaN
26          0       3  female   3.00      3      1   21.0750        S  NaN
27          1       3    male   3.00      4      2   31.3875        S  NaN
28          1       2  female   3.00      1      2   41.5792        C  NaN
29          1       2    male   3.00      1      1   26.0000        S    F
30          0       3    male   4.00      4      2   31.2750        S  NaN
31          0       3    male   4.00      4      1   29.1250        Q  NaN
32          0       3    male   4.00      3      2   27.9000        S  NaN
33          1       2  female   4.00      1      1   23.0000        S  NaN
34          1       3  female   4.00      0      1   13.4167        C  NaN
35          1       3    male   4.00      1      1   11.1333        S  NaN
36          1       2  female   4.00      2      1   39.0000        S    F
37          1       3  female   4.00      1      1   16.7000        S    G
38          1       1    male   4.00      0      2   81.8583        S    A
39          1       3  female   4.00      0      2   22.0250        S  NaN
40          1       3  female   5.00      4      2   31.3875        S  NaN
41          1       3  female   5.00      0      0   12.4750        S  NaN
42          1       3  female   5.00      2      1   19.2583        C  NaN
43          1       2  female   5.00      1      2   27.7500        S  NaN
44          1       2  female   6.00      0      1   33.0000        S  NaN
45          0       3  female   6.00      4      2   31.2750        S  NaN
46          1       3    male   6.00      0      1   12.4750        S    E
47          0       3    male   7.00      4      1   29.1250        Q  NaN
48          1       2  female   7.00      0      2   26.2500        S  NaN
49          0       3    male   7.00      4      1   39.6875        S  NaN
50          0       3  female   8.00      3      1   21.0750        S  NaN
51          1       2    male   8.00      1      1   36.7500        S  NaN
52          1       2  female   8.00      0      2   26.2500        S  NaN
53          0       3    male   8.00      4      1   29.1250        Q  NaN
54          0       3  female   9.00      2      2   34.3750        S  NaN
55          0       3  female   9.00      4      2   31.2750        S  NaN
56          0       3  female   9.00      1      1   15.2458        C  NaN
57          0       3    male   9.00      4      2   31.3875        S  NaN
58          0       3    male   9.00      5      2   46.9000        S  NaN
59          0       3  female   9.00      3      2   27.9000        S  NaN
60          1       3    male   9.00      1      1   15.9000        S  NaN
61          1       3    male   9.00      0      2   20.5250        S  NaN
62          0       3  female  10.00      0      2   24.1500        S  NaN
63          0       3    male  10.00      3      2   27.9000        S  NaN
64          0       3  female  11.00      4      2   31.2750        S  NaN
65          0       3    male  11.00      0      0   18.7875        C  NaN
66          0       3    male  11.00      5      2   46.9000        S  NaN
67          1       1    male  11.00      1      2  120.0000        S    B
68          1       3    male  12.00      1      0   11.2417        C  NaN
69          1       2  female  13.00      0      1   19.5000        S  NaN
70          1       3  female  13.00      0      0    7.2292        C  NaN
71          1       1  female  14.00      1      2  120.0000        S    B
72          0       3    male  14.00      4      1   39.6875        S  NaN
73          1       2  female  14.00      1      0   30.0708        C  NaN
74          1       3  female  14.00      1      0   11.2417        C  NaN
75          0       3    male  14.00      5      2   46.9000        S  NaN
76          0       3  female  14.00      0      0    7.8542        S  NaN
77          0       3  female  14.50      1      0   14.4542        C  NaN
78          0       3    male  15.00      1      1    7.2292        C  NaN
79          1       3  female  15.00      0      0    7.2250        C  NaN
80          1       1  female  15.00      0      1  211.3375        S    B
81          1       3  female  15.00      0      0    8.0292        Q  NaN
82          1       3  female  15.00      1      0   14.4542        C  NaN
83          1       3    male  16.00      0      0    8.0500        S  NaN
84          0       2    male  16.00      0      0   26.0000        S  NaN
85          0       3    male  16.00      2      0   18.0000        S  NaN
86          0       3    male  16.00      0      0    9.2167        S  NaN
87          0       3    male  16.00      4      1   39.6875        S  NaN
88          0       3    male  16.00      0      0    9.5000        S  NaN
89          0       3    male  16.00      1      3   34.3750        S  NaN
90          0       3    male  16.00      0      0    8.0500        S  NaN
91          0       3  female  16.00      5      2   46.9000        S  NaN
92          1       1  female  16.00      0      1   57.9792        C    B
93          0       2    male  16.00      0      0   10.5000        S  NaN
94          1       1  female  16.00      0      1   39.4000        S    D
95          0       3    male  16.00      0      0    7.7750        S  NaN
96          1       1  female  16.00      0      0   86.5000        S    B
97          0       3    male  16.00      1      1   20.2500        S  NaN
98          1       3  female  16.00      0      0    7.7333        Q  NaN
99          1       3  female  16.00      0      0    7.7500        Q  NaN
100         0       3    male  17.00      0      0    8.6625        S  NaN
101         0       3    male  17.00      1      0    7.0542        S  NaN
102         0       3    male  17.00      0      0    7.1250        S  NaN
103         1       1    male  17.00      0      2  110.8833        C    C
104         1       2  female  17.00      0      0   12.0000        C  NaN
105         0       3    male  17.00      0      0    8.6625        S  NaN
106         0       3    male  17.00      1      1    7.2292        C  NaN
107         0       3    male  17.00      0      0    8.6625        S  NaN
108         1       3  female  17.00      4      2    7.9250        S  NaN
109         1       1  female  17.00      1      0   57.0000        S    B
110         1       1  female  17.00      1      0  108.9000        C    C
111         1       2  female  17.00      0      0   10.5000        S  NaN
112         0       3  female  17.00      0      0   14.4583        C  NaN
113         0       3  female  18.00      0      0    6.7500        Q  NaN
114         0       3    male  18.00      1      1   20.2125        S  NaN
115         1       2  female  18.00      0      2   13.0000        S  NaN
116         0       3    male  18.00      0      0    7.7958        S  NaN
117         0       2    male  18.00      0      0   73.5000        S  NaN
118         0       3    male  18.00      1      0    6.4958        S  NaN
119         0       2    male  18.00      0      0   13.0000        S  NaN
120         0       1    male  18.00      1      0  108.9000        C    C
121         1       3    male  18.00      0      0    8.0500        S  NaN
122         1       3  female  18.00      0      0    9.8417        S  NaN
123         0       3    male  18.00      1      1    7.8542        S  NaN
124         0       3    male  18.00      0      0    7.7750        S  NaN
125         1       1  female  18.00      2      2  262.3750        C    B
126         1       1  female  18.00      0      2   79.6500        S    E
127         1       2  female  18.00      0      1   23.0000        S  NaN
128         0       3  female  18.00      0      1   14.4542        C  NaN
129         1       1  female  18.00      1      0  227.5250        C    C
130         0       2    male  18.00      0      0   11.5000        S  NaN
131         1       3  female  18.00      0      0    7.4958        S  NaN
132         1       3  female  18.00      0      1    9.3500        S  NaN
133         0       3  female  18.00      2      0   18.0000        S  NaN
134         0       3  female  18.00      0      0    7.7750        S  NaN
135         0       3    male  18.00      0      0    8.3000        S  NaN
136         0       2    male  18.00      0      0   11.5000        S  NaN
137         0       3    male  18.00      0      0    7.7500        S  NaN
138         0       3  female  18.00      1      0   17.8000        S  NaN
139         1       2    male  19.00      0      0   10.5000        S  NaN
140         1       1  female  19.00      0      2   26.2833        S    D
141         0       1    male  19.00      3      2  263.0000        S    C
142         0       3    male  19.00      0      0    7.6500        S    F
143         1       1  female  19.00      1      0   91.0792        C    B
144         0       3    male  19.00      0      0    0.0000        S  NaN
145         1       2  female  19.00      0      0   26.0000        S  NaN
146         0       3    male  19.00      0      0    8.1583        S  NaN
147         1       2  female  19.00      1      0   26.0000        S  NaN
148         0       3    male  19.00      0      0    7.8958        S  NaN
149         0       3    male  19.00      0      0   14.5000        S  NaN
150         0       3    male  19.00      0      0    7.8958        S  NaN
151         1       3  female  19.00      0      0    7.8792        Q  NaN
152         0       2    male  19.00      0      0   10.5000        S  NaN
153         0       3    male  19.00      0      0   10.1708        S  NaN
154         0       2    male  19.00      0      0   13.0000        S  NaN
155         0       3    male  19.00      0      0    7.8958        S  NaN
156         1       1  female  19.00      0      0   30.0000        S    B
157         1       3    male  19.00      0      0    8.0500        S  NaN
158         0       1    male  19.00      1      0   53.1000        S    D
159         0       3    male  19.00      0      0    6.7500        Q  NaN
160         0       3    male  19.00      0      0    8.0500        S  NaN
161         0       2    male  19.00      1      1   36.7500        S  NaN
162         0       3    male  19.00      0      0    7.7750        S  NaN
163         1       3  female  19.00      1      0    7.8542        S  NaN
164         0       3    male  20.00      0      0    4.0125        C  NaN
165         1       3    male  20.00      0      0    7.2292        C  NaN
166         1       3    male  20.00      1      1   15.7417        C  NaN
167         0       3    male  20.00      0      0    7.9250        S  NaN
168         0       3    male  20.00      0      0    9.8458        S  NaN
169         0       3    male  20.00      0      0    7.0500        S  NaN
170         1       3    male  20.00      1      0    7.9250        S  NaN
171         0       3    male  20.00      0      0    9.5000        S  NaN
172         0       3  female  20.00      0      0    8.6625        S  NaN
173         0       3    male  20.00      0      0    8.0500        S  NaN
174         0       3    male  20.00      0      0    7.8542        S  NaN
175         0       3    male  20.00      0      0    9.2250        S  NaN
176         0       3    male  20.00      0      0    8.6625        S  NaN
177         0       3    male  20.00      0      0    7.8542        S  NaN
178         0       3  female  20.00      1      0    9.8250        S  NaN
179         0       3    male  20.50      0      0    7.2500        S  NaN
180         0       3  female  21.00      1      0    9.8250        S  NaN
181         0       3    male  21.00      0      0    7.7750        S  NaN
182         0       1    male  21.00      0      1   77.2875        S    D
183         1       1  female  21.00      0      0   77.9583        S    D
184         1       3  female  21.00      0      0    7.6500        S  NaN
185         0       3    male  21.00      0      0    8.4333        S  NaN
186         0       2    male  21.00      0      0   73.5000        S  NaN
187         0       3    male  21.00      0      0    7.9250        S  NaN
188         0       2    male  21.00      1      0   11.5000        S  NaN
189         0       3    male  21.00      0      0    7.9250        S  NaN
190         1       1  female  21.00      2      2  262.3750        C    B
191         0       3    male  21.00      0      0    8.0500        S  NaN
192         0       3  female  21.00      0      0    7.7500        Q  NaN
193         0       3    male  21.00      0      0    8.0500        S  NaN
194         0       3  female  21.00      2      2   34.3750        S  NaN
195         0       3    male  21.00      0      0    7.2500        S  NaN
196         0       3    male  21.00      0      0    7.8000        S  NaN
197         0       3    male  21.00      0      0    7.7333        Q  NaN
198         1       2  female  21.00      0      0   10.5000        S  NaN
199         0       3    male  21.00      0      0    7.8542        S  NaN
200         0       3    male  21.00      0      0    8.6625        S  NaN
201         0       3    male  21.00      0      0   16.1000        S  NaN
202         1       3    male  21.00      0      0    7.7958        S  NaN
203         0       2    male  21.00      2      0   73.5000        S  NaN
204         0       3    male  22.00      0      0    8.0500        S  NaN
205         1       3  female  22.00      0      0    7.2500        S  NaN
206         1       3  female  22.00      0      0    7.7750        S  NaN
207         0       1    male  22.00      0      0  135.6333        C  NaN
208         0       3  female  22.00      0      0    9.8375        S  NaN
209         0       3    male  22.00      0      0    7.2500        S  NaN
210         1       3    male  22.00      0      0    7.2250        C  NaN
211         0       3    male  22.00      0      0    7.7958        S  NaN
212         0       3    male  22.00      0      0    7.8958        S  NaN
213         1       2  female  22.00      1      2   41.5792        C  NaN
214         1       3  female  22.00      0      0    7.7500        Q  NaN
215         0       3    male  22.00      0      0    7.5208        S  NaN
216         1       2  female  22.00      1      1   29.0000        S  NaN
217         0       3    male  22.00      0      0    7.8958        S  NaN
218         0       3    male  22.00      0      0    7.2292        C  NaN
219         1       1  female  22.00      0      2   49.5000        C    B
220         0       3    male  22.00      0      0    9.0000        S  NaN
221         1       1  female  22.00      0      1   55.0000        S    E
222         0       3    male  22.00      1      0    7.2500        S  NaN
223         0       3    male  22.00      0      0    7.2500        S  NaN
224         1       1  female  22.00      1      0   66.6000        S    C
225         1       1  female  22.00      0      0  151.5500        S  NaN
226         1       3  female  22.00      0      0    7.7500        S  NaN
227         0       3    male  22.00      0      0    9.3500        S  NaN
228         0       3    male  22.00      0      0    8.0500        S  NaN
229         0       3  female  22.00      0      0   10.5167        S  NaN
230         0       3    male  22.00      0      0    7.1250        S  NaN
231         0       3    male  23.00      0      0    9.2250        S  NaN
232         0       2    male  23.00      2      1   11.5000        S  NaN
233         0       2    male  23.00      0      0   13.0000        S  NaN
234         1       1  female  23.00      1      0  113.2750        C    D
235         0       2    male  23.00      0      0   13.0000        S  NaN
236         0       3    male  23.00      0      0    7.8542        S  NaN
237         0       2    male  23.00      0      0   13.0000        S  NaN
238         1       1  female  23.00      3      2  263.0000        S    C
239         0       2    male  23.00      0      0   15.0458        C  NaN
240         0       3  female  23.00      0      0    7.9250        S  NaN
241         0       2    male  23.00      0      0   10.5000        S  NaN
242         1       2  female  23.00      0      0   13.7917        C    D
243         0       3    male  23.00      0      0    7.8958        S  NaN
244         1       3  female  23.00      0      0    7.5500        S  NaN
245         1       1    male  23.00      0      1   63.3583        C    D
246         0       3    male  23.50      0      0    7.2292        C  NaN
247         1       2  female  24.00      2      3   18.7500        S  NaN
248         0       3    male  24.00      0      0    7.0500        S  NaN
249         0       1    male  24.00      0      0   79.2000        C    B
250         1       1  female  24.00      3      2  263.0000        S    C
251         0       2    male  24.00      0      0   13.0000        S  NaN
252         0       3    male  24.00      0      0    8.0500        S  NaN
253         1       1  female  24.00      0      0   69.3000        C    B
254         1       3    male  24.00      0      0    7.1417        S  NaN
255         1       3  female  24.00      1      0   15.8500        S  NaN
256         1       2  female  24.00      0      0   13.0000        S    F
257         0       1    male  24.00      0      1  247.5208        C    B
258         1       2  female  24.00      1      2   65.0000        S  NaN
259         0       3    male  24.00      0      0    7.4958        S  NaN
260         0       3    male  24.00      0      0    7.8958        S  NaN
261         0       2    male  24.00      0      0   10.5000        S  NaN
262         1       2  female  24.00      2      1   27.0000        S  NaN
263         0       3  female  24.00      0      0    8.8500        S  NaN
264         1       2  female  24.00      0      2   14.5000        S  NaN

### Ranking DataFrames with rank()

In [28]:
import pandas as pd

In [29]:
sales = pd.Series([15, 32, 45, 21, 55, 15, 0],  index = ["Mo", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])

In [30]:
sales = pd.Series([15, 32, 45, 15, 55, 15, 0],  index = ["Mo", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])

In [31]:
sales

Mo     15
Tue    32
Wed    45
Thu    15
Fri    55
Sat    15
Sun     0
dtype: int64

In [32]:
sales.sort_values(ascending = False)

Fri    55
Wed    45
Tue    32
Mo     15
Thu    15
Sat    15
Sun     0
dtype: int64

In [33]:
sales.rank(ascending=False, method = "min").sort_values(ascending = True)

Fri    1.0
Wed    2.0
Tue    3.0
Mo     4.0
Thu    4.0
Sat    4.0
Sun    7.0
dtype: float64

In [34]:
sales.rank(ascending=False, method = "min", pct=True).sort_values()

Fri    0.142857
Wed    0.285714
Tue    0.428571
Mo     0.571429
Thu    0.571429
Sat    0.571429
Sun    1.000000
dtype: float64

In [35]:
titanic = pd.read_csv("titanic.csv")

In [36]:
titanic.fare.rank(ascending = False)

0      815.0
1      103.0
2      659.5
3      144.0
4      628.0
5      599.0
6      157.5
7      359.5
8      526.0
9      233.5
10     396.5
11     277.0
12     628.0
13     219.0
14     719.0
15     407.0
16     246.0
17     484.5
18     391.0
19     842.5
20     311.0
21     484.5
22     650.0
23     196.5
24     359.5
25     213.5
26     842.5
27       5.5
28     709.5
29     687.5
30     265.0
31      30.5
32     768.5
33     540.5
34      72.5
35     153.0
36     829.0
37     628.0
38     391.0
39     523.5
40     573.0
41     364.5
42     687.5
43     174.0
44     709.5
45     628.0
46     421.5
47     768.5
48     357.0
49     393.5
50     179.5
51     728.0
52      94.0
53     311.0
54     120.0
55     196.5
56     540.5
57     829.0
58     260.5
59     168.5
60     829.0
61      75.5
62      67.5
63     255.5
64     265.0
65     428.0
66     540.5
67     604.0
68     659.5
69     590.0
70     540.5
71     168.5
72     100.0
73     448.0
74     133.0
75     796.5
76     687.5
77     628.0
78     249.5
79     510.5
80     579.5
81     567.0
82     735.0
83     165.0
84     540.5
85     411.5
86     202.5
87     628.0
88       5.5
89     628.0
90     628.0
91     719.0
92     122.0
93     368.5
94     815.0
95     628.0
96     200.0
97     119.0
98     350.5
99     311.0
100    687.5
101    687.5
102     91.5
103    597.0
104    659.5
105    687.5
106    796.5
107    743.5
108    687.5
109    338.5
110    153.0
111    448.0
112    628.0
113    559.5
114    443.0
115    659.5
116    768.5
117    364.5
118     10.5
119    219.0
120    100.0
121    628.0
122    233.5
123    484.5
124     91.5
125    523.5
126    768.5
127    849.0
128    354.5
129    864.5
130    687.5
131    859.0
132    438.0
133    311.0
134    484.5
135    433.0
136    289.0
137    144.0
138    578.0
139     81.5
140    428.0
141    768.5
142    411.5
143    868.5
144    520.5
145    193.5
146    731.5
147    202.5
148    311.0
149    484.5
150    508.0
151    115.5
152    628.0
153    438.0
154    808.0
155    121.0
156    790.5
157    628.0
158    590.0
159    109.0
160    402.0
161    414.0
162    743.5
163    590.0
164    179.5
165    371.0
166    140.5
167    255.5
168    329.0
169    133.0
170    206.0
171    246.0
172    526.0
173    659.5
174    226.5
175    719.0
176    332.5
177    251.0
178    484.5
179    884.0
180    109.0
181    432.0
182    213.5
183    187.5
184    356.0
185    161.0
186    421.5
187    277.0
188    421.5
189    687.5
190    484.5
191    484.5
192    719.0
193    311.0
194    265.0
195     30.5
196    768.5
197    601.0
198    768.5
199    484.5
200    567.0
201    109.0
202    870.5
203    842.5
204    628.0
205    553.5
206    411.5
207    385.5
208    768.5
209    224.0
210    859.0
211    364.5
212    815.0
213    484.5
214    768.5
215     44.0
216    659.5
217    268.5
218     96.0
219    540.5
220    628.0
221    484.5
222    628.0
223    687.5
224     59.5
225    574.5
226    540.5
227    815.0
228    484.5
229    332.5
230     67.5
231    743.5
232    460.5
233    213.5
234    540.5
235    801.5
236    311.0
237    292.5
238    540.5
239    517.0
240    448.0
241    421.5
242    540.5
243    851.5
244    842.5
245     59.5
246    743.5
247    438.0
248    148.0
249    311.0
250    815.0
251    553.5
252    277.0
253    402.0
254    375.5
255    428.0
256     81.5
257     65.0
258      2.0
259    311.0
260    768.5
261    213.5
262     78.0
263    884.0
264    768.5
265    540.5
266    179.5
267    743.5
268     24.0
269     33.0
270    224.0
271    884.0
272    379.5
273    242.0
274    768.5
275     89.0
276    768.5
277    884.0
278    246.0
279    373.5
280    768.5
281    719.0
282    567.0
283    628.0
284    311.0
285    590.0
286    567.0
287    687.5
288    484.5
289    768.5
290     84.5
291     56.5
292    506.0
293    581.0
294    687.5
295    265.0
296    829.0
297     27.5
298    230.0
299     10.5
300    768.5
301    347.5
302    884.0
303    514.0
304    628.0
305     27.5
306     47.5
307     50.5
308    343.5
309    128.5
310     70.0
311      8.5
312    311.0
313    687.5
314    292.5
315    719.0
316    311.0
317    455.0
318     21.5
319     35.5
320    815.0
321    687.5
322    514.0
323    249.5
324    109.0
325     33.0
326    874.0
327    484.5
328    371.0
329    124.5
330    347.5
331    252.0
332     24.0
333    391.0
334     37.5
335    687.5
336    115.5
337     35.5
338    628.0
339    196.5
340    311.0
341      5.5
342    484.5
343    484.5
344    484.5
345    484.5
346    484.5
347    402.0
348    408.5
349    590.0
350    576.5
351    199.0
352    829.0
353    393.5
354    842.5
355    567.0
356    140.5
357    484.5
358    709.5
359    709.5
360    255.5
361    265.0
362    448.0
363    859.0
364    421.5
365    815.0
366     97.0
367    829.0
368    768.5
369    113.5
370    139.0
371    870.5
372    628.0
373     33.0
374    359.5
375     72.5
376    815.0
377     17.0
378    876.0
379    743.5
380     13.5
381    415.5
382    659.5
383    153.0
384    687.5
385    100.0
386    168.5
387    484.5
388    793.0
389    518.0
390     40.5
391    731.5
392    659.5
393     44.0
394    396.5
395    731.5
396    719.0
397    311.0
398    540.5
399    507.0
400    659.5
401    628.0
402    559.5
403    411.5
404    590.0
405    364.5
406    768.5
407    388.0
408    743.5
409    332.5
410    687.5
411    867.0
412     59.5
413    884.0
414    659.5
415    628.0
416    210.0
417    484.5
418    484.5
419    338.5
420    687.5
421    790.5
422    712.0
423    452.5
424    375.5
425    815.0
426    311.0
427    311.0
428    768.5
429    628.0
430    277.0
431    402.0
432    311.0
433    851.5
434    137.5
435     40.5
436    202.5
437    388.0
438      5.5
439    540.5
440    292.5
441    567.0
442    743.5
443    484.5
444    606.0
445     74.0
446    379.5
447    277.0
448    382.5
449    230.0
450    260.5
451    377.5
452    260.5
453     62.5
454    628.0
455    687.5
456    277.0
457    157.5
458    540.5
459    768.5
460    277.0
461    628.0
462    190.0
463    484.5
464    628.0
465    859.0
466    884.0
467    277.0
468    794.0
469    382.5
470    815.0
471    590.0
472    260.5
473    458.0
474    558.0
475    153.0
476    364.5
477    863.0
478    804.0
479    516.0
480    168.5
481    884.0
482    628.0
483    561.5
484     56.5
485    332.5
486     59.5
487    242.0
488    628.0
489    408.5
490    377.5
491    815.0
492    230.0
493    162.5
494    628.0
495    443.0
496     86.5
497    431.0
498     27.5
499    731.5
500    590.0
501    768.5
502    799.0
503    561.5
504     65.0
505     50.5
506    311.0
507    277.0
508    353.0
509    133.0
510    768.5
511    628.0
512    287.0
513    123.0
514    806.0
515    205.0
516    540.5
517    338.5
518    311.0
519    687.5
520     54.5
521    687.5
522    842.5
523    124.5
524    829.0
525    768.5
526    540.5
527     16.0
528    659.5
529    520.5
530    311.0
531    829.0
532    829.0
533    354.5
534    590.0
535    292.5
536    277.0
537     52.5
538    438.0
539    164.0
540    104.5
541    219.0
542    219.0
543    311.0
544     52.5
545    311.0
546    311.0
547    456.0
548    371.0
549    193.5
550     47.5
551    311.0
552    726.5
553    842.5
554    743.5
555    277.0
556    183.5
557     13.5
558     78.0
559    395.0
560    768.5
561    687.5
562    460.5
563    628.0
564    628.0
565    338.5
566    687.5
567    359.5
568    829.0
569    719.0
570    540.5
571    159.0
572    285.0
573    768.5
574    628.0
575    438.0
576    484.5
577    137.5
578    443.0
579    659.5
580    237.5
581     47.5
582    311.0
583    176.0
584    582.0
585     78.0
586    434.0
587     81.5
588    628.0
589    628.0
590    851.5
591     86.5
592    815.0
593    768.5
594    311.0
595    338.5
596    208.0
597    884.0
598    842.5
599    128.5
600    268.5
601    687.5
602    172.0
603    628.0
604    277.0
605    417.0
606    687.5
607    230.0
608    174.0
609     24.0
610    219.0
611    859.0
612    421.5
613    768.5
614    628.0
615    117.5
616    452.5
617    402.0
618    187.5
619    540.5
620    448.0
621    148.0
622    415.5
623    719.0
624    402.0
625    211.0
626    514.0
627     89.0
628    687.5
629    790.5
630    237.5
631    854.5
632    230.0
633    884.0
634    255.5
635    484.5
636    659.5
637    292.5
638    179.5
639    402.0
640    719.0
641    113.5
642    255.5
643    133.0
644    382.5
645     94.0
646    687.5
647    196.5
648    801.5
649    801.5
650    687.5
651    350.5
652    600.0
653    726.5
654    868.5
655    100.0
656    687.5
657    421.5
658    484.5
659     44.0
660     37.5
661    842.5
662    330.0
663    806.0
664    659.5
665    100.0
666    484.5
667    743.5
668    628.0
669    153.0
670    187.5
671    153.0
672    540.5
673    484.5
674    884.0
675    743.5
676    628.0
677    557.0
678    168.5
679      2.0
680    605.0
681     94.0
682    576.5
683    168.5
684    187.5
685    174.0
686    179.5
687    555.0
688    731.5
689     19.0
690    126.5
691    463.0
692    133.0
693    842.5
694    277.0
695    460.5
696    628.0
697    790.5
698     47.5
699    796.5
700     13.5
701    287.0
702    448.0
703    786.0
704    719.0
705    311.0
706    460.5
707    287.0
708     27.5
709    428.0
710    162.5
711    277.0
712    153.0
713    572.0
714    484.5
715    796.5
716     13.5
717    540.5
718    421.5
719    743.5
720    208.0
721    854.5
722    484.5
723    484.5
724    144.0
725    590.0
726    364.5
727    787.5
728    311.0
729    659.5
730     19.0
731    385.5
732    884.0
733    484.5
734    484.5
735    402.0
736    202.5
737      2.0
738    687.5
739    687.5
740    237.5
741     84.5
742      8.5
743    402.0
744    659.5
745    104.5
746    373.5
747    484.5
748    144.0
749    768.5
750    350.5
751    510.5
752    567.0
753    687.5
754    117.5
755    438.0
756    731.5
757    520.5
758    628.0
759     65.0
760    438.0
761    851.5
762    829.0
763     40.5
764    743.5
765     89.0
766    183.5
767    768.5
768    338.5
769    602.0
770    567.0
771    719.0
772    540.5
773    842.5
774    350.5
775    768.5
776    768.5
777    510.5
778    787.5
779     19.0
780    829.0
781    126.5
782    237.5
783    345.5
784    859.0
785    815.0
786    806.0
787    246.0
788    368.5
789     81.5
790    768.5
791    311.0
792    109.0
793    226.5
794    687.5
795    484.5
796    327.5
797    583.0
798    829.0
799    338.5
800    484.5
801    292.5
802     40.5
803    598.0
804    864.5
805    743.5
806    884.0
807    743.5
808    484.5
809    144.0
810    707.0
811    338.5
812    540.5
813    219.0
814    628.0
815    884.0
816    659.5
817    191.5
818    872.0
819    255.5
820     54.5
821    590.0
822    884.0
823    510.5
824    179.5
825    866.0
826    133.0
827    191.5
828    768.5
829     75.5
830    448.0
831    388.0
832    829.0
833    719.0
834    603.0
835     70.0
836    590.0
837    628.0
838    133.0
839    242.0
840    659.5
841    540.5
842    224.0
843    873.0
844    590.0
845    801.5
846    109.0
847    687.5
848    208.0
849     62.5
850    219.0
851    743.5
852    428.0
853    185.0
854    311.0
855    574.5
856     21.5
857    277.0
858    382.5
859    829.0
860    454.0
861    520.5
862    327.5
863    109.0
864    484.5
865    484.5
866    457.0
867    160.0
868    567.0
869    526.0
870    687.5
871    148.0
872    875.0
873    579.5
874    343.5
875    842.5
876    556.0
877    687.5
878    687.5
879     70.0
880    311.0
881    687.5
882    528.0
883    540.5
884    859.0
885    246.0
886    484.5
887    237.5
888    345.5
889    237.5
890    768.5
Name: fare, dtype: float64

In [37]:
titanic["fare_rank"] = titanic.fare.rank(ascending = False, method="min")

In [38]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck,fare_rank
0,0,3,male,22.0,1,0,7.2500,S,NaN,809.0
1,1,1,female,38.0,1,0,71.2833,C,C,103.0
2,1,3,female,26.0,0,0,7.9250,S,NaN,651.0
3,1,1,female,35.0,1,0,53.1000,S,C,142.0
4,0,3,male,35.0,0,0,8.0500,S,NaN,607.0

In [39]:
titanic.sort_values("fare", ascending= False)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck,fare_rank
258,1,1,female,35.00,0,0,512.3292,C,NaN,1.0
737,1,1,male,35.00,0,0,512.3292,C,B,1.0
679,1,1,male,36.00,0,1,512.3292,C,B,1.0
88,1,1,female,23.00,3,2,263.0000,S,C,4.0
27,0,1,male,19.00,3,2,263.0000,S,C,4.0
341,1,1,female,24.00,3,2,263.0000,S,C,4.0
438,0,1,male,64.00,1,4,263.0000,S,C,4.0
311,1,1,female,18.00,2,2,262.3750,C,B,8.0
742,1,1,female,21.00,2,2,262.3750,C,B,8.0
118,0,1,male,24.00,0,1,247.5208,C,B,10.0
299,1,1,female,50.00,0,1,247.5208,C,B,10.0
557,0,1,male,NaN,0,0,227.5250,C,NaN,12.0
700,1,1,female,18.00,1,0,227.5250,C,C,12.0
380,1,1,female,42.00,0,0,227.5250,C,NaN,12.0
716,1,1,female,38.00,0,0,227.5250,C,C,12.0
527,0,1,male,NaN,0,0,221.7792,S,C,16.0
377,0,1,male,27.00,0,2,211.5000,C,C,17.0
730,1,1,female,29.00,0,0,211.3375,S,B,18.0
779,1,1,female,43.00,0,1,211.3375,S,B,18.0
689,1,1,female,15.00,0,1,211.3375,S,B,18.0
318,1,1,female,31.00,0,2,164.8667,S,C,21.0
856,1,1,female,45.00,1,1,164.8667,S,NaN,21.0
268,1,1,female,58.00,0,1,153.4625,S,C,23.0
332,0,1,male,38.00,0,1,153.4625,S,C,23.0
609,1,1,female,40.00,0,0,153.4625,S,C,23.0
498,0,1,female,25.00,1,2,151.5500,S,C,26.0
305,1,1,male,0.92,1,2,151.5500,S,C,26.0
297,0,1,female,2.00,1,2,151.5500,S,C,26.0
708,1,1,female,22.00,0,0,151.5500,S,NaN,26.0
195,1,1,female,58.00,0,0,146.5208,C,B,30.0
31,1,1,female,NaN,1,0,146.5208,C,B,30.0
373,0,1,male,22.00,0,0,135.6333,C,NaN,32.0
325,1,1,female,36.00,0,0,135.6333,C,C,32.0
269,1,1,female,35.00,0,0,135.6333,S,C,32.0
319,1,1,female,40.00,1,1,134.5000,C,E,35.0
337,1,1,female,41.00,0,0,134.5000,C,E,35.0
334,1,1,female,NaN,1,0,133.6500,S,NaN,37.0
660,1,1,male,50.00,2,0,133.6500,S,NaN,37.0
435,1,1,female,14.00,1,2,120.0000,S,B,39.0
802,1,1,male,11.00,1,2,120.0000,S,B,39.0
763,1,1,female,36.00,1,2,120.0000,S,B,39.0
390,1,1,male,36.00,1,2,120.0000,S,B,39.0
215,1,1,female,31.00,1,0,113.2750,C,D,43.0
659,0,1,male,58.00,0,2,113.2750,C,D,43.0
393,1,1,female,23.00,1,0,113.2750,C,D,43.0
581,1,1,female,39.00,1,1,110.8833,C,C,46.0
550,1,1,male,17.00,0,2,110.8833,C,C,46.0
698,0,1,male,49.00,1,1,110.8833,C,C,46.0
306,1,1,female,NaN,0,0,110.8833,C,NaN,46.0
307,1,1,female,17.00,1,0,108.9000,C,C,50.0
505,0,1,male,18.00,1,0,108.9000,C,C,50.0
544,0,1,male,50.00,1,0,106.4250,C,C,52.0
537,1,1,female,30.00,0,0,106.4250,C,NaN,52.0
820,1,1,female,52.00,1,1,93.5000,S,B,54.0
520,1,1,female,30.00,0,0,93.5000,S,B,54.0
291,1,1,female,19.00,1,0,91.0792,C,B,56.0
484,1,1,male,25.00,1,0,91.0792,C,B,56.0
486,1,1,female,35.00,1,0,90.0000,S,C,58.0
412,1,1,female,33.00,1,0,90.0000,Q,C,58.0
245,0,1,male,44.00,2,0,90.0000,Q,C,58.0
224,1,1,male,38.00,1,0,90.0000,S,C,58.0
849,1,1,female,NaN,1,0,89.1042,C,C,62.0
453,1,1,male,49.00,1,0,89.1042,C,C,62.0
504,1,1,female,16.00,0,0,86.5000,S,B,64.0
257,1,1,female,30.00,0,0,86.5000,S,B,64.0
759,1,1,female,33.00,0,0,86.5000,S,B,64.0
62,0,1,male,45.00,1,0,83.4750,S,C,67.0
230,1,1,female,35.00,1,0,83.4750,S,C,67.0
879,1,1,female,56.00,0,1,83.1583,C,C,69.0
835,1,1,female,39.00,1,1,83.1583,C,E,69.0
310,1,1,female,24.00,0,0,83.1583,C,C,69.0
375,1,1,female,NaN,1,0,82.1708,C,NaN,72.0
34,0,1,male,28.00,1,0,82.1708,C,NaN,72.0
445,1,1,male,4.00,0,2,81.8583,S,A,74.0
829,1,1,female,62.00,0,0,80.0000,NaN,B,75.0
61,1,1,female,38.00,0,0,80.0000,NaN,B,75.0
558,1,1,female,39.00,1,1,79.6500,S,E,77.0
262,0,1,male,52.00,1,1,79.6500,S,E,77.0
585,1,1,female,18.00,0,2,79.6500,S,E,77.0
256,1,1,female,NaN,0,0,79.2000,C,NaN,80.0
139,0,1,male,24.00,0,0,79.2000,C,B,80.0
789,0,1,male,46.00,0,0,79.2000,C,B,80.0
587,1,1,male,60.00,1,1,79.2000,C,B,80.0
741,0,1,male,36.00,1,0,78.8500,S,C,84.0
290,1,1,female,26.00,0,0,78.8500,S,NaN,84.0
496,1,1,female,54.00,1,0,78.2667,C,D,86.0
591,1,1,female,52.00,1,0,78.2667,C,D,86.0
627,1,1,female,21.00,0,0,77.9583,S,D,88.0
275,1,1,female,63.00,1,0,77.9583,S,D,88.0
765,1,1,female,51.00,1,0,77.9583,S,D,88.0
102,0,1,male,21.00,0,1,77.2875,S,D,91.0
124,0,1,male,54.00,0,1,77.2875,S,D,91.0
52,1,1,female,49.00,1,0,76.7292,C,D,93.0
681,1,1,male,27.00,0,0,76.7292,C,D,93.0
645,1,1,male,48.00,1,0,76.7292,C,D,93.0
218,1,1,female,32.00,0,0,76.2917,C,D,96.0
366,1,1,female,60.00,1,0,75.2500,C,D,97.0
655,0,2,male,24.00,2,0,73.5000,S,NaN,98.0
385,0,2,male,18.00,0,0,73.5000,S,NaN,98.0
72,0,2,male,21.00,0,0,73.5000,S,NaN,98.0
665,0,2,male,32.00,2,0,73.5000,S,NaN,98.0
120,0,2,male,21.00,2,0,73.5000,S,NaN,98.0
1,1,1,female,38.00,1,0,71.2833,C,C,103.0
540,1,1,female,36.00,0,2,71.0000,S,B,104.0
745,0,1,male,70.00,1,1,71.0000,S,B,104.0
863,0,3,female,NaN,8,2,69.5500,S,NaN,106.0
324,0,3,male,NaN,8,2,69.5500,S,NaN,106.0
180,0,3,female,NaN,8,2,69.5500,S,NaN,106.0
201,0,3,male,NaN,8,2,69.5500,S,NaN,106.0
159,0,3,male,NaN,8,2,69.5500,S,NaN,106.0
792,0,3,female,NaN,8,2,69.5500,S,NaN,106.0
846,0,3,male,NaN,8,2,69.5500,S,NaN,106.0
369,1,1,female,24.00,0,0,69.3000,C,B,113.0
641,1,1,female,24.00,0,0,69.3000,C,B,113.0
151,1,1,female,22.00,1,0,66.6000,S,C,115.0
336,0,1,male,29.00,1,0,66.6000,S,C,115.0
754,1,2,female,48.00,1,2,65.0000,S,NaN,117.0
615,1,2,female,24.00,1,2,65.0000,S,NaN,117.0
97,1,1,male,23.00,0,1,63.3583,C,D,119.0
54,0,1,male,65.00,0,1,61.9792,C,B,120.0
155,0,1,male,51.00,0,1,61.3792,C,NaN,121.0
92,0,1,male,46.00,1,0,61.1750,S,E,122.0
513,1,1,female,54.00,1,0,59.4000,C,NaN,123.0
523,1,1,female,44.00,0,1,57.9792,C,B,124.0
329,1,1,female,16.00,0,1,57.9792,C,B,124.0
781,1,1,female,17.00,1,0,57.0000,S,B,126.0
690,1,1,male,31.00,1,0,57.0000,S,B,126.0
599,1,1,male,49.00,1,0,56.9292,C,A,128.0
309,1,1,female,30.00,0,0,56.9292,C,E,128.0
169,0,3,male,28.00,0,0,56.4958,S,NaN,130.0
838,1,3,male,32.00,0,0,56.4958,S,NaN,130.0
692,1,3,male,NaN,0,0,56.4958,S,NaN,130.0
74,1,3,male,32.00,0,0,56.4958,S,NaN,130.0
643,1,3,male,NaN,0,0,56.4958,S,NaN,130.0
826,0,3,male,NaN,0,0,56.4958,S,NaN,130.0
509,1,3,male,26.00,0,0,56.4958,S,NaN,130.0
577,1,1,female,39.00,1,0,55.9000,S,E,137.0
434,0,1,male,50.00,1,0,55.9000,S,E,137.0
370,1,1,male,25.00,1,0,55.4417,C,E,139.0
166,1,1,female,NaN,0,1,55.0000,S,E,140.0
356,1,1,female,22.00,0,1,55.0000,S,E,140.0
809,1,1,female,33.00,1,0,53.1000,S,E,142.0
748,0,1,male,19.00,1,0,53.1000,S,D,142.0
137,0,1,male,37.00,1,0,53.1000,S,C,142.0
724,1,1,male,27.00,1,0,53.1000,S,E,142.0
3,1,1,female,35.00,1,0,53.1000,S,C,142.0
871,1,1,female,47.00,1,1,52.5542,S,D,147.0
621,1,1,male,42.00,1,0,52.5542,S,D,147.0
248,1,1,male,37.00,1,1,52.5542,S,D,147.0
669,1,1,female,NaN,1,0,52.0000,S,C,150.0
383,1,1,female,35.00,1,0,52.0000,S,NaN,150.0
671,0,1,male,31.00,1,0,52.0000,S,B,150.0
712,1,1,male,48.00,1,0,52.0000,S,C,150.0
35,0,1,male,42.00,1,0,52.0000,S,NaN,150.0
475,0,1,male,NaN,0,0,52.0000,S,A,150.0
110,0,1,male,47.00,0,0,52.0000,S,C,150.0
6,0,1,male,54.00,0,0,51.8625,S,E,157.0
457,1,1,female,NaN,1,0,51.8625,S,D,157.0
571,1,1,female,53.00,2,0,51.4792,S,C,159.0
867,0,1,male,31.00,0,0,50.4958,S,A,160.0
185,0,1,male,NaN,0,0,50.0000,S,A,161.0
493,0,1,male,71.00,0,0,49.5042,C,NaN,162.0
710,1,1,female,24.00,0,0,49.5042,C,C,162.0
539,1,1,female,22.00,0,2,49.5000,C,B,164.0
83,0,1,male,28.00,0,0,47.1000,S,NaN,165.0
71,0,3,female,16.00,5,2,46.9000,S,NaN,166.0
386,0,3,male,1.00,5,2,46.9000,S,NaN,166.0
480,0,3,male,9.00,5,2,46.9000,S,NaN,166.0
678,0,3,female,43.00,1,6,46.9000,S,NaN,166.0
683,0,3,male,14.00,5,2,46.9000,S,NaN,166.0
59,0,3,male,11.00,5,2,46.9000,S,NaN,166.0
602,0,1,male,NaN,0,0,42.4000,S,NaN,172.0
608,1,2,female,22.00,1,2,41.5792,C,NaN,173.0
685,0,2,male,25.00,1,2,41.5792,C,NaN,173.0
43,1,2,female,3.00,1,2,41.5792,C,NaN,173.0
583,0,1,male,36.00,0,0,40.1250,C,A,176.0
686,0,3,male,14.00,4,1,39.6875,S,NaN,177.0
266,0,3,male,16.00,4,1,39.6875,S,NaN,177.0
638,0,3,female,41.00,0,5,39.6875,S,NaN,177.0
164,0,3,male,1.00,4,1,39.6875,S,NaN,177.0
824,0,3,male,2.00,4,1,39.6875,S,NaN,177.0
50,0,3,male,7.00,4,1,39.6875,S,NaN,177.0
766,0,1,male,NaN,0,0,39.6000,C,NaN,183.0
556,1,1,female,48.00,1,0,39.6000,C,A,183.0
853,1,1,female,16.00,0,1,39.4000,S,D,185.0
670,1,2,female,40.00,1,1,39.0000,S,NaN,186.0
684,0,2,male,60.00,1,1,39.0000,S,NaN,186.0
183,1,2,male,1.00,2,1,39.0000,S,F,186.0
618,1,2,female,4.00,2,1,39.0000,S,F,186.0
462,0,1,male,47.00,0,0,38.5000,S,E,190.0
817,0,2,male,31.00,1,1,37.0042,C,NaN,191.0
827,1,2,male,1.00,0,2,37.0042,C,NaN,191.0
145,0,2,male,19.00,1,1,36.7500,S,NaN,193.0
549,1,2,male,8.00,1,1,36.7500,S,NaN,193.0
647,1,1,male,56.00,0,0,35.5000,C,A,195.0
339,0,1,male,45.00,0,0,35.5000,S,NaN,195.0
55,1,1,male,NaN,0,0,35.5000,S,C,195.0
23,1,1,male,28.00,0,0,35.5000,S,A,195.0
351,0,1,male,NaN,0,0,35.0000,S,C,199.0
96,0,1,male,71.00,0,0,34.6542,C,A,200.0
86,0,3,male,16.00,1,3,34.3750,S,NaN,201.0
436,0,3,female,21.00,2,2,34.3750,S,NaN,201.0
736,0,3,female,48.00,1,3,34.3750,S,NaN,201.0
147,0,3,female,9.00,2,2,34.3750,S,NaN,201.0
515,0,1,male,47.00,0,0,34.0208,S,D,205.0
170,0,1,male,61.00,0,0,33.5000,S,B,206.0
848,0,2,male,28.00,0,1,33.0000,S,NaN,207.0
720,1,2,female,6.00,0,1,33.0000,S,NaN,207.0
596,1,2,female,NaN,0,0,33.0000,S,NaN,207.0
416,1,2,female,34.00,1,1,32.5000,S,NaN,210.0
625,0,1,male,61.00,0,0,32.3208,S,D,211.0
25,1,3,female,38.00,1,5,31.3875,S,NaN,212.0
182,0,3,male,9.00,4,2,31.3875,S,NaN,212.0
233,1,3,female,5.00,4,2,31.3875,S,NaN,212.0
261,1,3,male,3.00,4,2,31.3875,S,NaN,212.0
813,0,3,female,6.00,4,2,31.2750,S,NaN,216.0
13,0,3,male,39.00,1,5,31.2750,S,NaN,216.0
119,0,3,female,2.00,4,2,31.2750,S,NaN,216.0
610,0,3,female,39.00,1,5,31.2750,S,NaN,216.0
850,0,3,male,4.00,4,2,31.2750,S,NaN,216.0
542,0,3,female,11.00,4,2,31.2750,S,NaN,216.0
541,0,3,female,9.00,4,2,31.2750,S,NaN,216.0
270,0,1,male,NaN,0,0,31.0000,S,NaN,223.0
209,1,1,male,40.00,0,0,31.0000,C,A,223.0
842,1,1,female,30.00,0,0,31.0000,C,NaN,223.0
793,0,1,male,NaN,0,0,30.6958,C,NaN,226.0
174,0,1,male,56.00,0,0,30.6958,C,A,226.0
492,0,1,male,55.00,0,0,30.5000,S,C,228.0
607,1,1,male,27.00,0,0,30.5000,S,NaN,228.0
449,1,1,male,52.00,0,0,30.5000,S,C,228.0
298,1,1,male,NaN,0,0,30.5000,S,C,228.0
632,1,1,male,32.00,0,0,30.5000,C,B,228.0
122,0,2,male,32.50,1,0,30.0708,C,NaN,233.0
9,1,2,female,14.00,1,0,30.0708,C,NaN,233.0
740,1,1,male,NaN,0,0,30.0000,S,D,235.0
889,1,1,male,26.00,0,0,30.0000,C,C,235.0
580,1,2,female,25.00,1,1,30.0000,S,NaN,235.0
782,0,1,male,29.00,0,0,30.0000,S,D,235.0
630,1,1,male,80.00,0,0,30.0000,S,A,235.0
887,1,1,female,19.00,0,0,30.0000,S,B,235.0
839,1,1,male,NaN,0,0,29.7000,C,C,241.0
487,0,1,male,58.00,0,0,29.7000,C,B,241.0
273,0,1,male,37.00,0,1,29.7000,C,C,241.0
16,0,3,male,2.00,4,1,29.1250,Q,NaN,244.0
885,0,3,female,39.00,0,5,29.1250,Q,NaN,244.0
787,0,3,male,8.00,4,1,29.1250,Q,NaN,244.0
171,0,3,male,4.00,4,1,29.1250,Q,NaN,244.0
278,0,3,male,7.00,4,1,29.1250,Q,NaN,244.0
78,1,2,male,0.83,0,2,29.0000,S,NaN,249.0
323,1,2,female,22.00,1,1,29.0000,S,NaN,249.0
177,0,1,female,50.00,0,0,28.7125,C,C,251.0
331,0,1,male,45.50,0,0,28.5000,S,C,252.0
360,0,3,male,40.00,1,4,27.9000,S,NaN,253.0
642,0,3,female,2.00,3,2,27.9000,S,NaN,253.0
63,0,3,male,4.00,3,2,27.9000,S,NaN,253.0
819,0,3,male,10.00,3,2,27.9000,S,NaN,253.0
634,0,3,female,9.00,3,2,27.9000,S,NaN,253.0
167,0,3,female,45.00,1,4,27.9000,S,NaN,253.0
472,1,2,female,33.00,1,2,27.7500,S,NaN,259.0
450,0,2,male,36.00,1,2,27.7500,S,NaN,259.0
452,0,1,male,30.00,0,0,27.7500,C,C,259.0
58,1,2,female,5.00,1,2,27.7500,S,NaN,259.0
361,0,2,male,29.00,1,0,27.7208,C,NaN,263.0
194,1,1,female,44.00,0,0,27.7208,C,B,263.0
295,0,1,male,NaN,0,0,27.7208,C,NaN,263.0
64,0,1,male,NaN,0,0,27.7208,C,NaN,263.0
30,0,1,male,40.00,0,0,27.7208,C,NaN,263.0
217,0,2,male,42.00,1,0,27.0000,S,NaN,268.0
600,1,2,female,24.00,2,1,27.0000,S,NaN,268.0
507,1,1,male,NaN,0,0,26.5500,S,NaN,270.0
467,0,1,male,56.00,0,0,26.5500,S,NaN,270.0
430,1,1,male,28.00,0,0,26.5500,S,C,270.0
711,0,1,male,NaN,0,0,26.5500,S,C,270.0
460,1,1,male,48.00,0,0,26.5500,S,E,270.0
456,0,1,male,65.00,0,0,26.5500,S,E,270.0
187,1,1,male,45.00,0,0,26.5500,S,NaN,270.0
11,1,1,female,58.00,0,0,26.5500,S,C,270.0
447,1,1,male,34.00,0,0,26.5500,S,NaN,270.0
555,0,1,male,62.00,0,0,26.5500,S,NaN,270.0
857,1,1,male,51.00,0,0,26.5500,S,E,270.0
694,0,1,male,60.00,0,0,26.5500,S,NaN,270.0
536,0,1,male,45.00,0,0,26.5500,S,B,270.0
252,0,1,male,62.00,0,0,26.5500,S,C,270.0
604,1,1,male,35.00,0,0,26.5500,C,NaN,270.0
572,1,1,male,36.00,0,0,26.3875,S,E,285.0
707,1,1,male,42.00,0,0,26.2875,S,E,286.0
512,1,1,male,36.00,0,0,26.2875,S,E,286.0
701,1,1,male,35.00,0,0,26.2875,S,E,286.0
136,1,1,female,19.00,0,2,26.2833,S,D,289.0
237,1,2,female,8.00,0,2,26.2500,S,NaN,290.0
801,1,2,female,31.00,1,1,26.2500,S,NaN,290.0
535,1,2,female,7.00,0,2,26.2500,S,NaN,290.0
314,0,2,male,43.00,1,1,26.2500,S,NaN,290.0
440,1,2,female,45.00,1,1,26.2500,S,NaN,290.0
637,0,2,male,31.00,1,1,26.2500,S,NaN,290.0
705,0,2,male,39.00,0,0,26.0000,S,NaN,296.0
316,1,2,female,24.00,1,0,26.0000,S,NaN,296.0
312,0,2,female,26.00,1,1,26.0000,S,NaN,296.0
426,1,2,female,28.00,1,0,26.0000,S,NaN,296.0
530,1,2,female,2.00,1,1,26.0000,S,NaN,296.0
148,0,2,male,36.50,0,2,26.0000,S,F,296.0
551,0,2,male,27.00,0,0,26.0000,S,NaN,296.0
133,1,2,female,29.00,1,0,26.0000,S,NaN,296.0
791,0,2,male,16.00,0,0,26.0000,S,NaN,296.0
20,0,2,male,35.00,0,0,26.0000,S,NaN,296.0
543,1,2,male,32.00,1,0,26.0000,S,NaN,296.0
397,0,2,male,46.00,0,0,26.0000,S,NaN,296.0
545,0,1,male,64.00,0,0,26.0000,S,NaN,296.0
340,1,2,male,2.00,1,1,26.0000,S,F,296.0
427,1,2,female,19.00,0,0,26.0000,S,NaN,296.0
99,0,2,male,34.00,1,0,26.0000,S,NaN,296.0
432,1,2,female,42.00,1,0,26.0000,S,NaN,296.0
284,0,1,male,NaN,0,0,26.0000,S,A,296.0
249,0,2,male,54.00,1,0,26.0000,S,NaN,296.0
854,0,2,female,44.00,1,0,26.0000,S,NaN,296.0
193,1,2,male,3.00,1,1,26.0000,S,F,296.0
594,0,2,male,37.00,1,0,26.0000,S,NaN,296.0
880,1,2,female,25.00,0,1,26.0000,S,NaN,296.0
728,0,2,male,25.00,1,0,26.0000,S,NaN,296.0
259,1,2,female,50.00,0,1,26.0000,S,NaN,296.0
236,0,2,male,44.00,1,0,26.0000,S,NaN,296.0
506,1,2,female,33.00,0,2,26.0000,S,NaN,296.0
582,0,2,male,54.00,0,0,26.0000,S,NaN,296.0
518,1,2,female,36.00,1,0,26.0000,S,NaN,296.0
53,1,2,female,29.00,1,0,26.0000,S,NaN,296.0
546,1,2,female,19.00,1,0,26.0000,S,NaN,296.0
796,1,1,female,49.00,0,0,25.9292,S,D,327.0
862,1,1,female,48.00,0,0,25.9292,S,D,327.0
168,0,1,male,NaN,0,0,25.9250,S,NaN,329.0
662,0,1,male,47.00,0,0,25.5875,S,E,330.0
409,0,3,female,NaN,3,1,25.4667,S,NaN,331.0
229,0,3,female,NaN,3,1,25.4667,S,NaN,331.0
176,0,3,male,NaN,3,1,25.4667,S,NaN,331.0
485,0,3,female,NaN,3,1,25.4667,S,NaN,331.0
799,0,3,female,30.00,1,1,24.1500,S,NaN,335.0
109,1,3,female,NaN,1,0,24.1500,Q,NaN,335.0
811,0,3,male,39.00,0,0,24.1500,S,NaN,335.0
419,0,3,female,10.00,0,2,24.1500,S,NaN,335.0
768,0,3,male,NaN,1,0,24.1500,Q,NaN,335.0
595,0,3,male,36.00,1,1,24.1500,S,NaN,335.0
565,0,3,male,24.00,2,0,24.1500,S,NaN,335.0
517,0,3,male,NaN,0,0,24.1500,Q,NaN,335.0
874,1,2,female,28.00,1,0,24.0000,C,NaN,343.0
308,0,2,male,30.00,1,0,24.0000,C,NaN,343.0
783,0,3,male,NaN,1,2,23.4500,S,NaN,345.0
888,0,3,female,NaN,1,2,23.4500,S,NaN,345.0
330,1,3,female,NaN,2,0,23.2500,Q,NaN,347.0
301,1,3,male,NaN,2,0,23.2500,Q,NaN,347.0
651,1,2,female,18.00,0,1,23.0000,S,NaN,349.0
750,1,2,female,4.00,1,1,23.0000,S,NaN,349.0
774,1,2,female,54.00,1,3,23.0000,S,NaN,349.0
98,1,2,female,34.00,0,1,23.0000,S,NaN,349.0
508,0,3,male,28.00,0,0,22.5250,S,NaN,353.0
128,1,3,female,NaN,1,1,22.3583,C,F,354.0
533,1,3,female,NaN,0,2,22.3583,C,NaN,354.0
184,1,3,female,4.00,0,2,22.0250,S,NaN,356.0
48,0,3,male,NaN,2,0,21.6792,C,NaN,357.0
567,0,3,female,29.00,0,4,21.0750,S,NaN,358.0
374,0,3,female,3.00,3,1,21.0750,S,NaN,358.0
7,0,3,male,2.00,3,1,21.0750,S,NaN,358.0
24,0,3,female,8.00,3,1,21.0750,S,NaN,358.0
476,0,2,male,34.00,1,0,21.0000,S,NaN,362.0
211,1,2,female,35.00,0,0,21.0000,S,NaN,362.0
405,0,2,male,34.00,1,0,21.0000,S,NaN,362.0
726,1,2,female,30.00,3,0,21.0000,S,NaN,362.0
117,0,2,male,29.00,1,0,21.0000,S,NaN,362.0
41,0,2,female,27.00,1,0,21.0000,S,NaN,362.0
788,1,3,male,1.00,1,2,20.5750,S,NaN,368.0
93,0,3,male,26.00,1,2,20.5750,S,NaN,368.0
165,1,3,male,9.00,0,2,20.5250,S,NaN,370.0
328,1,3,female,31.00,1,1,20.5250,S,NaN,370.0
548,0,3,male,33.00,1,1,20.5250,S,NaN,370.0
746,0,3,male,16.00,1,1,20.2500,S,NaN,373.0
279,1,3,female,35.00,1,1,20.2500,S,NaN,373.0
254,0,3,female,41.00,0,2,20.2125,S,NaN,375.0
424,0,3,male,18.00,1,1,20.2125,S,NaN,375.0
490,0,3,male,NaN,1,0,19.9667,S,NaN,377.0
451,0,3,male,NaN,1,0,19.9667,S,NaN,377.0
446,1,2,female,13.00,0,1,19.5000,S,NaN,379.0
272,1,2,female,41.00,0,1,19.5000,S,NaN,379.0
858,1,3,female,24.00,0,3,19.2583,C,NaN,381.0
644,1,3,female,0.75,2,1,19.2583,C,NaN,381.0
469,1,3,female,0.75,2,1,19.2583,C,NaN,381.0
448,1,3,female,5.00,2,1,19.2583,C,NaN,381.0
207,1,3,male,26.00,0,0,18.7875,C,NaN,385.0
731,0,3,male,11.00,0,0,18.7875,C,NaN,385.0
831,1,2,male,0.83,1,1,18.7500,S,NaN,387.0
407,1,2,male,3.00,1,1,18.7500,S,NaN,387.0
437,1,2,female,24.00,2,3,18.7500,S,NaN,387.0
333,0,3,male,16.00,2,0,18.0000,S,NaN,390.0
18,0,3,female,31.00,1,0,18.0000,S,NaN,390.0
38,0,3,female,18.00,2,0,18.0000,S,NaN,390.0
353,0,3,male,25.00,1,0,17.8000,S,NaN,393.0
49,0,3,female,18.00,1,0,17.8000,S,NaN,393.0
559,1,3,female,36.00,1,0,17.4000,S,NaN,395.0
10,1,3,female,4.00,1,1,16.7000,S,G,396.0
394,1,3,female,24.00,0,2,16.7000,S,G,396.0
431,1,3,female,NaN,1,0,16.1000,S,NaN,398.0
347,1,3,female,NaN,1,0,16.1000,S,NaN,398.0
617,0,3,female,26.00,1,0,16.1000,S,NaN,398.0
639,0,3,male,NaN,1,0,16.1000,S,NaN,398.0
160,0,3,male,44.00,0,1,16.1000,S,NaN,398.0
253,0,3,male,30.00,1,0,16.1000,S,NaN,398.0
624,0,3,male,21.00,0,0,16.1000,S,NaN,398.0
743,0,3,male,24.00,1,0,16.1000,S,NaN,398.0
735,0,3,male,28.50,0,0,16.1000,S,NaN,398.0
15,1,2,female,55.00,0,0,16.0000,S,NaN,407.0
489,1,3,male,9.00,1,1,15.9000,S,NaN,408.0
348,1,3,male,3.00,1,1,15.9000,S,NaN,408.0
206,0,3,male,32.00,1,0,15.8500,S,NaN,410.0
142,1,3,female,24.00,1,0,15.8500,S,NaN,410.0
85,1,3,female,33.00,3,0,15.8500,S,NaN,410.0
403,0,3,male,28.00,1,0,15.8500,S,NaN,410.0
161,1,2,female,40.00,0,0,15.7500,S,NaN,414.0
622,1,3,male,20.00,1,1,15.7417,C,NaN,415.0
381,1,3,female,1.00,0,2,15.7417,C,NaN,415.0
605,0,3,male,36.00,1,0,15.5500,S,NaN,417.0
241,1,3,female,NaN,1,0,15.5000,Q,NaN,418.0
612,1,3,female,NaN,1,0,15.5000,Q,NaN,418.0
718,0,3,male,NaN,0,0,15.5000,Q,NaN,418.0
186,1,3,female,NaN,1,0,15.5000,Q,NaN,418.0
657,0,3,female,32.00,1,1,15.5000,Q,NaN,418.0
364,0,3,male,NaN,1,0,15.5000,Q,NaN,418.0
188,0,3,male,40.00,1,1,15.5000,Q,NaN,418.0
46,0,3,male,NaN,1,0,15.5000,Q,NaN,418.0
140,0,3,female,NaN,0,2,15.2458,C,NaN,426.0
65,1,3,male,NaN,1,1,15.2458,C,NaN,426.0
852,0,3,female,9.00,1,1,15.2458,C,NaN,426.0
255,1,3,female,29.00,0,2,15.2458,C,NaN,426.0
709,1,3,male,NaN,1,1,15.2458,C,NaN,426.0
497,0,3,male,NaN,0,0,15.1000,S,NaN,431.0
181,0,2,male,NaN,0,0,15.0500,C,NaN,432.0
135,0,2,male,23.00,0,0,15.0458,C,NaN,433.0
586,0,2,male,47.00,0,0,15.0000,S,NaN,434.0
755,1,2,male,0.67,1,1,14.5000,S,NaN,435.0
575,0,3,male,19.00,0,0,14.5000,S,NaN,435.0
247,1,2,female,24.00,0,2,14.5000,S,NaN,435.0
538,0,3,male,NaN,0,0,14.5000,S,NaN,435.0
760,0,3,male,NaN,0,0,14.5000,S,NaN,435.0
153,0,3,male,40.50,0,2,14.5000,S,NaN,435.0
132,0,3,female,47.00,1,0,14.5000,S,NaN,435.0
495,0,3,male,NaN,0,0,14.4583,C,NaN,442.0
114,0,3,female,17.00,0,0,14.4583,C,NaN,442.0
578,0,3,female,NaN,1,0,14.4583,C,NaN,442.0
620,0,3,male,27.00,1,0,14.4542,C,NaN,445.0
830,1,3,female,15.00,1,0,14.4542,C,NaN,445.0
362,0,3,female,45.00,0,1,14.4542,C,NaN,445.0
73,0,3,male,26.00,1,0,14.4542,C,NaN,445.0
111,0,3,female,14.50,1,0,14.4542,C,NaN,445.0
240,0,3,female,NaN,1,0,14.4542,C,NaN,445.0
702,0,3,female,18.00,0,1,14.4542,C,NaN,445.0
616,0,3,male,34.00,1,1,14.4000,S,NaN,452.0
423,0,3,female,28.00,1,1,14.4000,S,NaN,452.0
860,0,3,male,41.00,2,0,14.1083,S,NaN,454.0
317,0,2,male,54.00,0,0,14.0000,S,NaN,455.0
547,1,2,male,NaN,0,0,13.8625,C,NaN,456.0
866,1,2,female,27.00,1,0,13.8583,C,NaN,457.0
473,1,2,female,23.00,0,0,13.7917,C,D,458.0
562,0,2,male,28.00,0,0,13.5000,S,NaN,459.0
695,0,2,male,52.00,0,0,13.5000,S,NaN,459.0
232,0,2,male,59.00,0,0,13.5000,S,NaN,459.0
706,1,2,female,45.00,0,0,13.5000,S,NaN,459.0
691,1,3,female,4.00,0,1,13.4167,C,NaN,463.0
733,0,2,male,23.00,0,0,13.0000,S,NaN,464.0
800,0,2,male,34.00,0,0,13.0000,S,NaN,464.0
191,0,2,male,19.00,0,0,13.0000,S,NaN,464.0
865,1,2,female,42.00,0,0,13.0000,S,NaN,464.0
734,0,2,male,23.00,0,0,13.0000,S,NaN,464.0
221,0,2,male,27.00,0,0,13.0000,S,NaN,464.0

In [40]:
titanic.drop(columns = "fare_rank", inplace= True)

In [41]:
titanic

     survived  pclass     sex    age  sibsp  parch      fare embarked deck
0           0       3    male  22.00      1      0    7.2500        S  NaN
1           1       1  female  38.00      1      0   71.2833        C    C
2           1       3  female  26.00      0      0    7.9250        S  NaN
3           1       1  female  35.00      1      0   53.1000        S    C
4           0       3    male  35.00      0      0    8.0500        S  NaN
5           0       3    male    NaN      0      0    8.4583        Q  NaN
6           0       1    male  54.00      0      0   51.8625        S    E
7           0       3    male   2.00      3      1   21.0750        S  NaN
8           1       3  female  27.00      0      2   11.1333        S  NaN
9           1       2  female  14.00      1      0   30.0708        C  NaN
10          1       3  female   4.00      1      1   16.7000        S    G
11          1       1  female  58.00      0      0   26.5500        S    C
12          0       3    male  20.00      0      0    8.0500        S  NaN
13          0       3    male  39.00      1      5   31.2750        S  NaN
14          0       3  female  14.00      0      0    7.8542        S  NaN
15          1       2  female  55.00      0      0   16.0000        S  NaN
16          0       3    male   2.00      4      1   29.1250        Q  NaN
17          1       2    male    NaN      0      0   13.0000        S  NaN
18          0       3  female  31.00      1      0   18.0000        S  NaN
19          1       3  female    NaN      0      0    7.2250        C  NaN
20          0       2    male  35.00      0      0   26.0000        S  NaN
21          1       2    male  34.00      0      0   13.0000        S    D
22          1       3  female  15.00      0      0    8.0292        Q  NaN
23          1       1    male  28.00      0      0   35.5000        S    A
24          0       3  female   8.00      3      1   21.0750        S  NaN
25          1       3  female  38.00      1      5   31.3875        S  NaN
26          0       3    male    NaN      0      0    7.2250        C  NaN
27          0       1    male  19.00      3      2  263.0000        S    C
28          1       3  female    NaN      0      0    7.8792        Q  NaN
29          0       3    male    NaN      0      0    7.8958        S  NaN
30          0       1    male  40.00      0      0   27.7208        C  NaN
31          1       1  female    NaN      1      0  146.5208        C    B
32          1       3  female    NaN      0      0    7.7500        Q  NaN
33          0       2    male  66.00      0      0   10.5000        S  NaN
34          0       1    male  28.00      1      0   82.1708        C  NaN
35          0       1    male  42.00      1      0   52.0000        S  NaN
36          1       3    male    NaN      0      0    7.2292        C  NaN
37          0       3    male  21.00      0      0    8.0500        S  NaN
38          0       3  female  18.00      2      0   18.0000        S  NaN
39          1       3  female  14.00      1      0   11.2417        C  NaN
40          0       3  female  40.00      1      0    9.4750        S  NaN
41          0       2  female  27.00      1      0   21.0000        S  NaN
42          0       3    male    NaN      0      0    7.8958        C  NaN
43          1       2  female   3.00      1      2   41.5792        C  NaN
44          1       3  female  19.00      0      0    7.8792        Q  NaN
45          0       3    male    NaN      0      0    8.0500        S  NaN
46          0       3    male    NaN      1      0   15.5000        Q  NaN
47          1       3  female    NaN      0      0    7.7500        Q  NaN
48          0       3    male    NaN      2      0   21.6792        C  NaN
49          0       3  female  18.00      1      0   17.8000        S  NaN
50          0       3    male   7.00      4      1   39.6875        S  NaN
51          0       3    male  21.00      0      0    7.8000        S  NaN
52          1       1  female  49.00      1      0   76.7292        C    D
53          1       2  female  29.00      1      0   26.0000        S  NaN
54          0       1    male  65.00      0      1   61.9792        C    B
55          1       1    male    NaN      0      0   35.5000        S    C
56          1       2  female  21.00      0      0   10.5000        S  NaN
57          0       3    male  28.50      0      0    7.2292        C  NaN
58          1       2  female   5.00      1      2   27.7500        S  NaN
59          0       3    male  11.00      5      2   46.9000        S  NaN
60          0       3    male  22.00      0      0    7.2292        C  NaN
61          1       1  female  38.00      0      0   80.0000      NaN    B
62          0       1    male  45.00      1      0   83.4750        S    C
63          0       3    male   4.00      3      2   27.9000        S  NaN
64          0       1    male    NaN      0      0   27.7208        C  NaN
65          1       3    male    NaN      1      1   15.2458        C  NaN
66          1       2  female  29.00      0      0   10.5000        S    F
67          0       3    male  19.00      0      0    8.1583        S  NaN
68          1       3  female  17.00      4      2    7.9250        S  NaN
69          0       3    male  26.00      2      0    8.6625        S  NaN
70          0       2    male  32.00      0      0   10.5000        S  NaN
71          0       3  female  16.00      5      2   46.9000        S  NaN
72          0       2    male  21.00      0      0   73.5000        S  NaN
73          0       3    male  26.00      1      0   14.4542        C  NaN
74          1       3    male  32.00      0      0   56.4958        S  NaN
75          0       3    male  25.00      0      0    7.6500        S    F
76          0       3    male    NaN      0      0    7.8958        S  NaN
77          0       3    male    NaN      0      0    8.0500        S  NaN
78          1       2    male   0.83      0      2   29.0000        S  NaN
79          1       3  female  30.00      0      0   12.4750        S  NaN
80          0       3    male  22.00      0      0    9.0000        S  NaN
81          1       3    male  29.00      0      0    9.5000        S  NaN
82          1       3  female    NaN      0      0    7.7875        Q  NaN
83          0       1    male  28.00      0      0   47.1000        S  NaN
84          1       2  female  17.00      0      0   10.5000        S  NaN
85          1       3  female  33.00      3      0   15.8500        S  NaN
86          0       3    male  16.00      1      3   34.3750        S  NaN
87          0       3    male    NaN      0      0    8.0500        S  NaN
88          1       1  female  23.00      3      2  263.0000        S    C
89          0       3    male  24.00      0      0    8.0500        S  NaN
90          0       3    male  29.00      0      0    8.0500        S  NaN
91          0       3    male  20.00      0      0    7.8542        S  NaN
92          0       1    male  46.00      1      0   61.1750        S    E
93          0       3    male  26.00      1      2   20.5750        S  NaN
94          0       3    male  59.00      0      0    7.2500        S  NaN
95          0       3    male    NaN      0      0    8.0500        S  NaN
96          0       1    male  71.00      0      0   34.6542        C    A
97          1       1    male  23.00      0      1   63.3583        C    D
98          1       2  female  34.00      0      1   23.0000        S  NaN
99          0       2    male  34.00      1      0   26.0000        S  NaN
100         0       3  female  28.00      0      0    7.8958        S  NaN
101         0       3    male    NaN      0      0    7.8958        S  NaN
102         0       1    male  21.00      0      1   77.2875        S    D
103         0       3    male  33.00      0      0    8.6542        S  NaN
104         0       3    male  37.00      2      0    7.9250        S  NaN
105         0       3    male  28.00      0      0    7.8958        S  NaN
106         1       3  female  21.00      0      0    7.6500        S  NaN
107         1       3    male    NaN      0      0    7.7750        S  NaN
108         0       3    male  38.00      0      0    7.8958        S  NaN
109         1       3  female    NaN      1      0   24.1500        Q  NaN
110         0       1    male  47.00      0      0   52.0000        S    C
111         0       3  female  14.50      1      0   14.4542        C  NaN
112         0       3    male  22.00      0      0    8.0500        S  NaN
113         0       3  female  20.00      1      0    9.8250        S  NaN
114         0       3  female  17.00      0      0   14.4583        C  NaN
115         0       3    male  21.00      0      0    7.9250        S  NaN
116         0       3    male  70.50      0      0    7.7500        Q  NaN
117         0       2    male  29.00      1      0   21.0000        S  NaN
118         0       1    male  24.00      0      1  247.5208        C    B
119         0       3  female   2.00      4      2   31.2750        S  NaN
120         0       2    male  21.00      2      0   73.5000        S  NaN
121         0       3    male    NaN      0      0    8.0500        S  NaN
122         0       2    male  32.50      1      0   30.0708        C  NaN
123         1       2  female  32.50      0      0   13.0000        S    E
124         0       1    male  54.00      0      1   77.2875        S    D
125         1       3    male  12.00      1      0   11.2417        C  NaN
126         0       3    male    NaN      0      0    7.7500        Q  NaN
127         1       3    male  24.00      0      0    7.1417        S  NaN
128         1       3  female    NaN      1      1   22.3583        C    F
129         0       3    male  45.00      0      0    6.9750        S  NaN
130         0       3    male  33.00      0      0    7.8958        C  NaN
131         0       3    male  20.00      0      0    7.0500        S  NaN
132         0       3  female  47.00      1      0   14.5000        S  NaN
133         1       2  female  29.00      1      0   26.0000        S  NaN
134         0       2    male  25.00      0      0   13.0000        S  NaN
135         0       2    male  23.00      0      0   15.0458        C  NaN
136         1       1  female  19.00      0      2   26.2833        S    D
137         0       1    male  37.00      1      0   53.1000        S    C
138         0       3    male  16.00      0      0    9.2167        S  NaN
139         0       1    male  24.00      0      0   79.2000        C    B
140         0       3  female    NaN      0      2   15.2458        C  NaN
141         1       3  female  22.00      0      0    7.7500        S  NaN
142         1       3  female  24.00      1      0   15.8500        S  NaN
143         0       3    male  19.00      0      0    6.7500        Q  NaN
144         0       2    male  18.00      0      0   11.5000        S  NaN
145         0       2    male  19.00      1      1   36.7500        S  NaN
146         1       3    male  27.00      0      0    7.7958        S  NaN
147         0       3  female   9.00      2      2   34.3750        S  NaN
148         0       2    male  36.50      0      2   26.0000        S    F
149         0       2    male  42.00      0      0   13.0000        S  NaN
150         0       2    male  51.00      0      0   12.5250        S  NaN
151         1       1  female  22.00      1      0   66.6000        S    C
152         0       3    male  55.50      0      0    8.0500        S  NaN
153         0       3    male  40.50      0      2   14.5000        S  NaN
154         0       3    male    NaN      0      0    7.3125        S  NaN
155         0       1    male  51.00      0      1   61.3792        C  NaN
156         1       3  female  16.00      0      0    7.7333        Q  NaN
157         0       3    male  30.00      0      0    8.0500        S  NaN
158         0       3    male    NaN      0      0    8.6625        S  NaN
159         0       3    male    NaN      8      2   69.5500        S  NaN
160         0       3    male  44.00      0      1   16.1000        S  NaN
161         1       2  female  40.00      0      0   15.7500        S  NaN
162         0       3    male  26.00      0      0    7.7750        S  NaN
163         0       3    male  17.00      0      0    8.6625        S  NaN
164         0       3    male   1.00      4      1   39.6875        S  NaN
165         1       3    male   9.00      0      2   20.5250        S  NaN
166         1       1  female    NaN      0      1   55.0000        S    E
167         0       3  female  45.00      1      4   27.9000        S  NaN
168         0       1    male    NaN      0      0   25.9250        S  NaN
169         0       3    male  28.00      0      0   56.4958        S  NaN
170         0       1    male  61.00      0      0   33.5000        S    B
171         0       3    male   4.00      4      1   29.1250        Q  NaN
172         1       3  female   1.00      1      1   11.1333        S  NaN
173         0       3    male  21.00      0      0    7.9250        S  NaN
174         0       1    male  56.00      0      0   30.6958        C    A
175         0       3    male  18.00      1      1    7.8542        S  NaN
176         0       3    male    NaN      3      1   25.4667        S  NaN
177         0       1  female  50.00      0      0   28.7125        C    C
178         0       2    male  30.00      0      0   13.0000        S  NaN
179         0       3    male  36.00      0      0    0.0000        S  NaN
180         0       3  female    NaN      8      2   69.5500        S  NaN
181         0       2    male    NaN      0      0   15.0500        C  NaN
182         0       3    male   9.00      4      2   31.3875        S  NaN
183         1       2    male   1.00      2      1   39.0000        S    F
184         1       3  female   4.00      0      2   22.0250        S  NaN
185         0       1    male    NaN      0      0   50.0000        S    A
186         1       3  female    NaN      1      0   15.5000        Q  NaN
187         1       1    male  45.00      0      0   26.5500        S  NaN
188         0       3    male  40.00      1      1   15.5000        Q  NaN
189         0       3    male  36.00      0      0    7.8958        S  NaN
190         1       2  female  32.00      0      0   13.0000        S  NaN
191         0       2    male  19.00      0      0   13.0000        S  NaN
192         1       3  female  19.00      1      0    7.8542        S  NaN
193         1       2    male   3.00      1      1   26.0000        S    F
194         1       1  female  44.00      0      0   27.7208        C    B
195         1       1  female  58.00      0      0  146.5208        C    B
196         0       3    male    NaN      0      0    7.7500        Q  NaN
197         0       3    male  42.00      0      1    8.4042        S  NaN
198         1       3  female    NaN      0      0    7.7500        Q  NaN
199         0       2  female  24.00      0      0   13.0000        S  NaN
200         0       3    male  28.00      0      0    9.5000        S  NaN
201         0       3    male    NaN      8      2   69.5500        S  NaN
202         0       3    male  34.00      0      0    6.4958        S  NaN
203         0       3    male  45.50      0      0    7.2250        C  NaN
204         1       3    male  18.00      0      0    8.0500        S  NaN
205         0       3  female   2.00      0      1   10.4625        S    G
206         0       3    male  32.00      1      0   15.8500        S  NaN
207         1       3    male  26.00      0      0   18.7875        C  NaN
208         1       3  female  16.00      0      0    7.7500        Q  NaN
209         1       1    male  40.00      0      0   31.0000        C    A
210         0       3    male  24.00      0      0    7.0500        S  NaN
211         1       2  female  35.00      0      0   21.0000        S  NaN
212         0       3    male  22.00      0      0    7.2500        S  NaN
213         0       2    male  30.00      0      0   13.0000        S  NaN
214         0       3    male    NaN      1      0    7.7500        Q  NaN
215         1       1  female  31.00      1      0  113.2750        C    D
216         1       3  female  27.00      0      0    7.9250        S  NaN
217         0       2    male  42.00      1      0   27.0000        S  NaN
218         1       1  female  32.00      0      0   76.2917        C    D
219         0       2    male  30.00      0      0   10.5000        S  NaN
220         1       3    male  16.00      0      0    8.0500        S  NaN
221         0       2    male  27.00      0      0   13.0000        S  NaN
222         0       3    male  51.00      0      0    8.0500        S  NaN
223         0       3    male    NaN      0      0    7.8958        S  NaN
224         1       1    male  38.00      1      0   90.0000        S    C
225         0       3    male  22.00      0      0    9.3500        S  NaN
226         1       2    male  19.00      0      0   10.5000        S  NaN
227         0       3    male  20.50      0      0    7.2500        S  NaN
228         0       2    male  18.00      0      0   13.0000        S  NaN
229         0       3  female    NaN      3      1   25.4667        S  NaN
230         1       1  female  35.00      1      0   83.4750        S    C
231         0       3    male  29.00      0      0    7.7750        S  NaN
232         0       2    male  59.00      0      0   13.5000        S  NaN
233         1       3  female   5.00      4      2   31.3875        S  NaN
234         0       2    male  24.00      0      0   10.5000        S  NaN
235         0       3  female    NaN      0      0    7.5500        S  NaN
236         0       2    male  44.00      1      0   26.0000        S  NaN
237         1       2  female   8.00      0      2   26.2500        S  NaN
238         0       2    male  19.00      0      0   10.5000        S  NaN
239         0       2    male  33.00      0      0   12.2750        S  NaN
240         0       3  female    NaN      1      0   14.4542        C  NaN
241         1       3  female    NaN      1      0   15.5000        Q  NaN
242         0       2    male  29.00      0      0   10.5000        S  NaN
243         0       3    male  22.00      0      0    7.1250        S  NaN
244         0       3    male  30.00      0      0    7.2250        C  NaN
245         0       1    male  44.00      2      0   90.0000        Q    C
246         0       3  female  25.00      0      0    7.7750        S  NaN
247         1       2  female  24.00      0      2   14.5000        S  NaN
248         1       1    male  37.00      1      1   52.5542        S    D
249         0       2    male  54.00      1      0   26.0000        S  NaN
250         0       3    male    NaN      0      0    7.2500        S  NaN
251         0       3  female  29.00      1      1   10.4625        S    G
252         0       1    male  62.00      0      0   26.5500        S    C
253         0       3    male  30.00      1      0   16.1000        S  NaN
254         0       3  female  41.00      0      2   20.2125        S  NaN
255         1       3  female  29.00      0      2   15.2458        C  NaN
256         1       1  female    NaN      0      0   79.2000        C  NaN
257         1       1  female  30.00      0      0   86.5000        S    B
258         1       1  female  35.00      0      0  512.3292        C  NaN
259         1       2  female  50.00      0      1   26.0000        S  NaN
260         0       3    male    NaN      0      0    7.7500        Q  NaN
261         1       3    male   3.00      4      2   31.3875        S  NaN
262         0       1    male  52.00      1      1   79.6500        S    E
263         0       1    male  40.00      0      0    0.0000        S    B
264         0       3  female    NaN      0      0    7.7500        Q  NaN

### nunique(), nlargest() and nsmallest() with DataFrames

In [42]:
import pandas as pd

In [43]:
titanic = pd.read_csv("titanic.csv")

In [44]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [45]:
titanic.tail()

     survived  pclass     sex   age  sibsp  parch   fare embarked deck
886         0       2    male  27.0      0      0  13.00        S  NaN
887         1       1  female  19.0      0      0  30.00        S    B
888         0       3  female   NaN      1      2  23.45        S  NaN
889         1       1    male  26.0      0      0  30.00        C    C
890         0       3    male  32.0      0      0   7.75        Q  NaN

In [47]:
titanic.age.unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [62]:
titanic.nunique(axis = 1, dropna=False)

0      8
1      6
2      8
3      7
4      7
5      6
6      7
7      8
8      9
9      8
10     7
11     7
12     7
13     9
14     7
15     8
16     9
17     7
18     8
19     7
20     7
21     8
22     8
23     7
24     8
25     8
26     6
27     9
28     7
29     6
30     7
31     7
32     7
33     7
34     7
35     7
36     7
37     7
38     7
39     8
40     8
41     8
42     6
43     7
44     8
45     6
46     7
47     7
48     7
49     8
50     9
51     7
52     7
53     8
54     7
55     7
56     8
57     7
58     7
59     9
60     7
61     7
62     7
63     8
64     6
65     6
66     8
67     7
68     9
69     8
70     7
71     9
72     7
73     8
74     8
75     7
76     6
77     6
78     8
79     8
80     7
81     8
82     7
83     7
84     8
85     8
86     8
87     6
88     8
89     7
90     7
91     7
92     7
93     9
94     7
95     6
96     7
97     7
98     8
99     8
100    7
101    6
102    7
103    7
104    8
105    7
106    8
107    7
108    7
109    7
110    7
111    8
112    7
113    8
114    7
115    7
116    7
117    8
118    7
119    8
120    7
121    6
122    8
123    8
124    7
125    8
126    6
127    8
128    7
129    7
130    7
131    7
132    8
133    8
134    7
135    7
136    8
137    7
138    7
139    7
140    7
141    8
142    8
143    7
144    7
145    8
146    8
147    8
148    7
149    7
150    7
151    7
152    7
153    8
154    6
155    7
156    8
157    7
158    6
159    8
160    8
161    8
162    7
163    7
164    8
165    9
166    7
167    9
168    6
169    7
170    7
171    8
172    6
173    7
174    7
175    8
176    7
177    6
178    7
179    6
180    8
181    6
182    9
183    6
184    9
185    7
186    7
187    7
188    8
189    7
190    8
191    7
192    8
193    7
194    7
195    7
196    6
197    8
198    7
199    7
200    7
201    8
202    7
203    7
204    8
205    8
206    8
207    8
208    8
209    7
210    7
211    8
212    7
213    7
214    7
215    7
216    8
217    8
218    7
219    7
220    8
221    7
222    7
223    6
224    7
225    7
226    8
227    7
228    7
229    7
230    7
231    7
232    7
233    9
234    7
235    6
236    8
237    8
238    7
239    7
240    7
241    7
242    7
243    7
244    7
245    8
246    7
247    8
248    6
249    8
250    6
251    8
252    7
253    8
254    8
255    9
256    6
257    7
258    7
259    8
260    6
261    8
262    7
263    6
264    6
265    7
266    9
267    8
268    7
269    7
270    6
271    7
272    8
273    6
274    7
275    7
276    7
277    5
278    9
279    7
280    7
281    7
282    7
283    8
284    7
285    7
286    8
287    7
288    8
289    8
290    7
291    7
292    7
293    7
294    7
295    6
296    7
297    7
298    7
299    7
300    7
301    8
302    6
303    8
304    6
305    7
306    6
307    6
308    8
309    7
310    6
311    7
312    7
313    7
314    8
315    8
316    8
317    7
318    8
319    6
320    7
321    7
322    8
323    7
324    8
325    6
326    7
327    8
328    7
329    7
330    8
331    7
332    7
333    8
334    6
335    6
336    7
337    7
338    8
339    7
340    6
341    8
342    7
343    7
344    7
345    8
346    8
347    7
348    6
349    7
350    7
351    7
352    8
353    8
354    6
355    7
356    7
357    7
358    7
359    7
360    9
361    8
362    8
363    7
364    7
365    7
366    7
367    7
368    7
369    7
370    7
371    8
372    7
373    7
374    7
375    6
376    8
377    7
378    7
379    7
380    7
381    8
382    7
383    7
384    6
385    7
386    9
387    8
388    6
389    8
390    7
391    8
392    8
393    7
394    9
395    7
396    7
397    7
398    7
399    8
400    8
401    7
402    8
403    8
404    7
405    8
406    7
407    7
408    7
409    7
410    6
411    6
412    7
413    5
414    8
415    6
416    7
417    8
418    7
419    8
420    6
421    7
422    7
423    8
424    8
425    6
426    8
427    8
428    6
429    8
430    7
431    7
432    8
433    7
434    7
435    7
436    8
437    8
438    8
439    7
440    7
441    7
442    8
443    8
444    7
445    8
446    8
447    7
448    8
449    7
450    8
451    7
452    6
453    6
454    6
455    8
456    7
457    7
458    8
459    6
460    7
461    7
462    7
463    7
464    6
465    7
466    5
467    7
468    6
469    8
470    6
471    7
472    7
473    8
474    7
475    7
476    8
477    8
478    7
479    8
480    9
481    5
482    7
483    8
484    7
485    7
486    7
487    7
488    7
489    7
490    7
491    7
492    7
493    7
494    7
495    6
496    7
497    6
498    8
499    7
500    7
501    7
502    6
503    7
504    7
505    6
506    8
507    6
508    7
509    8
510    8
511    6
512    7
513    7
514    7
515    7
516    8
517    6
518    8
519    7
520    7
521    7
522    6
523    7
524    6
525    7
526    8
527    7
528    7
529    8
530    6
531    6
532    8
533    8
534    7
535    8
536    7
537    7
538    6
539    8
540    8
541    9
542    9
543    8
544    6
545    7
546    8
547    7
548    8
549    7
550    7
551    7
552    6
553    8
554    8
555    7
556    7
557    6
558    6
559    8
560    6
561    7
562    7
563    6
564    6
565    8
566    7
567    8
568    6
569    8
570    8
571    8
572    7
573    7
574    7
575    7
576    8
577    7
578    7
579    8
580    7
581    5
582    7
583    7
584    6
585    8
586    7
587    6
588    7
589    6
590    7
591    7
592    7
593    7
594    8
595    8
596    7
597    6
598    6
599    7
600    7
601    6
602    6
603    7
604    7
605    8
606    7
607    7
608    7
609    7
610    9
611    6
612    7
613    6
614    7
615    7
616    8
617    8
618    7
619    7
620    8
621    7
622    7
623    7
624    7
625    7
626    7
627    7
628    7
629    6
630    7
631    7
632    7
633    5
634    8
635    8
636    7
637    8
638    8
639    7
640    7
641    7
642    7
643    7
644    8
645    7
646    7
647    7
648    6
649    8
650    6
651    8
652    7
653    7
654    7
655    7
656    6
657    8
658    7
659    8
660    8
661    7
662    7
663    7
664    8
665    7
666    7
667    6
668    7
669    7
670    7
671    7
672    7
673    8
674    5
675    7
676    7
677    8
678    9
679    7
680    6
681    7
682    7
683    9
684    8
685    8
686    9
687    7
688    7
689    7
690    7
691    8
692    7
693    7
694    7
695    7
696    7
697    7
698    6
699    7
700    6
701    7
702    8
703    7
704    8
705    7
706    8
707    7
708    7
709    6
710    6
711    7
712    7
713    7
714    7
715    7
716    6
717    8
718    6
719    7
720    8
721    8
722    7
723    7
724    7
725    7
726    9
727    7
728    8
729    8
730    7
731    7
732    5
733    7
734    7
735    7
736    8
737    7
738    6
739    6
740    7
741    7
742    7
743    8
744    8
745    7
746    8
747    8
748    7
749    7
750    7
751    8
752    7
753    7
754    7
755    7
756    7
757    7
758    7
759    7
760    6
761    7
762    8
763    7
764    7
765    7
766    6
767    7
768    7
769    7
770    7
771    7
772    7
773    6
774    8
775    7
776    7
777    8
778    6
779    7
780    8
781    7
782    7
783    8
784    7
785    7
786    8
787    9
788    7
789    7
790    6
791    7
792    8
793    6
794    7
795    7
796    7
797    8
798    7
799    8
800    7
801    7
802    7
803    8
804    8
805    7
806    6
807    7
808    7
809    7
810    7
811    7
812    7
813    9
814    7
815    6
816    7
817    8
818    7
819    8
820    6
821    8
822    6
823    8
824    9
825    6
826    6
827    7
828    7
829    7
830    8
831    7
832    6
833    7
834    7
835    6
836    7
837    6
838    8
839    6
840    7
841    7
842    7
843    7
844    7
845    7
846    8
847    7
848    8
849    6
850    8
851    7
852    8
853    7
854    8
855    8
856    6
857    7
858    8
859    6
860    8
861    8
862    7
863    8
864    7
865    8
866    8
867    7
868    6
869    7
870    7
871    6
872    7
873    7
874    8
875    8
876    7
877    7
878    6
879    6
880    8
881    7
882    7
883    7
884    7
885    8
886    7
887    7
888    8
889    6
890    7
dtype: int64

In [63]:
titanic.nunique(dropna = False)

survived      2
pclass        3
sex           2
age          89
sibsp         7
parch         7
fare        248
embarked      4
deck          8
dtype: int64

In [51]:
titanic.nlargest(n = 5, columns = "fare")

     survived  pclass     sex   age  sibsp  parch      fare embarked deck
258         1       1  female  35.0      0      0  512.3292        C  NaN
679         1       1    male  36.0      0      1  512.3292        C    B
737         1       1    male  35.0      0      0  512.3292        C    B
27          0       1    male  19.0      3      2  263.0000        S    C
88          1       1  female  23.0      3      2  263.0000        S    C

In [52]:
titanic.sort_values("fare", ascending = False).head(5)

     survived  pclass     sex   age  sibsp  parch      fare embarked deck
258         1       1  female  35.0      0      0  512.3292        C  NaN
737         1       1    male  35.0      0      0  512.3292        C    B
679         1       1    male  36.0      0      1  512.3292        C    B
88          1       1  female  23.0      3      2  263.0000        S    C
27          0       1    male  19.0      3      2  263.0000        S    C

In [53]:
titanic.nsmallest(n = 1, columns = "age")

     survived  pclass   sex   age  sibsp  parch    fare embarked deck
803         1       3  male  0.42      0      1  8.5167        C  NaN

In [54]:
titanic.loc[titanic.age.idxmin()]

survived         1
pclass           3
sex           male
age           0.42
sibsp            0
parch            1
fare        8.5167
embarked         C
deck           NaN
Name: 803, dtype: object

### Summary Statistics and Accumulations

In [55]:
import pandas as pd

In [56]:
titanic = pd.read_csv("titanic.csv")

In [57]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [58]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [59]:
titanic.count(axis = "columns")

0      8
1      9
2      8
3      9
4      8
5      7
6      9
7      8
8      8
9      8
10     9
11     9
12     8
13     8
14     8
15     8
16     8
17     7
18     8
19     7
20     8
21     9
22     8
23     9
24     8
25     8
26     7
27     9
28     7
29     7
30     8
31     8
32     7
33     8
34     8
35     8
36     7
37     8
38     8
39     8
40     8
41     8
42     7
43     8
44     8
45     7
46     7
47     7
48     7
49     8
50     8
51     8
52     9
53     8
54     9
55     8
56     8
57     8
58     8
59     8
60     8
61     8
62     9
63     8
64     7
65     7
66     9
67     8
68     8
69     8
70     8
71     8
72     8
73     8
74     8
75     9
76     7
77     7
78     8
79     8
80     8
81     8
82     7
83     8
84     8
85     8
86     8
87     7
88     9
89     8
90     8
91     8
92     9
93     8
94     8
95     7
96     9
97     9
98     8
99     8
100    8
101    7
102    9
103    8
104    8
105    8
106    8
107    7
108    8
109    7
110    9
111    8
112    8
113    8
114    8
115    8
116    8
117    8
118    9
119    8
120    8
121    7
122    8
123    9
124    9
125    8
126    7
127    8
128    8
129    8
130    8
131    8
132    8
133    8
134    8
135    8
136    9
137    9
138    8
139    9
140    7
141    8
142    8
143    8
144    8
145    8
146    8
147    8
148    9
149    8
150    8
151    9
152    8
153    8
154    7
155    8
156    8
157    8
158    7
159    7
160    8
161    8
162    8
163    8
164    8
165    8
166    8
167    8
168    7
169    8
170    9
171    8
172    8
173    8
174    9
175    8
176    7
177    9
178    8
179    8
180    7
181    7
182    8
183    9
184    8
185    8
186    7
187    8
188    8
189    8
190    8
191    8
192    8
193    9
194    9
195    9
196    7
197    8
198    7
199    8
200    8
201    7
202    8
203    8
204    8
205    9
206    8
207    8
208    8
209    9
210    8
211    8
212    8
213    8
214    7
215    9
216    8
217    8
218    9
219    8
220    8
221    8
222    8
223    7
224    9
225    8
226    8
227    8
228    8
229    7
230    9
231    8
232    8
233    8
234    8
235    7
236    8
237    8
238    8
239    8
240    7
241    7
242    8
243    8
244    8
245    9
246    8
247    8
248    9
249    8
250    7
251    9
252    9
253    8
254    8
255    8
256    7
257    9
258    8
259    8
260    7
261    8
262    9
263    9
264    7
265    8
266    8
267    8
268    9
269    9
270    7
271    8
272    8
273    9
274    7
275    9
276    8
277    7
278    8
279    8
280    8
281    8
282    8
283    8
284    8
285    8
286    8
287    8
288    8
289    8
290    8
291    9
292    9
293    8
294    8
295    7
296    8
297    9
298    8
299    9
300    7
301    7
302    8
303    8
304    7
305    9
306    7
307    9
308    8
309    9
310    9
311    9
312    8
313    8
314    8
315    8
316    8
317    8
318    9
319    9
320    8
321    8
322    8
323    8
324    7
325    9
326    8
327    9
328    8
329    9
330    7
331    9
332    9
333    8
334    7
335    7
336    9
337    9
338    8
339    8
340    9
341    9
342    8
343    8
344    8
345    9
346    8
347    7
348    8
349    8
350    8
351    8
352    8
353    8
354    7
355    8
356    9
357    8
358    7
359    7
360    8
361    8
362    8
363    8
364    7
365    8
366    9
367    7
368    7
369    9
370    9
371    8
372    8
373    8
374    8
375    7
376    8
377    9
378    8
379    8
380    8
381    8
382    8
383    8
384    7
385    8
386    8
387    8
388    7
389    8
390    9
391    8
392    8
393    9
394    9
395    8
396    8
397    8
398    8
399    8
400    8
401    8
402    8
403    8
404    8
405    8
406    8
407    8
408    8
409    7
410    7
411    7
412    9
413    7
414    8
415    7
416    8
417    8
418    8
419    8
420    7
421    8
422    8
423    8
424    8
425    7
426    8
427    8
428    7
429    9
430    9
431    7
432    8
433    8
434    9
435    9
436    8
437    8
438    9
439    8
440    8
441    8
442    8
443    8
444    7
445    9
446    8
447    8
448    8
449    9
450    8
451    7
452    9
453    9
454    7
455    8
456    9
457    8
458    8
459    7
460    9
461    8
462    9
463    8
464    7
465    8
466    7
467    8
468    7
469    8
470    7
471    8
472    8
473    9
474    8
475    8
476    8
477    8
478    8
479    8
480    8
481    7
482    8
483    8
484    9
485    7
486    9
487    9
488    8
489    8
490    7
491    8
492    9
493    8
494    8
495    7
496    9
497    7
498    9
499    8
500    8
501    8
502    7
503    8
504    9
505    9
506    8
507    7
508    8
509    8
510    8
511    7
512    9
513    8
514    8
515    9
516    9
517    7
518    8
519    8
520    9
521    8
522    7
523    9
524    7
525    8
526    8
527    8
528    8
529    8
530    8
531    7
532    8
533    7
534    8
535    8
536    9
537    8
538    7
539    9
540    9
541    8
542    8
543    8
544    9
545    8
546    8
547    7
548    8
549    8
550    9
551    8
552    7
553    8
554    8
555    8
556    9
557    7
558    9
559    8
560    7
561    8
562    8
563    7
564    7
565    8
566    8
567    8
568    7
569    8
570    8
571    9
572    9
573    7
574    8
575    8
576    8
577    9
578    7
579    8
580    8
581    9
582    8
583    9
584    7
585    9
586    8
587    9
588    8
589    7
590    8
591    9
592    8
593    7
594    8
595    8
596    7
597    8
598    7
599    9
600    8
601    7
602    7
603    8
604    8
605    8
606    8
607    8
608    8
609    9
610    8
611    7
612    7
613    7
614    8
615    8
616    8
617    8
618    9
619    8
620    8
621    9
622    8
623    8
624    8
625    9
626    8
627    9
628    8
629    7
630    9
631    8
632    9
633    7
634    8
635    8
636    8
637    8
638    8
639    7
640    8
641    9
642    8
643    7
644    8
645    9
646    8
647    9
648    7
649    8
650    7
651    8
652    8
653    7
654    8
655    8
656    7
657    8
658    8
659    9
660    8
661    8
662    9
663    8
664    8
665    8
666    8
667    7
668    8
669    8
670    8
671    9
672    8
673    8
674    7
675    8
676    8
677    8
678    8
679    9
680    7
681    9
682    8
683    8
684    8
685    8
686    8
687    8
688    8
689    9
690    9
691    8
692    7
693    8
694    8
695    8
696    8
697    7
698    9
699    9
700    9
701    9
702    8
703    8
704    8
705    8
706    8
707    9
708    8
709    7
710    9
711    8
712    9
713    8
714    8
715    9
716    9
717    9
718    7
719    8
720    8
721    8
722    8
723    8
724    9
725    8
726    8
727    7
728    8
729    8
730    9
731    8
732    7
733    8
734    8
735    8
736    8
737    9
738    7
739    7
740    8
741    9
742    9
743    8
744    8
745    9
746    8
747    8
748    9
749    8
750    8
751    9
752    8
753    8
754    8
755    8
756    8
757    8
758    8
759    9
760    7
761    8
762    8
763    9
764    8
765    9
766    7
767    8
768    7
769    8
770    8
771    8
772    9
773    7
774    8
775    8
776    8
777    8
778    7
779    9
780    8
781    9
782    9
783    7
784    8
785    8
786    8
787    8
788    8
789    9
790    7
791    8
792    7
793    7
794    8
795    8
796    9
797    8
798    8
799    8
800    8
801    8
802    9
803    8
804    8
805    8
806    9
807    8
808    8
809    9
810    8
811    8
812    8
813    8
814    8
815    8
816    8
817    8
818    8
819    8
820    9
821    8
822    8
823    9
824    8
825    7
826    7
827    8
828    7
829    8
830    8
831    8
832    7
833    8
834    8
835    9
836    8
837    7
838    8
839    8
840    8
841    8
842    8
843    8
844    8
845    8
846    7
847    8
848    8
849    8
850    8
851    8
852    8
853    9
854    8
855    8
856    8
857    9
858    8
859    7
860    8
861    8
862    9
863    7
864    8
865    8
866    8
867    9
868    7
869    8
870    8
871    9
872    9
873    8
874    8
875    8
876    8
877    8
878    7
879    9
880    8
881    8
882    8
883    8
884    8
885    8
886    8
887    9
888    7
889    9
890    8
dtype: int64

In [60]:
titanic.count(axis = 1)

0      8
1      9
2      8
3      9
4      8
5      7
6      9
7      8
8      8
9      8
10     9
11     9
12     8
13     8
14     8
15     8
16     8
17     7
18     8
19     7
20     8
21     9
22     8
23     9
24     8
25     8
26     7
27     9
28     7
29     7
30     8
31     8
32     7
33     8
34     8
35     8
36     7
37     8
38     8
39     8
40     8
41     8
42     7
43     8
44     8
45     7
46     7
47     7
48     7
49     8
50     8
51     8
52     9
53     8
54     9
55     8
56     8
57     8
58     8
59     8
60     8
61     8
62     9
63     8
64     7
65     7
66     9
67     8
68     8
69     8
70     8
71     8
72     8
73     8
74     8
75     9
76     7
77     7
78     8
79     8
80     8
81     8
82     7
83     8
84     8
85     8
86     8
87     7
88     9
89     8
90     8
91     8
92     9
93     8
94     8
95     7
96     9
97     9
98     8
99     8
100    8
101    7
102    9
103    8
104    8
105    8
106    8
107    7
108    8
109    7
110    9
111    8
112    8
113    8
114    8
115    8
116    8
117    8
118    9
119    8
120    8
121    7
122    8
123    9
124    9
125    8
126    7
127    8
128    8
129    8
130    8
131    8
132    8
133    8
134    8
135    8
136    9
137    9
138    8
139    9
140    7
141    8
142    8
143    8
144    8
145    8
146    8
147    8
148    9
149    8
150    8
151    9
152    8
153    8
154    7
155    8
156    8
157    8
158    7
159    7
160    8
161    8
162    8
163    8
164    8
165    8
166    8
167    8
168    7
169    8
170    9
171    8
172    8
173    8
174    9
175    8
176    7
177    9
178    8
179    8
180    7
181    7
182    8
183    9
184    8
185    8
186    7
187    8
188    8
189    8
190    8
191    8
192    8
193    9
194    9
195    9
196    7
197    8
198    7
199    8
200    8
201    7
202    8
203    8
204    8
205    9
206    8
207    8
208    8
209    9
210    8
211    8
212    8
213    8
214    7
215    9
216    8
217    8
218    9
219    8
220    8
221    8
222    8
223    7
224    9
225    8
226    8
227    8
228    8
229    7
230    9
231    8
232    8
233    8
234    8
235    7
236    8
237    8
238    8
239    8
240    7
241    7
242    8
243    8
244    8
245    9
246    8
247    8
248    9
249    8
250    7
251    9
252    9
253    8
254    8
255    8
256    7
257    9
258    8
259    8
260    7
261    8
262    9
263    9
264    7
265    8
266    8
267    8
268    9
269    9
270    7
271    8
272    8
273    9
274    7
275    9
276    8
277    7
278    8
279    8
280    8
281    8
282    8
283    8
284    8
285    8
286    8
287    8
288    8
289    8
290    8
291    9
292    9
293    8
294    8
295    7
296    8
297    9
298    8
299    9
300    7
301    7
302    8
303    8
304    7
305    9
306    7
307    9
308    8
309    9
310    9
311    9
312    8
313    8
314    8
315    8
316    8
317    8
318    9
319    9
320    8
321    8
322    8
323    8
324    7
325    9
326    8
327    9
328    8
329    9
330    7
331    9
332    9
333    8
334    7
335    7
336    9
337    9
338    8
339    8
340    9
341    9
342    8
343    8
344    8
345    9
346    8
347    7
348    8
349    8
350    8
351    8
352    8
353    8
354    7
355    8
356    9
357    8
358    7
359    7
360    8
361    8
362    8
363    8
364    7
365    8
366    9
367    7
368    7
369    9
370    9
371    8
372    8
373    8
374    8
375    7
376    8
377    9
378    8
379    8
380    8
381    8
382    8
383    8
384    7
385    8
386    8
387    8
388    7
389    8
390    9
391    8
392    8
393    9
394    9
395    8
396    8
397    8
398    8
399    8
400    8
401    8
402    8
403    8
404    8
405    8
406    8
407    8
408    8
409    7
410    7
411    7
412    9
413    7
414    8
415    7
416    8
417    8
418    8
419    8
420    7
421    8
422    8
423    8
424    8
425    7
426    8
427    8
428    7
429    9
430    9
431    7
432    8
433    8
434    9
435    9
436    8
437    8
438    9
439    8
440    8
441    8
442    8
443    8
444    7
445    9
446    8
447    8
448    8
449    9
450    8
451    7
452    9
453    9
454    7
455    8
456    9
457    8
458    8
459    7
460    9
461    8
462    9
463    8
464    7
465    8
466    7
467    8
468    7
469    8
470    7
471    8
472    8
473    9
474    8
475    8
476    8
477    8
478    8
479    8
480    8
481    7
482    8
483    8
484    9
485    7
486    9
487    9
488    8
489    8
490    7
491    8
492    9
493    8
494    8
495    7
496    9
497    7
498    9
499    8
500    8
501    8
502    7
503    8
504    9
505    9
506    8
507    7
508    8
509    8
510    8
511    7
512    9
513    8
514    8
515    9
516    9
517    7
518    8
519    8
520    9
521    8
522    7
523    9
524    7
525    8
526    8
527    8
528    8
529    8
530    8
531    7
532    8
533    7
534    8
535    8
536    9
537    8
538    7
539    9
540    9
541    8
542    8
543    8
544    9
545    8
546    8
547    7
548    8
549    8
550    9
551    8
552    7
553    8
554    8
555    8
556    9
557    7
558    9
559    8
560    7
561    8
562    8
563    7
564    7
565    8
566    8
567    8
568    7
569    8
570    8
571    9
572    9
573    7
574    8
575    8
576    8
577    9
578    7
579    8
580    8
581    9
582    8
583    9
584    7
585    9
586    8
587    9
588    8
589    7
590    8
591    9
592    8
593    7
594    8
595    8
596    7
597    8
598    7
599    9
600    8
601    7
602    7
603    8
604    8
605    8
606    8
607    8
608    8
609    9
610    8
611    7
612    7
613    7
614    8
615    8
616    8
617    8
618    9
619    8
620    8
621    9
622    8
623    8
624    8
625    9
626    8
627    9
628    8
629    7
630    9
631    8
632    9
633    7
634    8
635    8
636    8
637    8
638    8
639    7
640    8
641    9
642    8
643    7
644    8
645    9
646    8
647    9
648    7
649    8
650    7
651    8
652    8
653    7
654    8
655    8
656    7
657    8
658    8
659    9
660    8
661    8
662    9
663    8
664    8
665    8
666    8
667    7
668    8
669    8
670    8
671    9
672    8
673    8
674    7
675    8
676    8
677    8
678    8
679    9
680    7
681    9
682    8
683    8
684    8
685    8
686    8
687    8
688    8
689    9
690    9
691    8
692    7
693    8
694    8
695    8
696    8
697    7
698    9
699    9
700    9
701    9
702    8
703    8
704    8
705    8
706    8
707    9
708    8
709    7
710    9
711    8
712    9
713    8
714    8
715    9
716    9
717    9
718    7
719    8
720    8
721    8
722    8
723    8
724    9
725    8
726    8
727    7
728    8
729    8
730    9
731    8
732    7
733    8
734    8
735    8
736    8
737    9
738    7
739    7
740    8
741    9
742    9
743    8
744    8
745    9
746    8
747    8
748    9
749    8
750    8
751    9
752    8
753    8
754    8
755    8
756    8
757    8
758    8
759    9
760    7
761    8
762    8
763    9
764    8
765    9
766    7
767    8
768    7
769    8
770    8
771    8
772    9
773    7
774    8
775    8
776    8
777    8
778    7
779    9
780    8
781    9
782    9
783    7
784    8
785    8
786    8
787    8
788    8
789    9
790    7
791    8
792    7
793    7
794    8
795    8
796    9
797    8
798    8
799    8
800    8
801    8
802    9
803    8
804    8
805    8
806    9
807    8
808    8
809    9
810    8
811    8
812    8
813    8
814    8
815    8
816    8
817    8
818    8
819    8
820    9
821    8
822    8
823    9
824    8
825    7
826    7
827    8
828    7
829    8
830    8
831    8
832    7
833    8
834    8
835    9
836    8
837    7
838    8
839    8
840    8
841    8
842    8
843    8
844    8
845    8
846    7
847    8
848    8
849    8
850    8
851    8
852    8
853    9
854    8
855    8
856    8
857    9
858    8
859    7
860    8
861    8
862    9
863    7
864    8
865    8
866    8
867    9
868    7
869    8
870    8
871    9
872    9
873    8
874    8
875    8
876    8
877    8
878    7
879    9
880    8
881    8
882    8
883    8
884    8
885    8
886    8
887    9
888    7
889    9
890    8
dtype: int64

In [61]:
titanic.mean(axis = 1) # old

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
titanic.mean(axis = 1, numeric_only=True) # new

In [ ]:
titanic.sum(axis = 0) # old

In [ ]:
titanic.sum(axis = 0, numeric_only=True) # new

In [ ]:
titanic.head()

In [ ]:
titanic.fare.cumsum(axis = 0)

In [ ]:
titanic.corr() # old

In [ ]:
titanic.corr(numeric_only=True) # new

In [ ]:
titanic.survived.corr(titanic.pclass)

### The agg() method

In [ ]:
import pandas as pd

In [ ]:
titanic = pd.read_csv("titanic.csv")

In [ ]:
titanic.head()

In [ ]:
titanic.describe()

In [ ]:
#titanic.mean() # old

In [ ]:
titanic.mean(numeric_only=True) # new

In [ ]:
titanic.agg("mean") # old

In [ ]:
titanic.agg("mean", numeric_only=True) # new but not recommended

In [ ]:
titanic.select_dtypes("number").agg("mean") # new and best practise

In [ ]:
titanic.select_dtypes("number").agg(["mean", "std"])

In [ ]:
titanic.select_dtypes("number").agg(["mean", "std", "min", "max", "median"])

In [ ]:
titanic.select_dtypes("number").agg({"survived": "mean", "age":["min", "max"]})

### apply(), map() and applymap()

In [ ]:
import pandas as pd

In [ ]:
sales = pd.read_csv("sales.csv", index_col = 0)

In [ ]:
sales

In [ ]:
sales.info()

In [ ]:
sales.min(axis = 0)

In [ ]:
sales.min(axis = 1)

In [ ]:
def range_f(series):
    return series.max() - series.min()

In [ ]:
sales.apply(range_f, axis = 0)

In [ ]:
sales.apply(lambda x: x.max() - x.min(), axis = 0)

In [ ]:
summer = pd.read_csv("summer.csv")

In [ ]:
summer.head()

In [ ]:
summer.Athlete.apply(lambda x: x[0])

In [ ]:
summer.Athlete.map(lambda x: x[0])

In [ ]:
summer.iloc[:,1:3].applymap(lambda x: x[0]) #old

In [ ]:
summer.iloc[:,1:3].map(lambda x: x[0]) # new

In [ ]:
sales.applymap(lambda x: 0.4*x-5) # old

In [ ]:
sales.map(lambda x: 0.4*x-5) # new

In [ ]:
sales*0.4-5

### Hierarchical Indexing (MultiIndex) Intro

In [ ]:
import pandas as pd

In [ ]:
titanic = pd.read_csv("titanic.csv")

In [ ]:
titanic

In [ ]:
titanic = titanic.iloc[:50, :]

In [ ]:
titanic.set_index(["pclass", "sex"], inplace = True)

In [ ]:
titanic

In [ ]:
titanic.sort_index(ascending = [True, True], inplace = True )

In [ ]:
titanic

In [ ]:
titanic.swaplevel()

In [ ]:
titanic

In [ ]:
titanic.reset_index(inplace = True)

In [ ]:
titanic

### Hierarchical Indexing (MultiIndex) Part 2

In [ ]:
import pandas as pd

In [ ]:
titanic = pd.read_csv("titanic.csv")

In [ ]:
titanic = titanic.iloc[:50,]

In [ ]:
titanic

In [ ]:
titanic = titanic.set_index(["pclass", "sex"]).sort_index(ascending = True)

In [ ]:
titanic

In [ ]:
titanic.loc[1]

In [ ]:
titanic.loc[[1,2]]

In [ ]:
titanic.loc[:2]

In [ ]:
titanic.loc[1, "female"]

In [ ]:
#titanic.loc[1, "female", "age"]

In [ ]:
titanic.loc[(1,"female")]

In [ ]:
titanic.loc[(1,"female"), "age"]

In [ ]:
titanic.loc[([1,2],"female"), ["age", "fare"]]

In [ ]:
titanic.loc[([1, 2],"female"), :]

In [ ]:
titanic

In [ ]:
titanic.loc[(slice(1), slice("female")), :]

### String Operations Intro / Refresher

In [ ]:
"Hello World"

In [ ]:
type("Hello World")

In [ ]:
hello = "Hello World"
hello

In [ ]:
len(hello)

In [ ]:
hello.lower()

In [ ]:
hello.upper()

In [ ]:
hello.title()

In [ ]:
hello.split(" ")

In [ ]:
hello.replace("Hello", "Hi")

In [ ]:
import pandas as pd

In [ ]:
summer = pd.read_csv("summer.csv")

In [ ]:
summer.head()

In [ ]:
names = summer.loc[:9, "Athlete"].copy()

In [ ]:
names

In [ ]:
names.dtypes

In [ ]:
names[0]

In [ ]:
type(names[0])

In [ ]:
names.str.lower()

### String Operations in Pandas

In [ ]:
import pandas as pd

In [ ]:
summer = pd.read_csv("summer.csv")

In [ ]:
summer.head()

In [ ]:
names = summer.loc[:9, "Athlete"].copy()

In [ ]:
names

In [ ]:
names.str.lower()

In [ ]:
names.str.title()

In [ ]:
summer.Event.str.split(" ", n = 2, expand= True)

In [ ]:
summer[summer.Event.str.contains("100M")]